[PopupMenu]
Showlayerslope=0
ShearHideAllComments=0
LayersHideAllComments=0
RamHideAllLayers=0
SnowTempHideAllLayers=0
ShearStress=0
HardnessType=0

[File]
Release=3.0

[Id]
Location=Bow Summit Plot
Title1=Parks Canada
Title2=Banff/Yoho/Kootenay
Date=11/1/2001
Time=12:00
Observer=BW,A.L.
Altitude=
AltUnits=Metres
Coords=      ,
Aspect=8
Slope=0
ProfileNbr=
ProfileType=Full

[Surface]
Roughness=Smooth
AirTemp=-1.0
PackHeight=50
LayerDown=0
PlotDown=0

[Penetration]
Ski= 10
Foot= 20

[Wind]
Speed=
Direction=N/A

[Sky]
Condition=Scattered Clouds

[Ram]
Hardness=

[Precip]
Type=Nil
Rate=

[SnowTempLayers]
MinTemperatureScale=-11
Count=6
SnowColour=4194432
SnowLine=16711680

[SnowHeight]
1=0
2=10
3=20
4=30
5=40
6=50

[SnowTemp]
1=-0.6
2=-0.9
3=-1.6
4=-2.9
5=-4.1
6=-3.8

[RamLayers]
RamColour=8404992
HardnessOnly=0
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1100
HandRamScale=0

[CrystalLayerHeight]
SymbolColour=8404992
1=-1
2=6
3=27
4=29
5=34
6=38
7=42
8=48
9=50

[Comments]
Count=1
1=Strong snowpack for this time of year. No new natural activity seen on the 93 N.
Stability=U

[CrystalLLayers]
BottomOfPit=0
Count=9

[CrystalLayerWaterContent]
1=Dry
2=Moist
3=Dry
4=Dry
5=Dry
6=Dry
7=Dry
8=Dry
9=Dry

[CrystalLayerGrainForm1]
1=1
2=4
3=4
4=9e
5=4c
6=4c
7=9b
8=2
9=2

[CrystalLayerGrainRimed1]
1=
2=
3=
4=
5=
6=
7=
8=
9=

[CrystalLayerGrainDiameter1]
1=3
2=2
3=1
4=
5=1
6=1
7=
8=2
9=2

[CrystalLayerGrainForm2]
1=
2=
3=
4=
5=
6=
7=
8=3c
9=

[CrystalLayerGrainRimed2]
1=
2=
3=
4=
5=
6=
7=
8=
9=

[CrystalLayerGrainDiameter2]
1=
2=
3=
4=
5=
6=
7=
8=1.5
9=

[CrystalLayerHandHardness]
1=N/A
2=1F+
3=P
4=P+
5=1F
6=1F-
7=P+
8=4F
9=F

[CrystalLayerDensity]
1=0
2=300
3=290
4=0
5=200
6=170
7=260
8=140
9=0

[CrystalLayerDensityEstimated]
1=
2=
3=
4=
5=
6=
7=
8=
9=

[CrystalLayerComments]
1=
2=
3=
4=
5=
6=
7=
8=
9=

[CrystalLayerCommentsPosition]
1=1
2=1
3=1
4=1
5=1
6=1
7=1
8=1
9=1

[CrystalLayerCommentsSlope]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0
9=0

[ShearLayers]
Count=2

[ShearLayerHeight]
1=27
2=38

[ShearLayerType]
1=Compression
2=Compression

[ShearLayerValue]
1=H  - Hard
2=V  - Very Easy

[ShearHits]
1=2
2=0

[ShearLayerComments]
1=
2=Broke under crust on cut 2 x.

[ShearLayerCommentsPosition]
1=3
2=3
