[File]
Release=3.0

[Id]
Location=Bow Summit Weather Plot
Title1=Parks Canada
Title2=Banff-Yoho-Kootenay
Date=
Time=12:45
Observer=AH MH BW
Altitude=
AltUnits=
Coords=      ,
Aspect=8
Slope=0
ProfileNbr=1
ProfileType=Full

[Surface]
Roughness=
AirTemp=-16.5
PackHeight=61
LayerDown=0
PlotDown=0

[Penetration]
Ski=
Foot= 60

[Wind]
Speed=Light
Direction=North East

[Sky]
Condition=Scattered Clouds

[Ram]
Hardness=

[Precip]
Type=Nil
Rate=

[SnowTempLayers]
Count=6
SnowColour=16711680
SnowLine=16711680

[SnowHeight]
1=10
2=20
3=30
4=40
5=51
6=61

[SnowTemp]
1=-4.4
2=-6.3
3=-7.0
4=-9.2
5=-11.8
6=-16.5

[RamLayers]
RamColour=0
HardnessOnly=0
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1100
HandRamScale=0

[CrystalLayerHeight]
SymbolColour=16711680
1=-1
2=19
3=35
4=46
5=54
6=60
7=61

[Comments]
Count=1
1=Snowpack very weak, Shovels like sugar. Foot pen to ground.
Stability=N

[CrystalLLayers]
BottomOfPit=0
Count=7

[CrystalLayerWaterContent]
1=Dry
2=Dry
3=Dry
4=Dry
5=Dry
6=Dry
7=Dry

[CrystalLayerGrainForm1]
1=1
2=5
3=4
4=4
5=2
6=1
7=1

[CrystalLayerGrainRimed1]
1=
2=
3=
4=
5=
6=
7=

[CrystalLayerGrainDiameter1]
1=1
2=4-6
3=2
4=1.5
5=1
6=1.5
7=.5

[CrystalLayerGrainForm2]
1=
2=
3=5
4=
5=
6=
7=

[CrystalLayerGrainRimed2]
1=
2=
3=
4=
5=
6=
7=

[CrystalLayerGrainDiameter2]
1=
2=
3=4
4=
5=
6=
7=

[CrystalLayerHandHardness]
1=N/A
2=1F
3=1F-
4=F+
5=F
6=F
7=4F

[CrystalLayerDensity]
1=0
2=220
3=240
4=150
5=110
6=80
7=140

[CrystalLayerDensityEstimated]
1=
2=
3=
4=
5=
6=
7=e

[CrystalLayerComments]
1=
2=
3=
4=
5=
6=
7=Thin wind skin

[CrystalLayerCommentsPosition]
1=1
2=1
3=1
4=1
5=1
6=1
7=1

[CrystalLayerCommentsSlope]
1=0
2=0
3=0
4=0
5=0
6=0
7=0

[ShearLayers]
Count=2

[ShearLayerHeight]
1=19
2=46

[ShearLayerType]
1=Compression
2=Compression

[ShearLayerValue]
1=M  - Moderate
2=M  - Moderate

[ShearHits]
1=19
2=12

[ShearLayerComments]
1=Collapse in DH
2=Collapse/not clean

[ShearLayerCommentsPosition]
1=3
2=3
