[File]
Release=3.0

[Id]
Location=Bow Summit Study Plot
Title1=Parks Canada
Title2=Banff-Yoho-Kootenay
Date=
Time=13:00
Observer=MH
Altitude=
AltUnits=
Coords=      ,
Aspect=8
Slope=0
ProfileNbr=BS010315
ProfileType=Full

[Surface]
Roughness=Smooth
AirTemp=-3.4
PackHeight=69
LayerDown=0
PlotDown=0

[Penetration]
Ski= 40
Foot=  6

[Wind]
Speed=Light
Direction=South West

[Sky]
Condition=Clear

[Ram]
Hardness=

[Precip]
Type=Nil
Rate=

[SnowTempLayers]
Count=7
SnowColour=16711680
SnowLine=16711680

[SnowHeight]
1=0
2=10
3=20
4=30
5=40
6=50
7=60

[SnowTemp]
1=-1.8
2=-2.2
3=-2.4
4=-2.8
5=-3.7
6=-4.7
7=-3.9

[RamLayers]
RamColour=0
HardnessOnly=0
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1100
HandRamScale=0

[CrystalLayerHeight]
SymbolColour=16711680
1=-1
2=43
3=57
4=59
5=60
6=66
7=69

[Comments]
Count=2
1=Naturals on Bow Peak and Crowfoot. NE asp size 2.5. Wind effect at treeline and Alpine. All tests in plot failing
2=in DH.
Stability=U

[CrystalLLayers]
BottomOfPit=0
Count=7

[CrystalLayerWaterContent]
1=Dry
2=Dry
3=Dry
4=Dry
5=Dry
6=Dry
7=Dry

[CrystalLayerGrainForm1]
1=2
2=5
3=4
4=9e
5=
6=3
7=2

[CrystalLayerGrainRimed1]
1=
2=
3=
4=
5=
6=
7=

[CrystalLayerGrainDiameter1]
1=1
2=3 -5
3=1.5-2
4=
5=
6=.5
7=1

[CrystalLayerGrainForm2]
1=7
2=
3=
4=
5=
6=
7=4

[CrystalLayerGrainRimed2]
1=
2=
3=
4=
5=
6=
7=

[CrystalLayerGrainDiameter2]
1=
2=
3=
4=
5=
6=
7=1

[CrystalLayerHandHardness]
1=N/A
2=4F
3=1F
4=P
5=1F+
6=F
7=F

[CrystalLayerDensity]
1=0
2=250
3=210
4=260
5=260
6=140
7=130

[CrystalLayerDensityEstimated]
1=
2=
3=
4=e
5=e
6=
7=e

[CrystalLayerComments]
1=
2=
3=
4=
5=
6=
7=

[CrystalLayerCommentsPosition]
1=1
2=1
3=1
4=1
5=1
6=1
7=1

[CrystalLayerCommentsSlope]
1=0
2=0
3=0
4=0
5=0
6=0
7=0

[ShearLayers]
Count=1

[ShearLayerHeight]
1=43

[ShearLayerType]
1=Shovel

[ShearLayerValue]
1=M - Moderate

[ShearHits]
1=0

[ShearLayerComments]
1=All tests at 43

[ShearLayerCommentsPosition]
1=3
