[File]
Release=3.0

[Id]
Location=Bow Summit Weather Plot
Title1=Parks Canada
Title2=Banff-Yoho-Kootenay
Date=
Time=13:00
Observer=AH BW
Altitude=2030
AltUnits=
Coords=      ,
Aspect=8
Slope=0
ProfileNbr=01
ProfileType=Full

[Surface]
Roughness=Smooth
AirTemp=-2.4
PackHeight=62
LayerDown=0
PlotDown=0

[Penetration]
Ski=
Foot= 60

[Wind]
Speed=Light
Direction=West

[Sky]
Condition=Broken Clouds

[Ram]
Hardness=

[Precip]
Type=Nil
Rate=

[SnowTempLayers]
Count=6
SnowColour=16711680
SnowLine=16711680

[SnowHeight]
1=0
2=10
3=20
4=30
5=50
6=62

[SnowTemp]
1=-3.5
2=-4.7
3=-5.3
4=-6.0
5=-6.1
6=-5.4

[RamLayers]
RamColour=0
HardnessOnly=0
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1100
HandRamScale=0

[CrystalLayerHeight]
SymbolColour=16711680
1=-1
2=32
3=42
4=50
5=62

[Comments]
Count=1
1=No real shear or compression results as entire snowpack has very little cohesion. A dung pile of sugar.
Stability=N

[CrystalLLayers]
BottomOfPit=0
Count=5

[CrystalLayerWaterContent]
1=Dry
2=Dry
3=Dry
4=Dry
5=Dry

[CrystalLayerGrainForm1]
1=2
2=5
3=4
4=4
5=2

[CrystalLayerGrainRimed1]
1=
2=
3=
4=
5=

[CrystalLayerGrainDiameter1]
1=1.5
2=3-6
3=2
4=2-3
5=1

[CrystalLayerGrainForm2]
1=
2=
3=
4=
5=

[CrystalLayerGrainRimed2]
1=
2=
3=
4=
5=

[CrystalLayerGrainDiameter2]
1=
2=
3=
4=
5=

[CrystalLayerHandHardness]
1=N/A
2=1F
3=4F
4=4F
5=4F+

[CrystalLayerDensity]
1=0
2=240
3=230
4=210
5=110

[CrystalLayerDensityEstimated]
1=
2=
3=
4=
5=

[CrystalLayerComments]
1=
2=
3=
4=
5=

[CrystalLayerCommentsPosition]
1=1
2=1
3=1
4=1
5=1

[CrystalLayerCommentsSlope]
1=0
2=0
3=0
4=0
5=0
