[File]
Release=3.0

[Id]
Location=Bow Summit Weather Plot
Title1=Parks Canada
Title2=Banff-Yoho-Kootenay
Date=2001/03/28
Time=09:50
Observer=AH
Altitude=
AltUnits=
Coords=      ,
Aspect=8
Slope=0
ProfileNbr=BS010328
ProfileType=Full

[Surface]
Roughness=Smooth
AirTemp=0.0
PackHeight=75
LayerDown=0
PlotDown=0

[Penetration]
Ski=
Foot= 75

[Wind]
Speed=Light
Direction=North

[Sky]
Condition=Overcast

[Ram]
Hardness=

[Precip]
Type=Snow
Rate=Very Light

[SnowTempLayers]
Count=9
SnowColour=16711680
SnowLine=16711680

[SnowHeight]
1=0
2=10
3=20
4=30
5=40
6=50
7=60
8=65
9=75

[SnowTemp]
1=-1.3
2=-1.8
3=-2.2
4=-2.6
5=-3.4
6=-3.8
7=-4.5
8=-4.4
9=-3.3

[RamLayers]
RamColour=0
HardnessOnly=0
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1100
HandRamScale=0

[CrystalLayerHeight]
SymbolColour=16711680
1=-1
2=54
3=56
4=61
5=69
6=72
7=75

[CrystalLLayers]
BottomOfPit=0
Count=7

[CrystalLayerWaterContent]
1=Dry
2=Dry
3=Dry
4=Dry
5=Dry
6=Dry
7=Dry

[CrystalLayerGrainForm1]
1=2
2=5
3=4
4=4c
5=4
6=9e
7=1

[CrystalLayerGrainRimed1]
1=
2=
3=
4=
5=
6=
7=

[CrystalLayerGrainDiameter1]
1=2
2=2-4
3=1-1.5
4=.5
5=.5
6=1-1.5
7=2

[CrystalLayerGrainForm2]
1=
2=4
3=
4=
5=
6=
7=

[CrystalLayerGrainRimed2]
1=
2=
3=
4=
5=
6=
7=

[CrystalLayerGrainDiameter2]
1=
2=2-4
3=
4=
5=
6=
7=

[CrystalLayerHandHardness]
1=N/A
2=F
3=1F
4=4F
5=4F+
6=P
7=F

[CrystalLayerDensity]
1=0
2=190
3=250
4=240
5=200
6=240
7=70

[CrystalLayerDensityEstimated]
1=
2=
3=
4=
5=
6=
7=

[CrystalLayerComments]
1=
2=
3=
4=
5=
6=
7=

[CrystalLayerCommentsPosition]
1=1
2=1
3=1
4=1
5=1
6=1
7=1

[CrystalLayerCommentsSlope]
1=0
2=0
3=0
4=0
5=0
6=0
7=0

[Comments]
Stability=N

[ShearLayers]
Count=1

[ShearLayerHeight]
1=40

[ShearLayerType]
1=Compression

[ShearLayerValue]
1=M  - Moderate

[ShearHits]
1=15

[ShearLayerComments]
1= x 2

[ShearLayerCommentsPosition]
1=3
