[PopupMenu]
Showlayerslope=1
ShearHideAllComments=0
LayersHideAllComments=0
RamHideAllLayers=0
SnowTempHideAllLayers=0
ShearStress=1
HardnessType=0

[File]
Release=3.0

[Id]
Location=Bow Summit
Title1=Parks Canada
Title2=Banff/Yoho/Kootenay
Date=2002/03/28
Time=12:31
Observer=
Altitude=2060
AltUnits=Metres
Coords=      ,
Aspect=4
Slope=0
ProfileNbr=BS020328
ProfileType=Full

[Surface]
Roughness=Smooth
AirTemp=-2.0
PackHeight=150
LayerDown=0
PlotDown=0

[Penetration]
Ski=  6
Foot=

[Wind]
Speed=Calm
Direction=N/A

[Sky]
Condition=Broken Clouds

[Ram]
Hardness=

[Precip]
Type=Snow
Rate=Very Light

[SnowTempLayers]
MinTemperatureScale=-11
Count=16
SnowColour=16711680
SnowLine=16711680

[SnowHeight]
1=0
2=10
3=20
4=30
5=40
6=50
7=60
8=70
9=80
10=90
11=100
12=110
13=120
14=130
15=140
16=150

[SnowTemp]
1=-1.0
2=-1.0
3=-2.0
4=-3.0
5=-3.0
6=-4.0
7=-4.0
8=-5.0
9=-5.0
10=-4.0
11=-4.0
12=-4.0
13=-4.0
14=-4.0
15=-4.0
16=-4.0

[RamLayers]
RamColour=0
HardnessOnly=0
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1100
HandRamScale=0

[CrystalLayerHeight]
SymbolColour=16711680
1=-1
2=26
3=28
4=41
5=64
6=65
7=81
8=95
9=98
10=128
11=141
12=144
13=150

[CrystalLLayers]
BottomOfPit=0
Count=13

[CrystalLayerWaterContent]
1=Dry
2=Dry
3=Dry
4=Dry
5=Dry
6=Dry
7=Dry
8=Dry
9=Dry
10=Dry
11=Dry
12=Dry
13=Dry

[CrystalLayerGrainForm1]
1=
2=4
3=4c
4=4c
5=4c
6=4c
7=3
8=3
9=3
10=3
11=3
12=9e
13=1

[CrystalLayerGrainRimed1]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=

[CrystalLayerGrainDiameter1]
1=
2=2-4
3=3
4=2-3
5=2
6=6
7=2
8=1
9=1.5
10=.5
11=.5
12=.5
13=1

[CrystalLayerGrainForm2]
1=
2=4
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=2

[CrystalLayerGrainRimed2]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=

[CrystalLayerGrainDiameter2]
1=
2=2-4
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=1

[CrystalLayerHandHardness]
1=N/A
2=1F+
3=N/A
4=4F-
5=4F
6=1F-
7=1F
8=P
9=1F
10=1F
11=1F
12=K
13=F

[CrystalLayerDensity]
1=0
2=390
3=0
4=310
5=305
6=0
7=310
8=320
9=300
10=290
11=180
12=310
13=100

[CrystalLayerDensityEstimated]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=

[CrystalLayerComments]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=

[CrystalLayerCommentsPosition]
1=1
2=1
3=1
4=1
5=1
6=1
7=1
8=1
9=1
10=1
11=1
12=1
13=1

[CrystalLayerCommentsSlope]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0
9=0
10=0
11=0
12=0
13=0

[Comments]
Stability=N

[ShearLayers]
Count=3

[ShearLayerHeight]
1=28
2=128
3=141

[ShearLayerType]
1=Compression
2=Compression
3=Compression

[ShearLayerValue]
1=H  - Hard
2=H  - Hard
3=M  - Moderate

[ShearHits]
1=25
2=22
3=11

[ShearLayerComments]
1= MF sz 2-3
2=rounds sz .5
3=rounds sz .5 bottom of cr

[ShearLayerCommentsPosition]
1=3
2=3
3=3
