[PopupMenu]
Showlayerslope=0
ShearHideAllComments=0
LayersHideAllComments=0
RamHideAllLayers=0
SnowTempHideAllLayers=0
ShearStress=1
HardnessType=0

[File]
Release=3.0

[Id]
Location=Vermilion
Title1=Parks Canada
Title2=Banff-Yoho-Kootenay
Date=12/18/2001
Time=00:00
Observer=Bw, ML
Altitude=2100
AltUnits=Metres
Coords=      ,
Aspect=8
Slope=0
ProfileNbr=VE2
ProfileType=Full

[Surface]
Roughness=
AirTemp=-13.0
PackHeight=133
LayerDown=0
PlotDown=0

[Penetration]
Ski=
Foot=

[Wind]
Speed=
Direction=N/A

[Sky]
Condition=Broken Clouds

[Ram]
Hardness=

[Precip]
Type=Nil
Rate=

[SnowTempLayers]
MinTemperatureScale=-11
Count=15
SnowColour=16711680
SnowLine=16711680

[SnowHeight]
1=0
2=10
3=20
4=30
5=40
6=50
7=60
8=70
9=80
10=90
11=100
12=110
13=120
14=123
15=133

[SnowTemp]
1=-0.9
2=-1.5
3=-2.0
4=-2.9
5=-3.3
6=-3.6
7=-4.4
8=-5.2
9=-6.0
10=-6.6
11=-7.6
12=-8.5
13=-11.6
14=-14.1
15=-16.2

[RamLayers]
RamColour=16711680
HardnessOnly=0
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1100
HandRamScale=0

[CrystalLayerHeight]
SymbolColour=16711680
1=-1
2=38
3=40
4=50
5=58
6=71
7=76
8=89
9=91
10=98
11=104
12=116
13=133

[Comments]
Count=1
1=Note 1: Variable pencil to knife.  Rain percolation through layer.
Stability=N

[CrystalLLayers]
BottomOfPit=0
Count=13

[CrystalLayerWaterContent]
1=Dry
2=Dry
3=Dry
4=Dry
5=Dry
6=Dry
7=Dry
8=Dry
9=Dry
10=Dry
11=Dry
12=Dry
13=Dry

[CrystalLayerGrainForm1]
1=1
2=3
3=9
4=4c
5=9
6=4
7=3
8=3
9=3
10=3
11=2
12=3
13=2

[CrystalLayerGrainRimed1]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=

[CrystalLayerGrainDiameter1]
1=1-3
2=1
3=
4=
5=
6=1
7=.5
8=1
9=.5
10=1
11=1.5
12=.5
13=1

[CrystalLayerGrainForm2]
1=1f
2=
3=
4=
5=
6=
7=
8=
9=
10=2
11=
12=
13=

[CrystalLayerGrainRimed2]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=

[CrystalLayerGrainDiameter2]
1=1-3
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=

[CrystalLayerHandHardness]
1=N/A
2=P
3=P+
4=P
5=K
6=1F
7=P
8=P
9=P-
10=P
11=1F+
12=1F
13=4F+

[CrystalLayerDensity]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0
9=0
10=0
11=0
12=0
13=0

[CrystalLayerDensityEstimated]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=

[CrystalLayerComments]
1=
2=
3=
4=See note 1
5=
6=
7=
8=
9=
10=
11=
12=
13=

[CrystalLayerCommentsPosition]
1=1
2=1
3=1
4=1
5=1
6=1
7=1
8=1
9=1
10=1
11=1
12=1
13=1

[CrystalLayerCommentsSlope]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0
9=0
10=0
11=0
12=0
13=0

[ShearLayers]
Count=4

[ShearLayerHeight]
1=58
2=71
3=98
4=116

[ShearLayerType]
1=Compression
2=Compression
3=Compression
4=Compression

[ShearLayerValue]
1=M  - Moderate
2=M  - Moderate
3=E  - Easy
4=E  - Easy

[ShearHits]
1=14
2=14
3=7
4=7

[ShearLayerComments]
1=
2=
3=
4=

[ShearLayerCommentsPosition]
1=3
2=3
3=3
4=3
