[PopupMenu]
Showlayerslope=0
ShearHideAllComments=0
LayersHideAllComments=0
RamHideAllLayers=0
SnowTempHideAllLayers=0
ShearStress=1
HardnessType=0

[File]
Release=3.0

[Id]
Location=Vermilion
Title1=Parks Canada
Title2=Banff-Yoho-Kootenay
Date=11/27/2001
Time=11:16
Observer=ML
Altitude=2100
AltUnits=Metres
Coords=      ,
Aspect=8
Slope=0
ProfileNbr=VE1
ProfileType=Full

[Surface]
Roughness=
AirTemp=-9.5
PackHeight=101
LayerDown=0
PlotDown=0

[Penetration]
Ski=
Foot= 25

[Wind]
Speed=Calm
Direction=N/A

[Sky]
Condition=Overcast

[Ram]
Hardness=

[Precip]
Type=Snow
Rate=Very Light

[SnowTempLayers]
MinTemperatureScale=-11
Count=10
SnowColour=16711680
SnowLine=16711680

[SnowHeight]
1=0
2=10
3=20
4=30
5=40
6=50
7=60
8=70
9=80
10=90

[SnowTemp]
1=0.0
2=-1.0
3=-1.2
4=-1.7
5=-2.6
6=-3.5
7=-4.3
8=-5.7
9=-6.7
10=-6.0

[RamLayers]
RamColour=0
HardnessOnly=0
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1100
HandRamScale=0

[CrystalLayerHeight]
SymbolColour=16711680
1=-1
2=10
3=48
4=64
5=70
6=73
7=93
8=101

[CrystalLLayers]
BottomOfPit=0
Count=8

[CrystalLayerWaterContent]
1=Dry
2=Dry
3=Dry
4=Dry
5=Dry
6=Dry
7=Dry
8=Dry

[CrystalLayerGrainForm1]
1=1
2=4
3=4
4=4
5=9
6=4
7=2
8=1

[CrystalLayerGrainRimed1]
1=
2=
3=
4=
5=
6=
7=
8=

[CrystalLayerGrainDiameter1]
1=2-3
2=2
3=.5
4=
5=1
6=1
7=1
8=2-3

[CrystalLayerGrainForm2]
1=
2=
3=
4=
5=
6=
7=
8=

[CrystalLayerGrainRimed2]
1=
2=
3=
4=
5=
6=
7=
8=

[CrystalLayerGrainDiameter2]
1=
2=
3=
4=
5=
6=
7=
8=

[CrystalLayerHandHardness]
1=N/A
2=P
3=P
4=1F
5=K
6=4F+
7=4F
8=F

[CrystalLayerDensity]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0

[CrystalLayerDensityEstimated]
1=
2=
3=
4=
5=
6=
7=
8=

[CrystalLayerComments]
1=
2=
3=
4=Thin ice crust @ 48
5=
6=
7=
8=

[CrystalLayerCommentsPosition]
1=1
2=1
3=1
4=2
5=1
6=1
7=1
8=1

[CrystalLayerCommentsSlope]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0

[Comments]
Stability=N

[ShearLayers]
Count=2

[ShearLayerHeight]
1=64
2=70

[ShearLayerType]
1=Compression
2=Shovel

[ShearLayerValue]
1=H  - Hard
2=M - Moderate

[ShearHits]
1=6
2=0

[ShearLayerComments]
1=
2=

[ShearLayerCommentsPosition]
1=3
2=3
