[File]
Release=3.0

[Id]
Location=Vermillion Lower Weather Plot
Title1=Parks Canada
Title2=Banff/Yoho/Kootenay
Date=
Time=
Observer=BW AH
Altitude=
AltUnits=
Coords=      ,
Aspect=2
Slope=0
ProfileNbr=01
ProfileType=Full

[Surface]
Roughness=Smooth
AirTemp=-9.0
PackHeight=100
LayerDown=0
PlotDown=0

[Penetration]
Ski= 25
Foot= 85

[Wind]
Speed=Light
Direction=West

[Sky]
Condition=Scattered Clouds

[Ram]
Hardness=

[Precip]
Type=Nil
Rate=

[SnowTempLayers]
Count=11
SnowColour=16711680
SnowLine=16711680

[SnowHeight]
1=0
2=10
3=20
4=30
5=40
6=50
7=60
8=70
9=80
10=90
11=100

[SnowTemp]
1=-1.1
2=-2.0
3=-2.9
4=-4.1
5=-5.0
6=-6.3
7=-7.4
8=-8.7
9=-9.9
10=-12.0
11=-8.0

[RamLayers]
RamColour=0
HardnessOnly=0
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1100
HandRamScale=0

[CrystalLayerHeight]
SymbolColour=16711680
1=-1
2=11
3=39
4=55
5=62
6=69
7=91
8=100

[Comments]
Count=2
1=Snowpack reasonably strong. No shear or evidence of SH at Jan 7 interface. Major layor of concern poor bond between
2=storm snow and old facets. Base still weak DH but improving.
Stability=N

[CrystalLLayers]
BottomOfPit=0
Count=8

[CrystalLayerWaterContent]
1=Dry
2=Dry
3=Dry
4=Dry
5=Dry
6=Dry
7=Dry
8=Dry

[CrystalLayerGrainForm1]
1=
2=9
3=5b
4=4
5=4c
6=4
7=2
8=1

[CrystalLayerGrainRimed1]
1=
2=
3=
4=
5=
6=
7=
8=

[CrystalLayerGrainDiameter1]
1=
2=
3=6
4=2
5=1.5
6=1-1.5
7=1
8=1.5

[CrystalLayerGrainForm2]
1=
2=5a
3=
4=
5=
6=
7=
8=

[CrystalLayerGrainRimed2]
1=
2=
3=
4=
5=
6=
7=
8=

[CrystalLayerGrainDiameter2]
1=
2=
3=
4=
5=
6=
7=
8=

[CrystalLayerHandHardness]
1=N/A
2=P+
3=1F-
4=1F+
5=1F
6=4F+
7=1F-
8=F

[CrystalLayerDensity]
1=0
2=290
3=250
4=260
5=240
6=200
7=180
8=70

[CrystalLayerDensityEstimated]
1=
2=
3=
4=
5=
6=
7=
8=

[CrystalLayerComments]
1=
2=
3=
4=Jan 7@55 No SH visible
5=
6=
7=
8=

[CrystalLayerCommentsPosition]
1=1
2=1
3=2
4=1
5=1
6=2
7=1
8=1

[CrystalLayerCommentsSlope]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0

[ShearLayers]
Count=2

[ShearLayerHeight]
1=25
2=69

[ShearLayerType]
1=Compression
2=Compression

[ShearLayerValue]
1=M  - Moderate
2=M  - Moderate

[ShearHits]
1=16
2=11

[ShearLayerComments]
1=X2 collapse in large DH
2=X2

[ShearLayerCommentsPosition]
1=3
2=3
