[File]
Release=3.0

[Id]
Location=Vermillion Lower
Title1=Parks Canada
Title2=Banff-Yoho-Kootenay
Date=2001/04/11
Time=14:30
Observer=TM GHI AH
Altitude=
AltUnits=
Coords=,
Aspect=8
Slope=0
ProfileNbr=VE010411
ProfileType=Test

[Surface]
Roughness=Smooth
AirTemp=-1.5
PackHeight=143
LayerDown=0
PlotDown=0

[Penetration]
Ski=10
Foot=25

[Wind]
Speed=Light
Direction=North

[Sky]
Condition=Scattered Clouds

[Ram]
Hardness=

[Precip]
Type=Nil
Rate=

[SnowTempLayers]
Count=16
SnowColour=16711680
SnowLine=16711680

[SnowHeight]
1=0
2=10
3=20
4=30
5=40
6=50
7=60
8=70
9=80
10=90
11=100
12=110
13=120
14=130
15=133
16=143

[SnowTemp]
1=0.0
2=-0.2
3=-0.4
4=-0.7
5=-0.9
6=-1.2
7=-1.4
8=-1.6
9=-1.9
10=-2.2
11=-2.6
12=-3.4
13=-4.6
14=-4.2
15=-3.3
16=-0.9

[RamLayers]
RamColour=0
HardnessOnly=0
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1100
HandRamScale=0

[CrystalLayerHeight]
SymbolColour=16711680
1=-1
2=36
3=69
4=92
5=106
6=107
7=121
8=131
9=134
10=143

[CrystalLLayers]
BottomOfPit=0
Count=10

[CrystalLayerWaterContent]
1=Dry
2=Dry
3=Dry
4=Dry
5=Dry
6=Dry
7=Dry
8=Dry
9=Dry
10=Dry

[CrystalLayerGrainForm1]
1=
2=5
3=5
4=4
5=4
6=9e
7=4
8=4
9=6
10=2

[CrystalLayerGrainRimed1]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=

[CrystalLayerGrainDiameter1]
1=
2=4
3=3
4=2
5=2.5
6=
7=1
8=1
9=1.5
10=2

[CrystalLayerGrainForm2]
1=
2=
3=
4=
5=
6=4
7=
8=
9=
10=

[CrystalLayerGrainRimed2]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=

[CrystalLayerGrainDiameter2]
1=
2=
3=
4=
5=
6=4-6
7=
8=
9=
10=

[CrystalLayerHandHardness]
1=N/A
2=4F
3=1F
4=P
5=P
6=P+
7=1F
8=4F
9=1F+
10=F

[CrystalLayerDensity]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0
9=0
10=0

[CrystalLayerDensityEstimated]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=

[CrystalLayerComments]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=

[CrystalLayerCommentsPosition]
1=1
2=1
3=1
4=1
5=1
6=1
7=1
8=1
9=1
10=1

[CrystalLayerCommentsSlope]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0
9=0
10=0

[Comments]
Stability=N

[ShearLayers]
Count=6

[ShearLayerHeight]
1=55
2=84
3=92
4=107
5=112
6=121

[ShearLayerType]
1=Compression
2=Compression
3=Shovel
4=Shovel
5=Compression
6=Compression

[ShearLayerValue]
1=H  - Hard
2=H  - Hard
3=E - Easy
4=E - Easy
5=M  - Moderate
6=M  - Moderate

[ShearHits]
1=28
2=25
3=0
4=0
5=15
6=12

[ShearLayerComments]
1= @55
2= @84
3= mostly facets, some real flat
4= @ crust
5= @112
6= @121

[ShearLayerCommentsPosition]
1=3
2=3
3=3
4=3
5=3
6=3
