[PopupMenu]
Showlayerslope=0
ShearHideAllComments=0
LayersHideAllComments=0
RamHideAllLayers=0
SnowTempHideAllLayers=0
ShearStress=0
HardnessType=0

[File]
Release=3.0

[Id]
Location=Vermillion
Title1=Parks Canada
Title2=Banff-Yoho-Kootenay
Date=1/16/2002
Time=12:30
Observer=AH CA
Altitude=2100
AltUnits=Metres
Coords=      ,
Aspect=2
Slope=0
ProfileNbr=VE020116
ProfileType=Full

[Surface]
Roughness=Smooth
AirTemp=-13.5
PackHeight=154
LayerDown=0
PlotDown=0

[Penetration]
Ski= 10
Foot= 20

[Wind]
Speed=Light
Direction=South West

[Sky]
Condition=Overcast

[Ram]
Hardness=

[Precip]
Type=Snow
Rate=Very Light

[SnowTempLayers]
MinTemperatureScale=-22
Count=16
SnowColour=16711680
SnowLine=16711680

[SnowHeight]
1=0
2=20
3=30
4=40
5=50
6=60
7=70
8=80
9=90
10=100
11=110
12=120
13=130
14=140
15=144
16=154

[SnowTemp]
1=-0.7
2=-0.3
3=-1.5
4=-2.0
5=-2.1
6=-2.9
7=-3.4
8=-4.2
9=-4.8
10=-5.8
11=-7.1
12=-9.2
13=-11.8
14=-14.0
15=-14.3
16=-12.1

[RamLayers]
RamColour=16711680
HardnessOnly=0
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1100
HandRamScale=0

[CrystalLayerHeight]
SymbolColour=16711680
1=-1
2=32
3=41
4=42
5=53
6=56
7=74
8=80
9=84
10=107
11=110
12=115
13=123
14=135
15=154

[CrystalLLayers]
BottomOfPit=0
Count=15

[CrystalLayerWaterContent]
1=Dry
2=Dry
3=Dry
4=Dry
5=Dry
6=Dry
7=Dry
8=Dry
9=Dry
10=Dry
11=Dry
12=Dry
13=Dry
14=Dry
15=Dry

[CrystalLayerGrainForm1]
1=7
2=4
3=9
4=4
5=9
6=7
7=4
8=4
9=4
10=4
11=7
12=4
13=4c
14=4c
15=4c

[CrystalLayerGrainRimed1]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=
14=
15=

[CrystalLayerGrainDiameter1]
1=2-6
2=1-3
3=
4=1-2
5=
6=2-3
7=1-2
8=1
9=.5-1
10=1-2
11=1-6
12=.5-1
13=.5
14=.5-4
15=.5

[CrystalLayerGrainForm2]
1=2
2=
3=
4=
5=
6=4
7=
8=
9=
10=
11=
12=
13=
14=
15=

[CrystalLayerGrainRimed2]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=
14=
15=

[CrystalLayerGrainDiameter2]
1=2
2=
3=
4=
5=
6=2-3
7=
8=
9=
10=
11=
12=
13=
14=
15=

[CrystalLayerHandHardness]
1=N/A
2=1F
3=P
4=P-
5=P
6=4F
7=1F
8=1F
9=1F+
10=1F
11=4F
12=1F
13=1F
14=4F
15=F

[CrystalLayerDensity]
1=0
2=290
3=320
4=370
5=410
6=350
7=280
8=290
9=320
10=280
11=170
12=210
13=240
14=190
15=150

[CrystalLayerDensityEstimated]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=
14=
15=

[CrystalLayerComments]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=
14=
15=

[CrystalLayerCommentsPosition]
1=1
2=1
3=1
4=1
5=1
6=1
7=1
8=1
9=1
10=1
11=1
12=1
13=1
14=1
15=1

[CrystalLayerCommentsSlope]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0
9=0
10=0
11=0
12=0
13=0
14=0
15=0

[Comments]
Stability=N

[ShearLayers]
Count=2

[ShearLayerHeight]
1=53
2=110

[ShearLayerType]
1=Compression
2=Compression

[ShearLayerValue]
1=H  - Hard
2=H  - Hard

[ShearHits]
1=24
2=22

[ShearLayerComments]
1=x 2
2=x 2

[ShearLayerCommentsPosition]
1=3
2=3
