[PopupMenu]
Showlayerslope=0
ShearHideAllComments=0
LayersHideAllComments=0
RamHideAllLayers=0
SnowTempHideAllLayers=0
ShearStress=0
HardnessType=0

[File]
Release=3.0

[Id]
Location=Vermillion
Title1=Parks Canada
Title2=Banff-Yoho-Kootenay
Date=2002/01/31
Time=14:12
Observer=AH PW BW
Altitude=2100
AltUnits=Metres
Coords=      ,
Aspect=4
Slope=0
ProfileNbr=VE020131
ProfileType=Full

[Surface]
Roughness=Smooth
AirTemp=-7.0
PackHeight=209
LayerDown=0
PlotDown=0

[Penetration]
Ski=
Foot= 40

[Wind]
Speed=Light
Direction=South

[Sky]
Condition=Overcast

[Ram]
Hardness=

[Precip]
Type=Snow
Rate=Very Light

[SnowTempLayers]
MinTemperatureScale=-22
Count=16
SnowColour=16711680
SnowLine=16711680

[SnowHeight]
1=0
2=20
3=40
4=60
5=80
6=100
7=110
8=120
9=130
10=140
11=150
12=160
13=170
14=180
15=190
16=199

[SnowTemp]
1=-0.3
2=-1.8
3=-2.3
4=-3.1
5=-4.4
6=-5.7
7=-6.4
8=-7.2
9=-8.0
10=-8.8
11=-9.7
12=-11.5
13=-12.7
14=-13.1
15=-13.2
16=-8.7

[RamLayers]
RamColour=0
HardnessOnly=0
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1100
HandRamScale=0

[CrystalLayerHeight]
SymbolColour=16711680
1=-1
2=36
3=49
4=55
5=60
6=70
7=76
8=108
9=110
10=124
11=126
12=147
13=150
14=170
15=202
16=209

[CrystalLLayers]
BottomOfPit=0
Count=16

[CrystalLayerWaterContent]
1=Dry
2=Dry
3=Dry
4=Dry
5=Dry
6=Dry
7=Dry
8=Dry
9=Dry
10=Dry
11=Dry
12=Dry
13=Dry
14=Dry
15=Dry
16=Dry

[CrystalLayerGrainForm1]
1=1
2=4
3=4
4=9
5=4
6=4
7=4
8=4
9=7
10=4
11=4
12=4
13=3
14=3c
15=2
16=1

[CrystalLayerGrainRimed1]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=
14=
15=
16=

[CrystalLayerGrainDiameter1]
1=2
2=2
3=2
4=
5=3
6=2
7=1.5
8=1
9=8-12
10=1
11=.5-1
12=1
13=.5
14=.5
15=.5-1
16=2

[CrystalLayerGrainForm2]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=4c
13=
14=2
15=4
16=

[CrystalLayerGrainRimed2]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=
14=
15=
16=

[CrystalLayerGrainDiameter2]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=1
13=
14=.5
15=.5-1
16=

[CrystalLayerHandHardness]
1=N/A
2=P
3=1F
4=P+
5=4F
6=4F
7=1F+
8=1F
9=1F-
10=1F+
11=1F-
12=1F
13=P
14=1F
15=4F
16=F

[CrystalLayerDensity]
1=0
2=370
3=360
4=350
5=410
6=280
7=310
8=300
9=0
10=290
11=0
12=260
13=170
14=220
15=170
16=50

[CrystalLayerDensityEstimated]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=
14=
15=
16=

[CrystalLayerComments]
1=
2=
3=
4=
5=
6=
7=
8=
9=Clean Shear
10=
11=
12=
13=
14=
15=
16=

[CrystalLayerCommentsPosition]
1=1
2=1
3=1
4=1
5=1
6=1
7=1
8=1
9=1
10=1
11=1
12=1
13=1
14=1
15=1
16=1

[CrystalLayerCommentsSlope]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0
9=0
10=0
11=0
12=0
13=0
14=0
15=0
16=0

[Comments]
Stability=N

[ShearLayers]
Count=2

[ShearLayerHeight]
1=55
2=186

[ShearLayerType]
1=Compression
2=Compression

[ShearLayerValue]
1=H  - Hard
2=M  - Moderate

[ShearHits]
1=20
2=10

[ShearLayerComments]
1=X 2, Clean Shear
2=X 2

[ShearLayerCommentsPosition]
1=3
2=3
