[PopupMenu]
Showlayerslope=1
ShearHideAllComments=0
LayersHideAllComments=0
RamHideAllLayers=0
SnowTempHideAllLayers=0
ShearStress=1
HardnessType=0

[File]
Release=3.0

[Id]
Location=Vermillion Plot
Title1=Parks Canada
Title2=Banff/Yoho/Kootenay
Date=2002/03/29
Time=13:00
Observer=MH, JM,PW
Altitude=2100
AltUnits=Metres
Coords=      ,
Aspect=8
Slope=0
ProfileNbr=V020329
ProfileType=Full

[Surface]
Roughness=Smooth
AirTemp=-1.5
PackHeight=253
LayerDown=0
PlotDown=0

[Penetration]
Ski=
Foot=

[Wind]
Speed=Light
Direction=South West

[Sky]
Condition=Overcast

[Ram]
Hardness=

[Precip]
Type=Snow
Rate=Very Light

[SnowTempLayers]
MinTemperatureScale=-11
Count=13
SnowColour=16711680
SnowLine=16711680

[SnowHeight]
1=140
2=150
3=160
4=170
5=180
6=190
7=200
8=210
9=220
10=230
11=240
12=243
13=253

[SnowTemp]
1=-4.1
2=-4.3
3=-4.6
4=-4.7
5=-4.9
6=-5.1
7=-5.3
8=-5.3
9=-5.3
10=-5.2
11=-3.9
12=-2.6
13=-1.5

[RamLayers]
RamColour=0
HardnessOnly=0
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1100
HandRamScale=0

[CrystalLayerHeight]
SymbolColour=16711680
1=-1
2=122
3=147
4=161
5=162
6=172
7=194
8=206
9=224
10=235
11=237
12=243
13=253

[CrystalLLayers]
BottomOfPit=0
Count=13

[CrystalLayerWaterContent]
1=Dry
2=Dry
3=Dry
4=Dry
5=Dry
6=Dry
7=Dry
8=Dry
9=Dry
10=Dry
11=Dry
12=Dry
13=Dry

[CrystalLayerGrainForm1]
1=
2=4c
3=4c
4=4c
5=7
6=3
7=3
8=3
9=3
10=4
11=9
12=3
13=2

[CrystalLayerGrainRimed1]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=

[CrystalLayerGrainDiameter1]
1=
2=1-1.5
3=1
4=.5
5=2
6=.5
7=.5
8=.25-.5
9=.5-1
10=.25
11=
12=.25
13=1

[CrystalLayerGrainForm2]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=

[CrystalLayerGrainRimed2]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=

[CrystalLayerGrainDiameter2]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=

[CrystalLayerHandHardness]
1=N/A
2=P
3=P+
4=P
5=N/A
6=P
7=P-
8=P
9=1F+
10=1F
11=K
12=4F
13=F

[CrystalLayerDensity]
1=0
2=0
3=0
4=0
5=0
6=350
7=260
8=280
9=240
10=200
11=0
12=150
13=60

[CrystalLayerDensityEstimated]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=

[CrystalLayerComments]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=

[CrystalLayerCommentsPosition]
1=1
2=1
3=1
4=1
5=1
6=1
7=1
8=1
9=1
10=1
11=1
12=1
13=1

[CrystalLayerCommentsSlope]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0
9=0
10=0
11=0
12=0
13=0

[Comments]
Stability=N

[ShearLayers]
Count=1

[ShearLayerHeight]
1=224

[ShearLayerType]
1=Compression

[ShearLayerValue]
1=H  - Hard

[ShearHits]
1=24

[ShearLayerComments]
1=@227 on 1F rounds

[ShearLayerCommentsPosition]
1=3
