[PopupMenu]
Showlayerslope=0
ShearHideAllComments=0
LayersHideAllComments=0
RamHideAllLayers=0
SnowTempHideAllLayers=0
ShearStress=1
HardnessType=0
[File]
Release=3.0
[Id]
Location=Vermilion Study Plot
Title1=Parks Canada
Title2=Banff-Yoho-Kootenay
Date=
Time=12:00
Observer=SM GI
Altitude=2273
AltUnits=Metres
Coords=      ,       
Aspect=8
Slope=0
ProfileNbr=5
ProfileType=Full
[Surface]
Roughness=Smooth
AirTemp=-9.2 
PackHeight=176
LayerDown=0
PlotDown=0
[Penetration]
Ski= 25
Foot= 50
[Wind]
Speed=Light
Direction=North
[Sky]
Condition=Overcast
[Ram]
Hardness=
[Precip]
Type=Snow
Rate=Light
[SnowTempLayers]
MinTemperatureScale=-88
Count=15
SnowColour=16711680
SnowLine=16711680
[SnowHeight]
1=0
2=10
3=20
4=30
5=40
6=50
7=60
8=70
9=80
10=90
11=100
12=110
13=120
14=130
15=140
[SnowTemp]
1=-0.4
2=-1.2
3=-1.7
4=-2.6
5=-3.2
6=-4.0
7=-4.7
8=-5.3
9=-6.1
10=-6.8
11=-7.6
12=-8.2
13=-8.9
14=-9.4
15=-9.6
[RamLayers]
RamColour=16777215
HardnessOnly=0
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1375
HandRamScale=0
[CrystalLayerHeight]
SymbolColour=16777215
[Comments]
Count=6
1=ADFAR PROJECT WINTER 2005-2006
2=
3=UTM NS 0571291 5648649 Map: Mount Assiniboine 82J/13
4=
5=Pre Assessment:
6=Post Assessment:
Stability=N
[CrystalLLayers]
BottomOfPit=0
