[PopupMenu]
Showlayerslope=0
ShearHideAllComments=0
LayersHideAllComments=0
RamHideAllLayers=0
SnowTempHideAllLayers=0
ShearStress=1
HardnessType=0
[File]
Release=3.0
[Id]
Location=Vermillion Study Plot
Title1=Parks Canada
Title2=Banff-Yoho-Kootenay
Date=
Time=10:50
Observer=SM
Altitude=2273
AltUnits=Metres
Coords=      ,       
Aspect=8
Slope=0
ProfileNbr=2
ProfileType=Full
[Surface]
Roughness=Smooth
AirTemp=-6.5 
PackHeight=150
LayerDown=0
PlotDown=0
[Penetration]
Ski= 20
Foot= 80
[Wind]
Speed=Calm
Direction=N/A
[Sky]
Condition=Obscure
[Ram]
Hardness=
[Precip]
Type=Snow
Rate=Light
[SnowTempLayers]
MinTemperatureScale=-11
Count=16
SnowColour=16711680
SnowLine=16711680
[SnowHeight]
1=0
2=10
3=20
4=30
5=40
6=50
7=60
8=70
9=80
10=90
11=100
12=110
13=120
14=130
15=140
16=150
[SnowTemp]
1=-0.4
2=-0.9
3=-1.2
4=-1.4
5=-1.8
6=-2.2
7=-2.5
8=-3.2
9=-3.6
10=-4.0
11=-4.6
12=-5.1
13=-5.9
14=-6.8
15=-7.4
16=-7.2
[RamLayers]
RamColour=16711680
HardnessOnly=0
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1100
HandRamScale=0
[CrystalLayerHeight]
SymbolColour=16711680
1=-1
2=21
3=35
4=64
5=76
6=89
7=106
8=124
9=133
10=150
[Comments]
Count=16
1=ADFAR PROJECT WINTER 2005-2006
2=
3=UTM: NS 571700 5648200  Map: Mount Assiniboine  NAD83
4=Site Description: Flat open glade surrounded by spruce, larch and pine trees
5=
6=Danger rating pre assessment: TL high, BTL considerable
7=Danger rating post assessment: no change
8=
9=CTE2 @ 133cm SC
10=CTE6/9 @ 124cm RP
11=CTM12 @ 106cm
12=CTM16/17 @ 64cm SP
13=
14=CTE 2,2 PC @
15=CTE 6,9 SP @         on size 2 stellars
16=CTM 16, 17 SP @ 64cm
Stability=N
[CrystalLLayers]
BottomOfPit=0
Count=10
[CrystalLayerWaterContent]
1=Dry
2=Dry
3=Dry
4=Dry
5=Dry
6=Dry
7=Dry
8=Dry
9=Dry
10=Dry
[CrystalLayerGrainForm1]
1=1
2=4
3=5
4=4
5=4c
6=3
7=2
8=2
9=1
10=1
[CrystalLayerGrainRimed1]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
[CrystalLayerGrainDiameter1]
1=2
2=3
3=3
4=2
5=1.5
6=1
7=1-1.5
8=1.5
9=1
10=1.5
[CrystalLayerGrainForm2]
1=
2=
3=
4=
5=
6=
7=
8=
9=2
10=1f
[CrystalLayerGrainRimed2]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
[CrystalLayerGrainDiameter2]
1=
2=
3=
4=
5=
6=
7=
8=
9=1
10=2
[CrystalLayerHandHardness]
1=N/A
2=P
3=1F+
4=4F
5=1F-
6=1F+
7=1F
8=1F-
9=4F
10=F
[CrystalLayerDensity]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0
9=0
10=0
[CrystalLayerDensityEstimated]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
[CrystalLayerComments]
1=
2=Conglomerated facets
3=Remnant crust @ 21
4=Remnant crust @ 35
5=
6=
7=Thin crust @ 89
8=
9=
10=
[CrystalLayerCommentsPosition]
1=1
2=1
3=2
4=2
5=1
6=1
7=2
8=1
9=1
10=1
[CrystalLayerCommentsSlope]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0
9=0
10=0
[ShearLayers]
Count=6
[ShearLayerHeight]
1=64
2=64
3=106
4=124
5=124
6=133
[ShearLayerType]
1=Compression
2=Compression
3=Compression
4=Compression
5=Compression
6=Compression
[ShearLayerValue]
1=M  - Moderate
2=M  - Moderate
3=M  - Moderate
4=E  - Easy
5=E  - Easy
6=E  - Easy
[ShearHits]
1=16
2=17
3=12
4=6
5=9
6=2
[ShearLayerComments]
1=Sudden planar
2=and CTM 16 (SP)
3=
4=Sudden planar
5=and CTE 6 (SP) on size 2 stellars
6=(PC) x 2
[ShearLayerCommentsPosition]
1=7
2=3
3=3
4=7
5=3
6=3
