[PopupMenu]
Showlayerslope=0
ShearHideAllComments=0
LayersHideAllComments=0
RamHideAllLayers=0
SnowTempHideAllLayers=0
ShearStress=0
HardnessType=0
[File]
Release=3.0
[Id]
Location=Takakkaw Study Plot
Title1=Banff Yoho Kootenay
Title2=National Parks
Date=2003-12-30
Time=11:45
Observer=GHI, TA, RB, KS
Altitude=1800
AltUnits=Metres
Coords=      ,       
Aspect=8
Slope=0
ProfileNbr=3
ProfileType=Full
[Surface]
Roughness=Smooth
AirTemp=-17.1
PackHeight=103
LayerDown=0
PlotDown=0
[Penetration]
Ski= 17
Foot=   
[Wind]
Speed=Extreme
Direction=N/A
[Sky]
Condition=Broken Clouds
[Ram]
Hardness=
[Precip]
Type=Snow
Rate=Very Light
[SnowTempLayers]
MinTemperatureScale=-22
Count=12
[SnowHeight]
1=0
2=10
3=20
4=30
5=40
6=50
7=60
8=70
[SnowTemp]
1=0.0
2=-0.9
3=-1.5
4=-2.2
5=-2.9
6=-3.9
7=-5.2
