[File]
Release=3.0

[Id]
Location=Iceline Plot
Title1=Parks Canada
Title2=Banff-Yoho-Kootenay
Date=2001/04/03
Time=13:36
Observer=GHI   GP
Altitude=1810
AltUnits=
Coords=      ,
Aspect=8
Slope=0
ProfileNbr=TA010403
ProfileType=test

[Surface]
Roughness=Smooth
AirTemp=0.1
PackHeight=150
LayerDown=0
PlotDown=0

[Penetration]
Ski= 16
Foot= 25

[Wind]
Speed=Light
Direction=South East

[Sky]
Condition=Scattered Clouds

[Ram]
Hardness=

[Precip]
Type=Nil
Rate=

[SnowTempLayers]
Count=16
SnowColour=16711680
SnowLine=16711680

[SnowHeight]
1=0
2=10
3=20
4=30
5=40
6=50
7=60
8=70
9=80
10=90
11=100
12=110
13=120
14=130
15=140
16=150

[SnowTemp]
1=-0.2
2=-0.4
3=-0.6
4=-0.9
5=-1.0
6=-1.2
7=-1.4
8=-1.7
9=-1.9
10=-2.1
11=-2.2
12=-2.4
13=-2.5
14=-2.5
15=-1.5
16=-1.4

[RamLayers]
RamColour=0
HardnessOnly=0
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1100
HandRamScale=0

[CrystalLayerHeight]
SymbolColour=16711680
1=-1
2=27
3=81
4=91
5=92
6=95
7=118
8=119
9=123
10=127
11=139
12=150

[Comments]
Count=2
1=Storm boards had 31 cm HST since March 21.  THe 03/21 HS was 143, which indicates that there has been
2=significant settlement
Stability=N

[CrystalLLayers]
BottomOfPit=0
Count=12

[CrystalLayerWaterContent]
1=Dry
2=Dry
3=Dry
4=Dry
5=Dry
6=Dry
7=Dry
8=Dry
9=Dry
10=Dry
11=Dry
12=Dry

[CrystalLayerGrainForm1]
1=2
2=4
3=4
4=3
5=4
6=3
7=3
8=9e
9=3c
10=2
11=2
12=2

[CrystalLayerGrainRimed1]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=

[CrystalLayerGrainDiameter1]
1=1.5
2=3
3=2
4=1
5=2
6=.5
7=.5 - 1
8=
9=1
10=1
11=1 - 1.5
12=2

[CrystalLayerGrainForm2]
1=
2=5
3=
4=4
5=7
6=
7=
8=
9=
10=
11=
12=1

[CrystalLayerGrainRimed2]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=

[CrystalLayerGrainDiameter2]
1=
2=4
3=
4=1
5=3
6=
7=
8=
9=
10=
11=
12=2

[CrystalLayerHandHardness]
1=N/A
2=F+
3=4F+
4=P
5=1F+
6=P
7=1F
8=P+
9=4F
10=F
11=4F
12=F

[CrystalLayerDensity]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0
9=0
10=0
11=0
12=0

[CrystalLayerDensityEstimated]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=

[CrystalLayerComments]
1=
2=
3=CTH, STH BTH @ 65 in FC
4=
5=
6=
7=
8=
9=CTM17 @ 127
10=
11=
12=CTE6 @ 139, STE @ 139|~

[CrystalLayerCommentsPosition]
1=1
2=1
3=1
4=1
5=1
6=1
7=1
8=1
9=1
10=1
11=1
12=1

[CrystalLayerCommentsSlope]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0
9=0
10=0
11=0
12=0
