[File]
Release=3.0

[Id]
Location=Takkakaw/Iceline plot
Title1=Parks Canada
Title2=Banff-Yoho-Kootenay
Date=2001/03/21
Time=13:25
Observer=AH RB
Altitude=1810
AltUnits=
Coords=      ,
Aspect=8
Slope=0
ProfileNbr=TA010321
ProfileType=Full

[Surface]
Roughness=Smooth
AirTemp=-3.0
PackHeight=143
LayerDown=0
PlotDown=0

[Penetration]
Ski=
Foot=

[Wind]
Speed=Light
Direction=South

[Sky]
Condition=Overcast

[Ram]
Hardness=

[Precip]
Type=Snow
Rate=Very Light

[SnowTempLayers]
Count=14
SnowColour=16711680
SnowLine=16711680

[SnowHeight]
1=0
2=10
3=20
4=40
5=50
6=60
7=70
8=80
9=90
10=100
11=110
12=120
13=133
14=143

[SnowTemp]
1=-0.2
2=-0.7
3=-0.9
4=-1.3
5=-1.6
6=-1.7
7=-1.9
8=-2.2
9=-2.4
10=-2.7
11=-3.0
12=-3.0
13=-1.0
14=-0.1

[RamLayers]
RamColour=0
HardnessOnly=0
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1100
HandRamScale=0

[CrystalLayerHeight]
SymbolColour=16711680
1=-1
2=20
3=48
4=93
5=94
6=98
7=99
8=110
9=130
10=143

[Comments]
Count=1
1=storm board 47 cm
Stability=N

[CrystalLLayers]
BottomOfPit=0
Count=10

[CrystalLayerWaterContent]
1=Dry
2=Dry
3=Dry
4=Dry
5=Dry
6=Dry
7=Dry
8=Dry
9=Dry
10=Dry

[CrystalLayerGrainForm1]
1=1
2=4
3=4
4=4
5=9e
6=3
7=9e
8=2
9=2
10=2

[CrystalLayerGrainRimed1]
1=r
2=
3=
4=
5=
6=
7=
8=
9=
10=

[CrystalLayerGrainDiameter1]
1=2
2=2
3=2-3
4=1-2
5=1-2
6=.5
7=
8=.5-1
9=1
10=1.5

[CrystalLayerGrainForm2]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=

[CrystalLayerGrainRimed2]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=

[CrystalLayerGrainDiameter2]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=

[CrystalLayerHandHardness]
1=N/A
2=4F
3=1F+
4=1F
5=P+
6=P+
7=P
8=1F
9=F
10=F

[CrystalLayerDensity]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0
9=0
10=0

[CrystalLayerDensityEstimated]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=

[CrystalLayerComments]
1=
2=
3=
4=some rounding
5=old sun crust
6=
7=some facetting
8=some facetting
9=
10=

[CrystalLayerCommentsPosition]
1=1
2=1
3=1
4=1
5=1
6=1
7=1
8=1
9=1
10=1

[CrystalLayerCommentsSlope]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0
9=0
10=0

[ShearLayers]
Count=1

[ShearLayerHeight]
1=110

[ShearLayerType]
1=Compression

[ShearLayerValue]
1=M  - Moderate

[ShearHits]
1=16

[ShearLayerComments]
1= x 2 @ new snow interface

[ShearLayerCommentsPosition]
1=3
