[File]
Release=3.0

[Id]
Location=Takkakaw/Iceline plot
Title1=Parks Canada
Title2=Banff-Yoho-Kootenay
Date=2001/02/07
Time=12:30
Observer=AH GJSS
Altitude=1922
AltUnits=
Coords=      ,
Aspect=8
Slope=0
ProfileNbr=TK010207
ProfileType=Test

[Surface]
Roughness=Smooth
AirTemp=-13.0
PackHeight=114
LayerDown=0
PlotDown=0

[Penetration]
Ski= 15
Foot=

[Wind]
Speed=Calm
Direction=N/A

[Sky]
Condition=Scattered Clouds

[Ram]
Hardness=

[Precip]
Type=Nil
Rate=

[SnowTempLayers]
Count=13
SnowColour=16711680
SnowLine=16711680

[SnowHeight]
1=0
2=10
3=20
4=30
5=40
6=50
7=60
8=70
9=80
10=90
11=100
12=104
13=114

[SnowTemp]
1=-0.4
2=-1.9
3=-2.9
4=-3.4
5=-3.9
6=-4.3
7=-4.8
8=-5.5
9=-7.2
10=-10.6
11=-13.0
12=-13.7
13=-20.4

[RamLayers]
RamColour=0
HardnessOnly=0
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1100
HandRamScale=0

[CrystalLayerHeight]
SymbolColour=16711680
1=-1
2=26
3=41
4=68
5=77
6=84
7=97
8=114

[Comments]
Count=1
1=buried surface hoar layer at 68
Stability=N

[CrystalLLayers]
BottomOfPit=0
Count=8

[CrystalLayerWaterContent]
1=Dry
2=Dry
3=Dry
4=Dry
5=Dry
6=Dry
7=Dry
8=Dry

[CrystalLayerGrainForm1]
1=7
2=5
3=4
4=4
5=4
6=4
7=2
8=2

[CrystalLayerGrainRimed1]
1=
2=
3=
4=
5=
6=
7=
8=

[CrystalLayerGrainDiameter1]
1=2
2=2-3
3=1
4=1
5=1
6=.5-1
7=1
8=2

[CrystalLayerGrainForm2]
1=2
2=4
3=
4=
5=3
6=2
7=4
8=

[CrystalLayerGrainRimed2]
1=
2=
3=
4=
5=
6=
7=
8=

[CrystalLayerGrainDiameter2]
1=1
2=2-3
3=
4=
5=1
6=.5-1
7=1
8=

[CrystalLayerHandHardness]
1=N/A
2=F
3=P-
4=1F+
5=1F+
6=1F
7=4F-
8=F

[CrystalLayerDensity]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0

[CrystalLayerDensityEstimated]
1=
2=
3=
4=
5=
6=
7=
8=

[CrystalLayerComments]
1=
2=
3=
4=
5=
6=
7=
8=

[CrystalLayerCommentsPosition]
1=1
2=1
3=1
4=1
5=1
6=1
7=1
8=1

[CrystalLayerCommentsSlope]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0

[ShearLayers]
Count=2

[ShearLayerHeight]
1=68
2=68

[ShearLayerType]
1=Shovel
2=Compression

[ShearLayerValue]
1=M - Moderate
2=H  - Hard

[ShearHits]
1=0
2=3

[ShearLayerComments]
1=plus STE @68, both failed on buried sh @68
2=x2

[ShearLayerCommentsPosition]
1=3
2=3
