[File]
Release=3.0

[Id]
Location=Takkakaw/Iceline plot
Title1=Parks Canada
Title2=Banff-Yoho-Kootenay
Date=2001/03/07
Time=09:00
Observer=AH GJSS
Altitude=1810
AltUnits=
Coords=,
Aspect=8
Slope=0
ProfileNbr=TA010307
ProfileType=Full

[Surface]
Roughness=Smooth
AirTemp=-3.4
PackHeight=110
LayerDown=0
PlotDown=0

[Penetration]
Ski=
Foot=50

[Wind]
Speed=Calm
Direction=N/A

[Sky]
Condition=Clear

[Ram]
Hardness=

[Precip]
Type=Nil
Rate=

[SnowTempLayers]
Count=12
SnowColour=16711680
SnowLine=16711680

[SnowHeight]
1=0
2=10
3=20
4=30
5=40
6=50
7=60
8=70
9=80
10=90
11=100
12=110

[SnowTemp]
1=-0.4
2=-1.0
3=-1.6
4=-2.2
5=-2.6
6=-3.0
7=-3.5
8=-4.0
9=-4.6
10=-6.5
11=-9.5
12=-12.2

[RamLayers]
RamColour=0
HardnessOnly=0
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1100
HandRamScale=0

[CrystalLayerHeight]
SymbolColour=16711680
1=-1
2=24
3=50
4=67
5=90
6=98
7=107
8=108
9=110

[Comments]
Count=2
1=
2=H INT 8.5
Stability=N

[CrystalLLayers]
BottomOfPit=0
Count=9

[CrystalLayerWaterContent]
1=Dry
2=Dry
3=Dry
4=Dry
5=Dry
6=Dry
7=Dry
8=Dry
9=Dry

[CrystalLayerGrainForm1]
1=7
2=5
3=4
4=4
5=4
6=4
7=2
8=9e
9=7

[CrystalLayerGrainRimed1]
1=
2=
3=
4=
5=
6=
7=
8=
9=

[CrystalLayerGrainDiameter1]
1=2-3
2=4-6
3=2-3
4=1-2
5=1
6=1
7=1-2
8=
9=3

[CrystalLayerGrainForm2]
1=
2=
3=
4=
5=
6=
7=
8=
9=2

[CrystalLayerGrainRimed2]
1=
2=
3=
4=
5=
6=
7=
8=
9=

[CrystalLayerGrainDiameter2]
1=
2=
3=
4=
5=
6=
7=
8=
9=3

[CrystalLayerHandHardness]
1=N/A
2=4F
3=P
4=1F
5=1F-
6=1F
7=4F-
8=P
9=F

[CrystalLayerDensity]
1=0
2=230
3=290
4=240
5=240
6=170
7=105
8=0
9=0

[CrystalLayerDensityEstimated]
1=
2=
3=
4=
5=
6=
7=
8=
9=

[CrystalLayerComments]
1=
2=
3=
4=STM @ 67
5=
6=
7=
8=
9=

[CrystalLayerCommentsPosition]
1=1
2=1
3=1
4=1
5=1
6=1
7=1
8=1
9=1

[CrystalLayerCommentsSlope]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0
9=0

[ShearLayers]
Count=2

[ShearLayerHeight]
1=24
2=67

[ShearLayerType]
1=Compression
2=Compression

[ShearLayerValue]
1=H  - Hard
2=H  - Hard

[ShearHits]
1=3
2=7

[ShearLayerComments]
1=and CTH7
2=

[ShearLayerCommentsPosition]
1=3
2=3
