[File]
Release=3.0

[Id]
Location=Takkakaw/Iceline plot
Title1=Parks Canada
Title2=Banff-Yoho-Kootenay
Date=2001/02/28
Time=12:40
Observer=AH
Altitude=1810
AltUnits=
Coords=      ,
Aspect=8
Slope=0
ProfileNbr=TA010228
ProfileType=FULL

[Surface]
Roughness=Smooth
AirTemp=-2.0
PackHeight=112
LayerDown=0
PlotDown=0

[Penetration]
Ski= 20
Foot=

[Wind]
Speed=Calm
Direction=N/A

[Sky]
Condition=Clear

[Ram]
Hardness=

[Precip]
Type=Nil
Rate=

[SnowTempLayers]
Count=12
SnowColour=16711680
SnowLine=16711680

[SnowHeight]
1=0
2=10
3=20
4=30
5=40
6=50
7=60
8=70
9=80
10=90
11=102
12=112

[SnowTemp]
1=-0.5
2=-0.9
3=-2.0
4=-4.5
5=-3.5
6=-5.5
7=-5.0
8=-6.0
9=-6.8
10=-8.0
11=-8.3
12=-3.1

[RamLayers]
RamColour=0
HardnessOnly=0
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1100
HandRamScale=0

[CrystalLayerHeight]
SymbolColour=16711680
1=-1
2=30
3=68
4=72
5=90
6=94
7=104
8=112

[Comments]
Count=2
1=
2=Storm Board 15 cm
Stability=N

[CrystalLLayers]
BottomOfPit=0
Count=8

[CrystalLayerWaterContent]
1=Dry
2=Dry
3=Dry
4=Dry
5=Dry
6=Dry
7=Dry
8=Dry

[CrystalLayerGrainForm1]
1=2
2=5
3=4
4=4
5=4
6=4
7=4
8=2

[CrystalLayerGrainRimed1]
1=
2=
3=
4=
5=
6=
7=
8=

[CrystalLayerGrainDiameter1]
1=.5-1
2=2-3
3=1.5
4=1.5
5=1
6=1.5
7=1
8=1.5

[CrystalLayerGrainForm2]
1=
2=
3=
4=
5=
6=
7=
8=

[CrystalLayerGrainRimed2]
1=
2=
3=
4=
5=
6=
7=
8=

[CrystalLayerGrainDiameter2]
1=
2=
3=
4=
5=
6=
7=
8=

[CrystalLayerHandHardness]
1=N/A
2=4F
3=1F+
4=1F+
5=1F+
6=1F
7=4F
8=F

[CrystalLayerDensity]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0

[CrystalLayerDensityEstimated]
1=
2=
3=
4=
5=
6=
7=
8=

[CrystalLayerComments]
1=
2=
3=STH @ 68 X2
4=
5=
6=
7=
8=

[CrystalLayerCommentsPosition]
1=1
2=1
3=1
4=1
5=1
6=1
7=1
8=1

[CrystalLayerCommentsSlope]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0

[ShearLayers]
Count=2

[ShearLayerHeight]
1=68
2=95

[ShearLayerType]
1=Compression
2=Compression

[ShearLayerValue]
1=H  - Hard
2=H  - Hard

[ShearHits]
1=9
2=3

[ShearLayerComments]
1=x 2 on some buried SH
2=

[ShearLayerCommentsPosition]
1=3
2=3
