[PopupMenu]
Showlayerslope=0
ShearHideAllComments=0
LayersHideAllComments=0
RamHideAllLayers=0
SnowTempHideAllLayers=0
ShearStress=0
HardnessType=0

[File]
Release=3.0

[Id]
Location=Takakkaw Falls Plot
Title1=Parks Canada
Title2=Banff-Yoho-Kootenay
Date=2002/03/22
Time=12:05
Observer=AH JM
Altitude=1810
AltUnits=Metres
Coords=      ,
Aspect=1
Slope=0
ProfileNbr=
ProfileType=

[Surface]
Roughness=
AirTemp=0.0
PackHeight=265
LayerDown=0
PlotDown=0

[Penetration]
Ski=
Foot=

[Wind]
Speed=
Direction=N/A

[Sky]
Condition=

[Ram]
Hardness=

[Precip]
Type=
Rate=

[SnowTempLayers]
MinTemperatureScale=-22
Count=23
SnowColour=16711680
SnowLine=16711680

[SnowHeight]
1=0
2=20
3=40
4=60
5=80
6=90
7=100
8=120
9=130
10=140
11=150
12=160
13=170
14=180
15=190
16=200
17=210
18=220
19=230
20=240
21=250
22=260
23=265

[SnowTemp]
1=-0.5
2=-1.0
3=-2.2
4=-3.4
5=-4.2
6=-5.0
7=-6.3
8=-6.7
9=-7.3
10=-7.7
11=-8.3
12=-8.5
13=-9.0
14=-9.2
15=-9.5
16=-10.4
17=-11.1
18=-11.7
19=-12.6
20=-12.8
21=-8.8
22=-0.1
23=-0.1

[RamLayers]
RamColour=0
HardnessOnly=0
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1100
HandRamScale=0

[CrystalLayerHeight]
SymbolColour=16711680
1=-1
2=31
3=35
4=92
5=98
6=101
7=105
8=115
9=155
10=175
11=188
12=192
13=215
14=233
15=243
16=249
17=265

[CrystalLLayers]
BottomOfPit=0
Count=17

[CrystalLayerWaterContent]
1=Dry
2=Dry
3=Dry
4=Dry
5=Dry
6=Dry
7=Dry
8=Dry
9=Dry
10=Dry
11=Dry
12=Dry
13=Dry
14=Dry
15=Dry
16=Dry
17=Dry

[CrystalLayerGrainForm1]
1=2
2=3
3=9
4=3
5=3
6=9
7=3
8=3
9=3
10=3
11=3
12=3
13=3
14=2
15=2
16=2
17=4c

[CrystalLayerGrainRimed1]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=
14=
15=
16=
17=

[CrystalLayerGrainDiameter1]
1=.5
2=4-5
3=
4=1
5=1
6=
7=2
8=1.5
9=.5
10=.5
11=.5-1
12=1
13=.5
14=1-2
15=1
16=1
17=.25-.5

[CrystalLayerGrainForm2]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=
14=
15=
16=
17=

[CrystalLayerGrainRimed2]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=
14=
15=
16=
17=

[CrystalLayerGrainDiameter2]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=
14=
15=
16=
17=

[CrystalLayerHandHardness]
1=N/A
2=P
3=P+
4=P
5=1F+
6=P+
7=1F-
8=1F
9=P
10=P
11=1F
12=1F-
13=1F
14=4F+
15=4F
16=4F-
17=F

[CrystalLayerDensity]
1=0
2=410
3=0
4=400
5=0
6=0
7=0
8=330
9=350
10=330
11=300
12=280
13=285
14=245
15=190
16=155
17=155

[CrystalLayerDensityEstimated]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=
14=
15=
16=
17=

[CrystalLayerComments]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=
14=
15=
16=
17=

[CrystalLayerCommentsPosition]
1=1
2=1
3=1
4=1
5=1
6=1
7=1
8=1
9=1
10=1
11=1
12=1
13=1
14=1
15=1
16=1
17=1

[CrystalLayerCommentsSlope]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0
9=0
10=0
11=0
12=0
13=0
14=0
15=0
16=0
17=0

[Comments]
Stability=N

[ShearLayers]
Count=4

[ShearLayerHeight]
1=185
2=215
3=243
4=249

[ShearLayerType]
1=Compression
2=Compression
3=Compression
4=Compression

[ShearLayerValue]
1=H  - Hard
2=H  - Hard
3=E  - Easy
4=E  - Easy

[ShearHits]
1=24
2=22
3=8
4=2

[ShearLayerComments]
1=
2=
3=
4=

[ShearLayerCommentsPosition]
1=3
2=3
3=3
4=3
