[PopupMenu]
Showlayerslope=0
ShearHideAllComments=0
LayersHideAllComments=0
RamHideAllLayers=0
SnowTempHideAllLayers=0
ShearStress=0
HardnessType=0

[File]
Release=3.0

[Id]
Location=Takakkaw Falls Plot
Title1=Parks Canada
Title2=Banff-Yoho-Kootenay
Date=2002/03/06
Time=12:55
Observer=AH GHI
Altitude=
AltUnits=Metres
Coords=      ,
Aspect=8
Slope=0
ProfileNbr=TA020306
ProfileType=Full

[Surface]
Roughness=Smooth
AirTemp=-16.8
PackHeight=255
LayerDown=0
PlotDown=0

[Penetration]
Ski= 29
Foot= 60

[Wind]
Speed=Light
Direction=East

[Sky]
Condition=Scattered Clouds

[Ram]
Hardness=

[Precip]
Type=
Rate=

[SnowTempLayers]
MinTemperatureScale=-22
Count=22
SnowColour=16711680
SnowLine=16711680

[SnowHeight]
1=0
2=20
3=40
4=60
5=80
6=100
7=110
8=120
9=130
10=140
11=150
12=160
13=170
14=180
15=190
16=200
17=210
18=220
19=230
20=240
21=245
22=255

[SnowTemp]
1=0.1
2=-0.7
3=-1.7
4=-2.5
5=-3.5
6=-4.2
7=-4.9
8=-5.4
9=-5.8
10=-6.3
11=-6.9
12=-7.3
13=-7.5
14=-7.7
15=-7.8
16=-7.8
17=-8.2
18=-9.5
19=-11.8
20=-13.2
21=-13.5
22=-16.9

[RamLayers]
RamColour=0
HardnessOnly=0
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1100
HandRamScale=0

[CrystalLayerHeight]
SymbolColour=16711680
1=-1
2=14
3=37
4=45
5=54
6=97
7=108
8=120
9=123
10=150
11=158
12=176
13=211
14=219
15=230
16=247
17=255

[CrystalLLayers]
BottomOfPit=0
Count=17

[CrystalLayerWaterContent]
1=Dry
2=Dry
3=Dry
4=Dry
5=Dry
6=Dry
7=Dry
8=Dry
9=Dry
10=Dry
11=Dry
12=Dry
13=Dry
14=Dry
15=Dry
16=Dry
17=Dry

[CrystalLayerGrainForm1]
1=2
2=3
3=4
4=5
5=4c
6=3
7=4c
8=4
9=4c
10=4
11=4
12=4c
13=4c
14=3
15=2
16=2
17=1

[CrystalLayerGrainRimed1]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=
14=
15=
16=
17=

[CrystalLayerGrainDiameter1]
1=1
2=1-2
3=2-3
4=3-4
5=2
6=1
7=1.5
8=1.5
9=1
10=.5-1
11=.5-1
12=.5
13=.5
14=1
15=2
16=1
17=2

[CrystalLayerGrainForm2]
1=
2=
3=
4=
5=
6=
7=9
8=
9=
10=
11=
12=
13=
14=
15=3
16=
17=2

[CrystalLayerGrainRimed2]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=
14=
15=
16=
17=

[CrystalLayerGrainDiameter2]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=
14=
15=.5
16=
17=1

[CrystalLayerHandHardness]
1=N/A
2=P
3=P
4=1F+
5=P
6=P
7=P+
8=P+
9=1F
10=P
11=P
12=1F+
13=1F
14=4F
15=F+
16=F
17=F

[CrystalLayerDensity]
1=0
2=375
3=350
4=310
5=330
6=330
7=330
8=300
9=330
10=390
11=300
12=280
13=180
14=150
15=100
16=105
17=70

[CrystalLayerDensityEstimated]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=
14=
15=
16=
17=

[CrystalLayerComments]
1=
2=
3=rounding
4=rounding
5=
6=
7=
8=
9=
10=
11=
12=
13=
14=
15=
16=
17=

[CrystalLayerCommentsPosition]
1=1
2=1
3=1
4=1
5=1
6=1
7=1
8=1
9=1
10=1
11=1
12=1
13=1
14=1
15=1
16=1
17=1

[CrystalLayerCommentsSlope]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0
9=0
10=0
11=0
12=0
13=0
14=0
15=0
16=0
17=0

[Comments]
Stability=N

[ShearLayers]
Count=3

[ShearLayerHeight]
1=176
2=208
3=230

[ShearLayerType]
1=Compression
2=Compression
3=Compression

[ShearLayerValue]
1=H  - Hard
2=M  - Moderate
3=E  - Easy

[ShearHits]
1=30
2=17
3=7

[ShearLayerComments]
1=on V
2=
3=STE on +/

[ShearLayerCommentsPosition]
1=3
2=3
3=3
