[PopupMenu]
Showlayerslope=0
ShearHideAllComments=0
LayersHideAllComments=0
RamHideAllLayers=0
SnowTempHideAllLayers=0
ShearStress=0
HardnessType=0

[File]
Release=3.0

[Id]
Location=Takakkaw Falls Plot
Title1=Parks Canada
Title2=Banff-Yoho-Kootenay
Date=
Time=12:50
Observer=AH BW
Altitude=1810
AltUnits=Metres
Coords=      ,
Aspect=1
Slope=0
ProfileNbr=TA020221
ProfileType=Full

[Surface]
Roughness=Smooth
AirTemp=-0.3
PackHeight=211
LayerDown=0
PlotDown=0

[Penetration]
Ski=
Foot=

[Wind]
Speed=
Direction=N/A

[Sky]
Condition=Overcast

[Ram]
Hardness=

[Precip]
Type=Snow
Rate=Moderate

[SnowTempLayers]
MinTemperatureScale=-11
Count=16
SnowColour=16711680
SnowLine=16711680

[SnowHeight]
1=0
2=40
3=60
4=80
5=100
6=110
7=120
8=130
9=140
10=150
11=160
12=170
13=180
14=190
15=201
16=211

[SnowTemp]
1=-0.3
2=-2.7
3=-3.4
4=-4.2
5=-5.0
6=-5.3
7=-5.6
8=-5.8
9=-6.0
10=-6.1
11=-6.1
12=-6.3
13=-6.5
14=-6.9
15=-6.5
16=-0.3

[RamLayers]
RamColour=16711680
HardnessOnly=0
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1100
HandRamScale=0

[CrystalLayerHeight]
SymbolColour=16711680
1=-1
2=48
3=86
4=87
5=105
6=116
7=128
8=160
9=176
10=183
11=202
12=211

[Comments]
Count=4
1=
2=Clean hard tests on SH
3=
4=Boards 35 cm
Stability=N

[CrystalLLayers]
BottomOfPit=0
Count=12

[CrystalLayerWaterContent]
1=Dry
2=Dry
3=Dry
4=Dry
5=Dry
6=Dry
7=Dry
8=Dry
9=Dry
10=Dry
11=Dry
12=Dry

[CrystalLayerGrainForm1]
1=1
2=4
3=4c
4=7
5=9e
6=4c
7=3
8=3
9=3
10=3
11=1
12=1

[CrystalLayerGrainRimed1]
1=r
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=r

[CrystalLayerGrainDiameter1]
1=1
2=3
3=1.5-2
4=6
5=
6=1
7=.3
8=.5
9=.5
10=1
11=1.5
12=1

[CrystalLayerGrainForm2]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=2
12=

[CrystalLayerGrainRimed2]
1=r
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=

[CrystalLayerGrainDiameter2]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=1.5
12=

[CrystalLayerHandHardness]
1=N/A
2=P-
3=P
4=1F
5=K
6=P-
7=P+
8=P
9=1F+
10=1F
11=F+
12=F

[CrystalLayerDensity]
1=0
2=320
3=320
4=0
5=0
6=300
7=330
8=290
9=240
10=180
11=110
12=100

[CrystalLayerDensityEstimated]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=

[CrystalLayerComments]
1=
2=striated
3=
4=
5=K variable, with facets 1.5, facets 2 on top
6=
7=
8=
9=
10=
11=
12=

[CrystalLayerCommentsPosition]
1=1
2=1
3=1
4=1
5=1
6=1
7=1
8=1
9=1
10=1
11=1
12=1

[CrystalLayerCommentsSlope]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0
9=0
10=0
11=0
12=0

[ShearLayers]
Count=3

[ShearLayerHeight]
1=87
2=183
3=202

[ShearLayerType]
1=Compression
2=Compression
3=Compression

[ShearLayerValue]
1=H  - Hard
2=M  - Moderate
3=E  - Easy

[ShearHits]
1=26
2=14
3=10

[ShearLayerComments]
1=clean shear
2=
3=

[ShearLayerCommentsPosition]
1=3
2=3
3=3
