[PopupMenu]
Showlayerslope=1
ShearHideAllComments=0
LayersHideAllComments=0
RamHideAllLayers=0
SnowTempHideAllLayers=0
ShearStress=0
HardnessType=0

[File]
Release=3.0

[Id]
Location=Takakaw Falls Plot
Title1=Parks Canada
Title2=Banff-Yoho-Kootenay
Date=2001/12/28
Time=14:25
Observer=AH PW
Altitude=1810
AltUnits=Metres
Coords=      ,
Aspect=2
Slope=0
ProfileNbr=TAK011229
ProfileType=Full

[Surface]
Roughness=Smooth
AirTemp=-12.5
PackHeight=126
LayerDown=0
PlotDown=0

[Penetration]
Ski= 15
Foot=

[Wind]
Speed=Calm
Direction=N/A

[Sky]
Condition=Scattered Clouds

[Ram]
Hardness=

[Precip]
Type=Nil
Rate=

[SnowTempLayers]
MinTemperatureScale=-11
Count=13
SnowColour=16711680
SnowLine=16711680

[SnowHeight]
1=10
2=20
3=30
4=40
5=50
6=60
7=70
8=80
9=90
10=100
11=110
12=116
13=126

[SnowTemp]
1=-0.6
2=-1.5
3=-1.9
4=-2.9
5=-3.7
6=-4.8
7=-6.2
8=-7.7
9=-10.1
10=-12.9
11=-15.8
12=-17.9
13=-17.7

[RamLayers]
RamColour=0
HardnessOnly=0
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1100
HandRamScale=0

[CrystalLayerHeight]
SymbolColour=16711680
1=-1
2=15
3=37
4=50
5=68
6=80
7=83
8=101
9=120
10=126

[Comments]
Count=2
1=No results on comp or shovel shear tests.  SH is building, found the whole way up the road and growing in size as you
2=gain elevation to the plot.
Stability=N

[CrystalLLayers]
BottomOfPit=0
Count=10

[CrystalLayerWaterContent]
1=Dry
2=Dry
3=Dry
4=Dry
5=Dry
6=Dry
7=Dry
8=Dry
9=Dry
10=Dry

[CrystalLayerGrainForm1]
1=
2=4
3=4
4=9
5=4
6=4
7=4
8=4
9=4
10=4

[CrystalLayerGrainRimed1]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=

[CrystalLayerGrainDiameter1]
1=
2=1
3=2
4=3
5=1
6=1.5
7=1
8=.5-1.0
9=.5-1.0
10=.5

[CrystalLayerGrainForm2]
1=
2=
3=
4=
5=4
6=4
7=7
8=
9=
10=

[CrystalLayerGrainRimed2]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=

[CrystalLayerGrainDiameter2]
1=
2=
3=
4=
5=2
6=2-3
7=1.5
8=
9=
10=

[CrystalLayerHandHardness]
1=N/A
2=P
3=P
4=P+
5=P
6=P
7=1F+
8=1F
9=4F-
10=F

[CrystalLayerDensity]
1=0
2=310
3=330
4=330
5=300
6=300
7=235
8=210
9=190
10=85

[CrystalLayerDensityEstimated]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=

[CrystalLayerComments]
1=
2=
3=
4=
5=2 is conglomerate
6=2-3 is conglomerates
7=
8=
9=
10=

[CrystalLayerCommentsPosition]
1=1
2=1
3=1
4=1
5=1
6=1
7=1
8=1
9=1
10=1

[CrystalLayerCommentsSlope]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0
9=0
10=0
