[PopupMenu]
Showlayerslope=1
ShearHideAllComments=0
LayersHideAllComments=0
RamHideAllLayers=0
SnowTempHideAllLayers=0
ShearStress=1
HardnessType=0

[File]
Release=3.0

[Id]
Location=Takakaw Plot
Title1=Parks Canada
Title2=Banff/Yoho/Kootenay
Date=2002/04/04
Time=10:40
Observer=PW
Altitude=1810
AltUnits=Metres
Coords=      ,
Aspect=1
Slope=0
ProfileNbr=Tak020404
ProfileType=Full

[Surface]
Roughness=Smooth
AirTemp=1.0
PackHeight=262
LayerDown=0
PlotDown=0

[Penetration]
Ski= 17
Foot= 28

[Wind]
Speed=Light
Direction=South West

[Sky]
Condition=Broken Clouds

[Ram]
Hardness=

[Precip]
Type=Snow
Rate=Very Light

[SnowTempLayers]
MinTemperatureScale=-11
Count=13
SnowColour=16711680
SnowLine=16711680

[SnowHeight]
1=10
2=60
3=100
4=120
5=140
6=160
7=180
8=200
9=220
10=240
11=250
12=252
13=262

[SnowTemp]
1=-0.5
2=-2.0
3=-2.0
4=-2.0
5=-4.0
6=-3.0
7=-4.0
8=-4.0
9=-5.0
10=-7.0
11=-8.0
12=-8.0
13=-1.0

[RamLayers]
RamColour=0
HardnessOnly=0
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1100
HandRamScale=0

[CrystalLayerHeight]
SymbolColour=16711680
1=-1
2=22
3=33
4=38
5=50
6=90
7=98
8=100
9=110
10=136
11=178
12=197
13=225
14=228
15=243
16=258
17=262

[CrystalLLayers]
BottomOfPit=0
Count=17

[CrystalLayerWaterContent]
1=Dry
2=Dry
3=Dry
4=Dry
5=Dry
6=Dry
7=Dry
8=Dry
9=Dry
10=Dry
11=Dry
12=Dry
13=Dry
14=Dry
15=Dry
16=Dry
17=Dry

[CrystalLayerGrainForm1]
1=
2=3
3=3
4=9
5=3
6=3
7=3
8=3
9=3
10=3
11=3
12=3
13=3
14=9
15=3
16=2
17=9

[CrystalLayerGrainRimed1]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=
14=
15=
16=
17=

[CrystalLayerGrainDiameter1]
1=
2=2-3
3=2-3
4=3
5=2-3
6=1.5
7=1
8=2
9=1.5
10=.5
11=1
12=.5-1
13=.5
14=2
15=.25
16=1
17=.5

[CrystalLayerGrainForm2]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=
14=
15=
16=
17=

[CrystalLayerGrainRimed2]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=
14=
15=
16=
17=

[CrystalLayerGrainDiameter2]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=
14=
15=
16=
17=

[CrystalLayerHandHardness]
1=N/A
2=P+
3=1F+
4=P
5=1F+
6=P+
7=P+
8=P
9=1F+
10=P+
11=P+
12=P
13=P
14=K
15=1F-
16=4F
17=P

[CrystalLayerDensity]
1=0
2=420
3=420
4=420
5=0
6=400
7=410
8=380
9=330
10=350
11=350
12=330
13=320
14=350
15=180
16=150
17=210

[CrystalLayerDensityEstimated]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=
14=
15=
16=
17=

[CrystalLayerComments]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=
14=
15=
16=
17=

[CrystalLayerCommentsPosition]
1=1
2=1
3=1
4=1
5=1
6=1
7=1
8=1
9=1
10=1
11=1
12=1
13=1
14=1
15=1
16=1
17=1

[CrystalLayerCommentsSlope]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0
9=0
10=0
11=0
12=0
13=0
14=0
15=0
16=0
17=0

[Comments]
Stability=N

[ShearLayers]
Count=4

[ShearLayerHeight]
1=228
2=228
3=258
4=258

[ShearLayerType]
1=Shovel
2=Compression
3=Compression
4=Shovel

[ShearLayerValue]
1=M - Moderate
2=M  - Moderate
3=E  - Easy
4=V - Very Easy

[ShearHits]
1=0
2=15
3=6
4=0

[ShearLayerComments]
1=
2=above cr on sz 1 rounds
3=on sz 1 DF
4=

[ShearLayerCommentsPosition]
1=3
2=3
3=3
4=3
