[PopupMenu]
Showlayerslope=0
ShearHideAllComments=0
LayersHideAllComments=0
RamHideAllLayers=0
SnowTempHideAllLayers=0
ShearStress=0
HardnessType=0

[File]
Release=3.0

[Id]
Location=Takakkaw Falls Plot
Title1=Parks Canada
Title2=Banff-Yoho-Kootenay
Date=2002/01/22
Time=13:10
Observer=AH GHI
Altitude=1810
AltUnits=Metres
Coords=      ,
Aspect=2
Slope=0
ProfileNbr=TA020122
ProfileType=Full

[Surface]
Roughness=Smooth
AirTemp=-9.2
PackHeight=164
LayerDown=0
PlotDown=0

[Penetration]
Ski=
Foot=

[Wind]
Speed=Light
Direction=South East

[Sky]
Condition=Overcast

[Ram]
Hardness=

[Precip]
Type=Snow
Rate=Light

[SnowTempLayers]
MinTemperatureScale=-22
Count=18
SnowColour=16711680
SnowLine=16711680

[SnowHeight]
1=0
2=10
3=20
4=30
5=40
6=50
7=60
8=70
9=80
10=90
11=100
12=110
13=120
14=130
15=140
16=150
17=153
18=163

[SnowTemp]
1=-0.2
2=-0.7
3=-1.1
4=-1.6
5=-2.4
6=-2.9
7=-3.5
8=-4.2
9=-5.0
10=-5.6
11=-6.4
12=-7.2
13=-7.8
14=-8.6
15=-9.2
16=-9.8
17=-9.5
18=-7.8

[RamLayers]
RamColour=0
HardnessOnly=0
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1100
HandRamScale=0

[CrystalLayerHeight]
SymbolColour=16711680
1=-1
2=15
3=16
4=38
5=53
6=77
7=92
8=93
9=103
10=107
11=112
12=123
13=125
14=139
15=164

[CrystalLLayers]
BottomOfPit=0
Count=15

[CrystalLayerWaterContent]
1=Dry
2=Dry
3=Dry
4=Dry
5=Dry
6=Dry
7=Dry
8=Dry
9=Dry
10=Dry
11=Dry
12=Dry
13=Dry
14=Dry
15=Dry

[CrystalLayerGrainForm1]
1=1
2=3
3=9
4=3
5=3
6=4
7=4
8=7
9=4
10=4c
11=4c
12=8
13=4
14=4
15=2

[CrystalLayerGrainRimed1]
1=r
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=
14=
15=

[CrystalLayerGrainDiameter1]
1=1
2=1
3=
4=
5=1-2
6=1-2
7=1
8=3-6
9=.5
10=.5-2
11=1-1.5
12=2-3
13=.5
14=1
15=1

[CrystalLayerGrainForm2]
1=
2=
3=
4=
5=3c
6=4c
7=
8=
9=
10=4
11=
12=4c
13=
14=
15=4c

[CrystalLayerGrainRimed2]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=
14=
15=

[CrystalLayerGrainDiameter2]
1=
2=
3=
4=
5=1-2
6=1-2
7=
8=
9=
10=.5-2
11=
12=2-3
13=
14=
15=1

[CrystalLayerHandHardness]
1=N/A
2=P
3=P
4=1F
5=1F-
6=P
7=1F+
8=1F
9=1F
10=P
11=1F
12=P
13=1F
14=4F
15=F

[CrystalLayerDensity]
1=0
2=380
3=0
4=360
5=330
6=350
7=280
8=0
9=240
10=260
11=230
12=330
13=230
14=160
15=65

[CrystalLayerDensityEstimated]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=
14=
15=

[CrystalLayerComments]
1=
2=
3=Nov rain crust
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=
14=
15=

[CrystalLayerCommentsPosition]
1=1
2=1
3=1
4=1
5=1
6=1
7=1
8=1
9=1
10=1
11=1
12=1
13=1
14=1
15=1

[CrystalLayerCommentsSlope]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0
9=0
10=0
11=0
12=0
13=0
14=0
15=0

[Comments]
Stability=N

[ShearLayers]
Count=3

[ShearLayerHeight]
1=92
2=134
3=151

[ShearLayerType]
1=Compression
2=Compression
3=Compression

[ShearLayerValue]
1=H  - Hard
2=M  - Moderate
3=E  - Easy

[ShearHits]
1=27
2=20
3=5

[ShearLayerComments]
1= X 2 on SH sz 3-6, STM @ 92
2= and CTM 17 @ 140
3=

[ShearLayerCommentsPosition]
1=3
2=3
3=3
