"""Station-to-ERA5 transfer for seasons without station records (ADR-025).

Before 2021-05 the study plots have no hourly station data, so the forcing is ERA5 alone. Two constants per
plot are estimated from the 2021-26 seasons, where both exist, and then applied unchanged to 1996-2021:

- ``ta_offset_k``: mean (station temperature at the plot - ERA5 temperature at the plot) over hours with a
  station value (the same offset the station-first assembly applies to its ERA5 fill);
- ``psum_ratio``: total gauge precipitation / total ERA5 precipitation over hours supplied by the gauge
  (plausibility-checked gauge hours only; replaced or ERA5-filled hours are excluded).

Per-season values are kept to show how stable the constants are. The adopted psum_factor (ADR-024) is still
applied on top with ``--corrected``, so ERA5-only runs are comparable with the station-driven runs.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
import yaml

from snowagent.baseline.assemble import _to_elevation, assemble, era5_cell_series
from snowagent.spatial_forcing.builder import ForcingConfig


def season_transfer(plot: str, year: int, cfg: dict, era5_dir: Path = Path("data/interim/era5")) -> dict:
    p = cfg["plots"][plot]
    start = pd.Timestamp(f"{year}-{cfg['season_start']}", tz="UTC")
    end = pd.Timestamp(f"{year + 1}-{cfg['season_end']}", tz="UTC")
    pf = assemble(plot, str(start), str(end), era5_dir=era5_dir)
    e5, e5_elev = era5_cell_series(p["lat"], p["lon"], pf.data.index, era5_dir)
    e5_ta, _ = _to_elevation(e5["ta"], e5["rh"], p["elevation_m"] - e5_elev, ForcingConfig().lapse_rate_k_per_m)
    st = pf.sources["ta"].isin(p.get("ta", [])) & e5_ta.notna()
    g = pf.sources["psum"].isin(p.get("psum", [])) & e5["psum"].notna()
    return {"ta_hours": int(st.sum()), "ta_offset_k": float((pf.data["ta"][st] - e5_ta[st]).mean()),
            "psum_hours": int(g.sum()), "gauge_mm": float(pf.data["psum"][g].sum()),
            "era5_mm": float(e5["psum"][g].sum())}


def derive(plots: list[str], seasons: list[int], cfg_path: Path = Path("config/plot_forcing.yaml")) -> dict:
    cfg = yaml.safe_load(Path(cfg_path).read_text())
    out: dict = {}
    for plot in plots:
        per = {f"{y}-{y + 1}": season_transfer(plot, y, cfg) for y in seasons}
        ta_h = np.array([v["ta_hours"] for v in per.values()])
        ta_o = np.array([v["ta_offset_k"] for v in per.values()])
        ok = ta_h > 0
        gauge = sum(v["gauge_mm"] for v in per.values())
        era5 = sum(v["era5_mm"] for v in per.values())
        out[plot] = {
            "ta_offset_k": round(float(np.average(ta_o[ok], weights=ta_h[ok])), 2),
            "psum_ratio": round(gauge / era5, 3) if era5 > 0 else 1.0,
            "per_season": {k: {"ta_offset_k": round(v["ta_offset_k"], 2), "ta_hours": v["ta_hours"],
                               "psum_ratio": round(v["gauge_mm"] / v["era5_mm"], 3) if v["era5_mm"] else None,
                               "gauge_mm": round(v["gauge_mm"]), "psum_hours": v["psum_hours"]}
                           for k, v in per.items()},
        }
    return out


def write(path: Path, transfer: dict, seasons: list[int]) -> None:
    header = (f"# Generated by `snowagent era5-transfer` from seasons {seasons[0]}-{seasons[-1] + 1} (ADR-025).\n"
              "# ERA5-only forcing (seasons without station data): ta = ERA5 at plot elevation + ta_offset_k;\n"
              "# psum = ERA5 x psum_ratio (x psum_factor from plot_forcing.yaml with --corrected).\n")
    path.write_text(header + yaml.safe_dump({"calibration_seasons": [f"{y}-{y + 1}" for y in seasons],
                                             "plots": transfer}, sort_keys=False))
