[PopupMenu]
Showlayerslope=0
ShearHideAllComments=0
LayersHideAllComments=0
RamHideAllLayers=0
SnowTempHideAllLayers=0
ShearStress=0
HardnessType=0

[File]
Release=3.0

[Id]
Location=Goat's Eye Plot
Title1=Parks Canada
Title2=Banff/Yoho/Kootenay
Date=07/03/02
Time=13:00
Observer=MH
Altitude=
AltUnits=Metres
Coords=      ,
Aspect=8
Slope=0
ProfileNbr=
ProfileType=Full

[Surface]
Roughness=Wavy
AirTemp=-24.0
PackHeight=174
LayerDown=0
PlotDown=0

[Penetration]
Ski=
Foot= 40

[Wind]
Speed=Light
Direction=West

[Sky]
Condition=Clear

[Ram]
Hardness=

[Precip]
Type=Nil
Rate=

[SnowTempLayers]
MinTemperatureScale=-11
Count=13
SnowColour=16711680
SnowLine=16711680

[SnowHeight]
1=60
2=70
3=80
4=90
5=100
6=110
7=120
8=130
9=140
10=150
11=160
12=164
13=174

[SnowTemp]
1=-3.7
2=-4.2
3=-4.7
4=-5.7
5=-5.9
6=-6.6
7=-7.2
8=-8.9
9=-10.9
10=-12.9
11=-18.9
12=-20.0
13=-21.0

[RamLayers]
RamColour=0
HardnessOnly=0
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1100
HandRamScale=0

[CrystalLayerHeight]
SymbolColour=16711680
1=-1
2=17
3=43
4=60
5=81
6=95
7=100
8=118
9=125
10=134
11=156
12=169
13=174

[Comments]
Count=2
1=Cold temps locking down snowpack. Hard results - large claas 3 on Borgeau 9 during storm cycle to creek. No
2=new in past 24 hrs.
Stability=U

[CrystalLLayers]
BottomOfPit=0
Count=13

[CrystalLayerWaterContent]
1=Dry
2=Dry
3=Dry
4=Dry
5=Dry
6=Dry
7=Dry
8=Dry
9=Dry
10=Dry
11=Dry
12=Dry
13=Dry

[CrystalLayerGrainForm1]
1=2
2=4
3=4
4=4
5=4c
6=4c
7=4c
8=4c
9=4c
10=4
11=4
12=4
13=4

[CrystalLayerGrainRimed1]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=

[CrystalLayerGrainDiameter1]
1=.5
2=2
3=3
4=2-3
5=1-2
6=1.5
7=1
8=1
9=1
10=1
11=.5
12=.5
13=.5

[CrystalLayerGrainForm2]
1=4
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=2
13=

[CrystalLayerGrainRimed2]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=

[CrystalLayerGrainDiameter2]
1=.25
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=.5
13=

[CrystalLayerHandHardness]
1=N/A
2=1F+
3=1F
4=1F-
5=P-
6=P-
7=P+
8=P
9=P
10=4F+
11=1F
12=4F
13=F

[CrystalLayerDensity]
1=0
2=310
3=260
4=250
5=300
6=320
7=360
8=300
9=270
10=240
11=190
12=120
13=100

[CrystalLayerDensityEstimated]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=

[CrystalLayerComments]
1=
2=October snow
3=old dh
4=conclomerates
5=
6=
7=wind cr
8=
9=
10=
11=
12=
13=

[CrystalLayerCommentsPosition]
1=1
2=1
3=1
4=1
5=1
6=1
7=1
8=1
9=1
10=1
11=1
12=1
13=1

[CrystalLayerCommentsSlope]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0
9=0
10=0
11=0
12=0
13=0

[ShearLayers]
Count=2

[ShearLayerHeight]
1=46
2=156

[ShearLayerType]
1=Compression
2=Compression

[ShearLayerValue]
1=H  - Hard
2=M  - Moderate

[ShearHits]
1=26
2=16

[ShearLayerComments]
1=noc cr
2=df & fcs

[ShearLayerCommentsPosition]
1=3
2=3
