[File]
Release=3.0

[Id]
Location=Sunshine Meadows
Title1=Parks Canada
Title2=Banff/Yoho/Kootenay
Date=22/02/01
Time=11:55
Observer=AH MH
Altitude=2475
AltUnits=
Coords=      ,
Aspect=8
Slope=0
ProfileNbr=GE010222
ProfileType=Full

[Surface]
Roughness=Smooth
AirTemp=-5.1
PackHeight=79
LayerDown=0
PlotDown=0

[Penetration]
Ski=
Foot=

[Wind]
Speed=Calm
Direction=N/A

[Sky]
Condition=Scattered Clouds

[Ram]
Hardness=

[Precip]
Type=Nil
Rate=

[SnowTempLayers]
Count=9
SnowColour=16711680
SnowLine=16711680

[SnowHeight]
1=0
2=10
3=20
4=30
5=40
6=50
7=60
8=69
9=79

[SnowTemp]
1=-2.1
2=-2.9
3=-4.0
4=-5.9
5=-7.2
6=-9.6
7=-11.8
8=-14.9
9=-4.3

[RamLayers]
RamColour=0
HardnessOnly=0
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1100
HandRamScale=0

[CrystalLayerHeight]
SymbolColour=16711680
1=-1
2=15
3=20
4=49
5=61
6=72
7=76
8=79

[CrystalLLayers]
BottomOfPit=0
Count=8

[CrystalLayerWaterContent]
1=Dry
2=Dry
3=Dry
4=Dry
5=Dry
6=Dry
7=Dry
8=Dry

[CrystalLayerGrainForm1]
1=7
2=5
3=4
4=4
5=4
6=4
7=4
8=4

[CrystalLayerGrainRimed1]
1=
2=
3=
4=
5=
6=
7=
8=

[CrystalLayerGrainDiameter1]
1=3-4
2=4
3=2-3
4=2-3
5=1-2
6=.5-1
7=.5-1
8=.5

[CrystalLayerGrainForm2]
1=
2=
3=
4=5
5=
6=
7=
8=

[CrystalLayerGrainRimed2]
1=
2=
3=
4=
5=
6=
7=
8=

[CrystalLayerGrainDiameter2]
1=
2=
3=
4=2-3
5=
6=
7=
8=

[CrystalLayerHandHardness]
1=N/A
2=1F
3=P
4=1F
5=4F
6=4F-
7=4F
8=F

[CrystalLayerDensity]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0

[CrystalLayerDensityEstimated]
1=
2=
3=
4=
5=
6=
7=
8=

[CrystalLayerComments]
1=
2=
3=November crust
4=
5=CTM12 @ 51
6=
7=
8=

[CrystalLayerCommentsPosition]
1=1
2=1
3=1
4=1
5=1
6=1
7=1
8=1

[CrystalLayerCommentsSlope]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0

[Comments]
Stability=N
