[File]
Release=3.0

[Id]
Location=Goat's Eye Plot
Title1=Parks Canada
Title2=Banff-Yoho-Kootenay
Date=3/7/01
Time=13:00
Observer=Brad White
Altitude=
AltUnits=
Coords=      ,
Aspect=5
Slope=0
ProfileNbr=01
ProfileType=Full

[Surface]
Roughness=Smooth
AirTemp=4.3
PackHeight=89
LayerDown=0
PlotDown=0

[Penetration]
Ski=
Foot= 60

[Wind]
Speed=Light
Direction=South West

[Sky]
Condition=Scattered Clouds

[Ram]
Hardness=

[Precip]
Type=Nil
Rate=

[SnowTempLayers]
Count=10
SnowColour=16711680
SnowLine=16711680

[SnowHeight]
1=0
2=10
3=20
4=30
5=40
6=50
7=60
8=70
9=79
10=89

[SnowTemp]
1=-2.6
2=-3.1
3=-4.2
4=-4.9
5=-5.5
6=-6.0
7=-7.2
8=-8.0
9=-5.5
10=-2.0

[RamLayers]
RamColour=0
HardnessOnly=0
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1100
HandRamScale=0

[CrystalLayerHeight]
SymbolColour=16711680
1=-1
2=11
3=43
4=62
5=78
6=89

[Comments]
Count=2
1=Considerable strength gain in upper snowpack since last profile. Shear on FC (62) underneath pencil layer is fast and
2=clean.
Stability=N

[CrystalLLayers]
BottomOfPit=0
Count=6

[CrystalLayerWaterContent]
1=Moist
2=Dry
3=Dry
4=Dry
5=Dry
6=Dry

[CrystalLayerGrainForm1]
1=2
2=9e
3=5
4=4
5=3c
6=2

[CrystalLayerGrainRimed1]
1=
2=
3=
4=
5=
6=

[CrystalLayerGrainDiameter1]
1=2
2=
3=
4=2
5=.5
6=1

[CrystalLayerGrainForm2]
1=
2=5
3=3b
4=5
5=
6=

[CrystalLayerGrainRimed2]
1=
2=
3=
4=
5=
6=

[CrystalLayerGrainDiameter2]
1=
2=
3=
4=3-5
5=
6=

[CrystalLayerHandHardness]
1=N/A
2=P
3=1F
4=4F
5=P
6=1F-

[CrystalLayerDensity]
1=0
2=220
3=180
4=200
5=220
6=110

[CrystalLayerDensityEstimated]
1=
2=
3=
4=
5=
6=

[CrystalLayerComments]
1=
2=
3=
4=
5=
6=

[CrystalLayerCommentsPosition]
1=1
2=1
3=1
4=1
5=1
6=1

[CrystalLayerCommentsSlope]
1=0
2=0
3=0
4=0
5=0
6=0

[ShearLayers]
Count=3

[ShearLayerHeight]
1=30
2=62
3=78

[ShearLayerType]
1=Compression
2=Compression
3=Compression

[ShearLayerValue]
1=H  - Hard
2=M  - Moderate
3=E  - Easy

[ShearHits]
1=25
2=12
3=10

[ShearLayerComments]
1=Collapse
2=ST Mod
3=Tilt Mod

[ShearLayerCommentsPosition]
1=3
2=3
3=3
