[File]
Release=3.0

[Id]
Location=Goat's Eye Plot
Title1=Parks Canada
Title2=Banff/Yoho/Kootenay
Date=
Time=
Observer=BW
Altitude=
AltUnits=
Coords=      ,
Aspect=8
Slope=0
ProfileNbr=01
ProfileType=Full

[Surface]
Roughness=Smooth
AirTemp=-5.0
PackHeight=122
LayerDown=0
PlotDown=0

[Penetration]
Ski= 25
Foot= 80

[Wind]
Speed=Moderate
Direction=South West

[Sky]
Condition=Broken Clouds

[Ram]
Hardness=

[Precip]
Type=Snow
Rate=Very Light

[SnowTempLayers]
Count=13
SnowColour=16711680
SnowLine=16711680

[SnowHeight]
1=0
2=10
3=20
4=30
5=40
6=50
7=60
8=70
9=80
10=90
11=100
12=112
13=122

[SnowTemp]
1=-1.3
2=-1.6
3=-2.2
4=-2.6
5=-2.9
6=-3.6
7=-4.1
8=-4.7
9=-5.3
10=-6.0
11=-6.4
12=-3.7
13=-0.5

[RamLayers]
RamColour=0
HardnessOnly=0
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1100
HandRamScale=0

[CrystalLayerHeight]
SymbolColour=16711680
1=-1
2=29
3=51
4=60
5=79
6=80
7=90
8=115
9=122

[Comments]
Count=2
1=Large full depth avalnches on nearby slopes with storm on April2-3. Loud and unsettling whumphing observed at pit
2=when foot penetrated DH. Nearby pit RB3 under Hst and RB6 on DH.
Stability=N

[CrystalLLayers]
BottomOfPit=0
Count=9

[CrystalLayerWaterContent]
1=Moist
2=Dry
3=Dry
4=Dry
5=Dry
6=Dry
7=Dry
8=Dry
9=Dry

[CrystalLayerGrainForm1]
1=1
2=5
3=5
4=4c
5=4c
6=9c
7=3
8=3
9=1

[CrystalLayerGrainRimed1]
1=
2=
3=
4=
5=
6=
7=
8=
9=

[CrystalLayerGrainDiameter1]
1=2-3
2=4-6
3=2-4
4=1-2
5=2
6=
7=.5
8=1
9=1-3

[CrystalLayerGrainForm2]
1=
2=
3=
4=
5=
6=4
7=
8=2
9=

[CrystalLayerGrainRimed2]
1=
2=
3=
4=
5=
6=
7=
8=
9=

[CrystalLayerGrainDiameter2]
1=
2=
3=
4=
5=
6=2
7=
8=1
9=

[CrystalLayerHandHardness]
1=N/A
2=4F-
3=4F
4=1F
5=4F+
6=4F
7=1F+
8=1F-
9=F

[CrystalLayerDensity]
1=0
2=200
3=240
4=290
5=240
6=200
7=180
8=170
9=30

[CrystalLayerDensityEstimated]
1=
2=
3=
4=
5=
6=e
7=
8=
9=

[CrystalLayerComments]
1=
2=
3=Fast/clean at 51
4=
5=
6=
7=
8=
9=

[CrystalLayerCommentsPosition]
1=1
2=1
3=1
4=1
5=1
6=1
7=1
8=1
9=1

[CrystalLayerCommentsSlope]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0
9=0

[ShearLayers]
Count=3

[ShearLayerHeight]
1=51
2=79
3=90

[ShearLayerType]
1=Compression
2=Shovel
3=Compression

[ShearLayerValue]
1=M  - Moderate
2=M - Moderate
3=M  - Moderate

[ShearHits]
1=16
2=0
3=12

[ShearLayerComments]
1=Much cleaner shear than in previous pits
2=No result in CT
3=STE

[ShearLayerCommentsPosition]
1=3
2=3
3=3
