[File]
Release=3.0

[Id]
Location=Goat's Eye Plot
Title1=Parks Canada
Title2=Banff/Yoho/Kootenay
Date=
Time=13:40
Observer=BW AH
Altitude=2130
AltUnits=
Coords=      ,
Aspect=8
Slope=0
ProfileNbr=3
ProfileType=Full

[Surface]
Roughness=Smooth
AirTemp=-4.5
PackHeight=62
LayerDown=0
PlotDown=0

[Penetration]
Ski=
Foot= 50

[Wind]
Speed=Light
Direction=North

[Sky]
Condition=Clear

[Ram]
Hardness=

[Precip]
Type=Nil
Rate=

[SnowTempLayers]
Count=7
SnowColour=16711680
SnowLine=16711680

[SnowHeight]
1=0
2=10
3=20
4=30
5=40
6=52
7=62

[SnowTemp]
1=-2.6
2=-3.3
3=-4.6
4=-7.7
5=-9.0
6=-8.5
7=-3.2

[RamLayers]
RamColour=0
HardnessOnly=0
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1100
HandRamScale=0

[CrystalLayerHeight]
SymbolColour=16711680
1=-1
2=13
3=30
4=45
5=56
6=62

[Comments]
Count=1
1=Mid-pack FC'ing with clear cool nights. Dec 27 layer very difficult to find SH.
Stability=N

[CrystalLLayers]
BottomOfPit=0
Count=6

[CrystalLayerWaterContent]
1=Dry
2=Dry
3=Dry
4=Dry
5=Dry
6=Dry

[CrystalLayerGrainForm1]
1=1
2=9
3=5b
4=4
5=4
6=2

[CrystalLayerGrainRimed1]
1=
2=
3=
4=
5=
6=

[CrystalLayerGrainDiameter1]
1=2-4
2=
3=6
4=2
5=1.5
6=1

[CrystalLayerGrainForm2]
1=
2=
3=
4=
5=
6=

[CrystalLayerGrainRimed2]
1=
2=
3=
4=
5=
6=

[CrystalLayerGrainDiameter2]
1=
2=
3=
4=
5=
6=

[CrystalLayerHandHardness]
1=N/A
2=P
3=4F
4=1F
5=4F+
6=F

[CrystalLayerDensity]
1=0
2=260
3=180
4=200
5=190
6=90

[CrystalLayerDensityEstimated]
1=
2=
3=
4=
5=
6=

[CrystalLayerComments]
1=stellars
2=
3=
4=Dec 27 @ 45. Some old SH.
5=
6=

[CrystalLayerCommentsPosition]
1=1
2=3
3=1
4=1
5=1
6=1

[CrystalLayerCommentsSlope]
1=0
2=0
3=0
4=0
5=0
6=0

[ShearLayers]
Count=2

[ShearLayerHeight]
1=30
2=45

[ShearLayerType]
1=Compression
2=Compression

[ShearLayerValue]
1=M  - Moderate
2=M  - Moderate

[ShearHits]
1=20
2=18

[ShearLayerComments]
1=X 2 Collapse
2=X 2

[ShearLayerCommentsPosition]
1=3
2=3
