[File]
Release=3.0

[Id]
Location=Goat's Eye Plot
Title1=Parks Canada
Title2=Banff/Yoho/Kootenay
Date=2/9/01
Time=14:15
Observer=MH
Altitude=
AltUnits=
Coords=      ,
Aspect=8
Slope=0
ProfileNbr=4
ProfileType=Full

[Surface]
Roughness=Smooth
AirTemp=-8.5
PackHeight=78
LayerDown=0
PlotDown=0

[Penetration]
Ski=
Foot= 60

[Wind]
Speed=Light
Direction=South West

[Sky]
Condition=Scattered Clouds

[Ram]
Hardness=

[Precip]
Type=Nil
Rate=

[SnowTempLayers]
Count=8
SnowColour=16711680
SnowLine=16711680

[SnowHeight]
1=0
2=10
3=20
4=30
5=40
6=60
7=68
8=78

[SnowTemp]
1=-1.0
2=-3.0
3=-5.5
4=-7.0
5=-12.0
6=-15.0
7=-15.0
8=-12.0

[RamLayers]
RamColour=16711680
HardnessOnly=0
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1100
HandRamScale=0

[CrystalLayerHeight]
SymbolColour=16711680
1=-1
2=10
3=30
4=38
5=45
6=60
7=71
8=78

[Comments]
Count=1
1=Profile Goats Eye - SH layer at 45 reactive. Some mid pack strength. No densities today.
Stability=U

[CrystalLLayers]
BottomOfPit=0
Count=8

[CrystalLayerWaterContent]
1=Dry
2=Dry
3=Dry
4=Dry
5=Dry
6=Dry
7=Dry
8=Dry

[CrystalLayerGrainForm1]
1=2
2=5
3=5
4=4
5=4
6=4
7=4
8=4

[CrystalLayerGrainRimed1]
1=
2=
3=
4=
5=
6=
7=
8=

[CrystalLayerGrainDiameter1]
1=1
2=4-6
3=6
4=2
5=3
6=2
7=1
8=.5

[CrystalLayerGrainForm2]
1=4
2=
3=
4=
5=7
6=
7=2
8=

[CrystalLayerGrainRimed2]
1=
2=
3=
4=
5=
6=
7=
8=

[CrystalLayerGrainDiameter2]
1=.5
2=
3=
4=
5=3
6=
7=1
8=

[CrystalLayerHandHardness]
1=N/A
2=1F
3=4F
4=P-
5=1F
6=4F
7=4F
8=F

[CrystalLayerDensity]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0

[CrystalLayerDensityEstimated]
1=
2=
3=
4=
5=
6=
7=
8=

[CrystalLayerComments]
1=
2=
3=
4=
5=SH flat plates
6=
7=
8=

[CrystalLayerCommentsPosition]
1=1
2=1
3=1
4=1
5=1
6=1
7=1
8=1

[CrystalLayerCommentsSlope]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0

[ShearLayers]
Count=2

[ShearLayerHeight]
1=10
2=45

[ShearLayerType]
1=Shovel
2=Compression

[ShearLayerValue]
1=E - Easy
2=E  - Easy

[ShearHits]
1=0
2=5

[ShearLayerComments]
1=
2=

[ShearLayerCommentsPosition]
1=3
2=3
