[File]
Release=3.0

[Id]
Location=Gaots Eye Plot
Title1=Parks Canada
Title2=Banff-Yoho-Kootenay
Date=3/8/01
Time=13:20
Observer=AH,MH
Altitude=
AltUnits=
Coords=      ,
Aspect=8
Slope=0
ProfileNbr=?
ProfileType=Full

[Surface]
Roughness=Smooth
AirTemp=5.8
PackHeight=82
LayerDown=0
PlotDown=0

[Penetration]
Ski=
Foot= 60

[Wind]
Speed=Light
Direction=South West

[Sky]
Condition=Scattered Clouds

[Ram]
Hardness=

[Precip]
Type=Nil
Rate=

[SnowTempLayers]
Count=9
SnowColour=16711680
SnowLine=16711680

[SnowHeight]
1=0
2=10
3=20
4=30
5=40
6=50
7=60
8=72
9=82

[SnowTemp]
1=-1.7
2=-2.8
3=-3.5
4=-4.0
5=-4.6
6=-5.7
7=-6.8
8=-5.2
9=-0.3

[RamLayers]
RamColour=0
HardnessOnly=0
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1100
HandRamScale=0

[CrystalLayerHeight]
SymbolColour=16711680
1=-1
2=51
3=63
4=71
5=80
6=81
7=82

[CrystalLLayers]
BottomOfPit=0
Count=7

[CrystalLayerWaterContent]
1=Moist
2=Dry
3=Dry
4=Moist
5=Moist
6=Moist
7=Moist

[CrystalLayerGrainForm1]
1=7
2=5
3=4
4=4
5=4
6=9e
7=7

[CrystalLayerGrainRimed1]
1=
2=
3=
4=
5=
6=
7=

[CrystalLayerGrainDiameter1]
1=1
2=2-6
3=1.5
4=.5
5=.5-1
6=
7=1

[CrystalLayerGrainForm2]
1=2
2=
3=
4=
5=
6=
7=2

[CrystalLayerGrainRimed2]
1=
2=
3=
4=
5=
6=
7=

[CrystalLayerGrainDiameter2]
1=1.5
2=
3=
4=
5=
6=
7=1.5

[CrystalLayerHandHardness]
1=N/A
2=F
3=4F
4=1F+
5=4F-
6=P+
7=F

[CrystalLayerDensity]
1=0
2=330
3=330
4=390
5=240
6=240
7=240

[CrystalLayerDensityEstimated]
1=
2=
3=
4=
5=
6=e
7=e

[CrystalLayerComments]
1=
2=
3=
4=
5=
6=
7=

[CrystalLayerCommentsPosition]
1=1
2=1
3=1
4=1
5=1
6=1
7=1

[CrystalLayerCommentsSlope]
1=0
2=0
3=0
4=0
5=0
6=0
7=0

[Comments]
Stability=N

[ShearLayers]
Count=2

[ShearLayerHeight]
1=51
2=71

[ShearLayerType]
1=Shovel
2=Compression

[ShearLayerValue]
1=H - Hard
2=M  - Moderate

[ShearHits]
1=0
2=7

[ShearLayerComments]
1=V&FC
2=on V

[ShearLayerCommentsPosition]
1=3
2=3
