[File]
Release=3.0

[Id]
Location=Goat's Eye Plot
Title1=Parks Canada
Title2=Banff-Yoho-Kootenay
Date=
Time=11:00
Observer=Brad White
Altitude=2316
AltUnits=
Coords=      ,
Aspect=8
Slope=0
ProfileNbr=GE
ProfileType=Full

[Surface]
Roughness=
AirTemp=-5.8
PackHeight=96
LayerDown=0
PlotDown=0

[Penetration]
Ski=
Foot=

[Wind]
Speed=Moderate
Direction=West

[Sky]
Condition=Broken Clouds

[Ram]
Hardness=

[Precip]
Type=Nil
Rate=

[SnowTempLayers]
Count=11
SnowColour=16711680
SnowLine=16711680

[SnowHeight]
1=0
2=10
3=20
4=30
5=40
6=50
7=60
8=70
9=80
10=86
11=96

[SnowTemp]
1=-1.9
2=-2.0
3=-2.5
4=-3.2
5=-3.6
6=-4.7
7=-5.4
8=-6.8
9=-8.1
10=-8.8
11=-8.3

[RamLayers]
RamColour=0
HardnessOnly=0
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1100
HandRamScale=0

[CrystalLayerHeight]
SymbolColour=16711680
1=-1
2=32
3=57
4=74
5=75
6=82
7=96

[CrystalLLayers]
BottomOfPit=0
Count=7

[CrystalLayerWaterContent]
1=Dry
2=Dry
3=Dry
4=Dry
5=Dry
6=Dry
7=Dry

[CrystalLayerGrainForm1]
1=2
2=5
3=5
4=4c
5=7
6=4c
7=2

[CrystalLayerGrainRimed1]
1=
2=
3=
4=
5=
6=
7=

[CrystalLayerGrainDiameter1]
1=1
2=6-12
3=6
4=1
5=3
6=1
7=1

[CrystalLayerGrainForm2]
1=
2=
3=
4=
5=4
6=
7=

[CrystalLayerGrainRimed2]
1=
2=
3=
4=
5=
6=
7=

[CrystalLayerGrainDiameter2]
1=
2=
3=
4=
5=2-3
6=
7=

[CrystalLayerHandHardness]
1=N/A
2=4F
3=4F+
4=P
5=4F
6=P
7=1F

[CrystalLayerDensity]
1=0
2=220
3=230
4=270
5=0
6=230
7=160

[CrystalLayerDensityEstimated]
1=
2=
3=
4=
5=
6=
7=

[CrystalLayerComments]
1=
2=
3=Sintered
4=
5=
6=
7=

[CrystalLayerCommentsPosition]
1=1
2=1
3=1
4=1
5=1
6=1
7=1

[CrystalLayerCommentsSlope]
1=0
2=0
3=0
4=0
5=0
6=0
7=0

[Comments]
Stability=N

[ShearLayers]
Count=2

[ShearLayerHeight]
1=75
2=80

[ShearLayerType]
1=Shovel
2=Shovel

[ShearLayerValue]
1=E - Easy
2=E - Easy

[ShearHits]
1=0
2=0

[ShearLayerComments]
1=also CTE8 X 2
2=also CTM

[ShearLayerCommentsPosition]
1=3
2=3
