[PopupMenu]
Showlayerslope=0
ShearHideAllComments=0
LayersHideAllComments=0
RamHideAllLayers=0
SnowTempHideAllLayers=0
ShearStress=0
HardnessType=0

[File]
Release=3.0

[Id]
Location=Goat's Eye Plot
Title1=Parks Canada
Title2=Banff-Yoho-Kootenay
Date=2002/03/20
Time=12:20
Observer=AH
Altitude=
AltUnits=Metres
Coords=      ,
Aspect=8
Slope=0
ProfileNbr=GE020320
ProfileType=Full

[Surface]
Roughness=Smooth
AirTemp=-21.0
PackHeight=181
LayerDown=0
PlotDown=0

[Penetration]
Ski=
Foot= 25

[Wind]
Speed=Light
Direction=East

[Sky]
Condition=Scattered Clouds

[Ram]
Hardness=

[Precip]
Type=Nil
Rate=

[SnowTempLayers]
MinTemperatureScale=-22
Count=19
SnowColour=16711680
SnowLine=16711680

[SnowHeight]
1=0
2=10
3=20
4=30
5=40
6=50
7=60
8=70
9=80
10=90
11=100
12=110
13=120
14=130
15=140
16=150
17=160
18=170
19=181

[SnowTemp]
1=-1.2
2=-1.8
3=-2.4
4=-2.9
5=-3.7
6=-4.2
7=-4.3
8=-5.0
9=-5.7
10=-6.4
11=-7.0
12=-7.8
13=-8.4
14=-9.7
15=-11.5
16=-12.7
17=-15.6
18=-20.0
19=-18.5

[RamLayers]
RamColour=0
HardnessOnly=0
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1100
HandRamScale=0

[CrystalLayerHeight]
SymbolColour=16711680
1=-1
2=20
3=37
4=38
5=77
6=80
7=90
8=113
9=139
10=154
11=181

[CrystalLLayers]
BottomOfPit=0
Count=11

[CrystalLayerWaterContent]
1=Dry
2=Dry
3=Dry
4=Dry
5=Dry
6=Dry
7=Dry
8=Dry
9=Dry
10=Dry
11=Dry

[CrystalLayerGrainForm1]
1=2
2=5
3=5
4=9
5=3
6=3
7=3
8=3
9=3
10=3
11=3

[CrystalLayerGrainRimed1]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=

[CrystalLayerGrainDiameter1]
1=.25
2=2-3
3=3
4=
5=2
6=1-2
7=1-2
8=1
9=.5
10=.5
11=.5

[CrystalLayerGrainForm2]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=2

[CrystalLayerGrainRimed2]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=

[CrystalLayerGrainDiameter2]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=1

[CrystalLayerHandHardness]
1=N/A
2=1F
3=4F
4=P
5=4F+
6=1F-
7=1F
8=P
9=1F+
10=1F
11=F

[CrystalLayerDensity]
1=0
2=280
3=295
4=0
5=310
6=280
7=320
8=300
9=220
10=210
11=140

[CrystalLayerDensityEstimated]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=

[CrystalLayerComments]
1=
2=
3=Rounding
4=
5=
6=Hard shear
7=
8=
9=
10=
11=Some facets .25

[CrystalLayerCommentsPosition]
1=1
2=1
3=1
4=1
5=1
6=1
7=1
8=1
9=1
10=1
11=1

[CrystalLayerCommentsSlope]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0
9=0
10=0
11=0

[Comments]
Stability=N

[ShearLayers]
Count=3

[ShearLayerHeight]
1=38
2=155
3=167

[ShearLayerType]
1=Compression
2=Compression
3=Compression

[ShearLayerValue]
1=H  - Hard
2=M  - Moderate
3=M  - Moderate

[ShearHits]
1=24
2=19
3=6

[ShearLayerComments]
1=
2=
3=

[ShearLayerCommentsPosition]
1=3
2=3
3=3
