[PopupMenu]
Showlayerslope=0
ShearHideAllComments=0
LayersHideAllComments=0
RamHideAllLayers=0
SnowTempHideAllLayers=0
ShearStress=0
HardnessType=0

[File]
Release=3.0

[Id]
Location=Goat's Eye Plot
Title1=Parks Canada
Title2=Banff-Yoho-Kootenay
Date=2002/02/06
Time=10:50
Observer=AH ML
Altitude=
AltUnits=Metres
Coords=      ,
Aspect=5
Slope=0
ProfileNbr=GE020206
ProfileType=Full

[Surface]
Roughness=Smooth
AirTemp=-7.3
PackHeight=144
LayerDown=0
PlotDown=0

[Penetration]
Ski=
Foot= 30

[Wind]
Speed=Light
Direction=West

[Sky]
Condition=Overcast

[Ram]
Hardness=

[Precip]
Type=Snow
Rate=Very Light

[SnowTempLayers]
MinTemperatureScale=-22
Count=12
SnowColour=16711680
SnowLine=16711680

[SnowHeight]
1=0
2=10
3=20
4=30
5=70
6=80
7=90
8=100
9=110
10=120
11=134
12=144

[SnowTemp]
1=-0.9
2=-1.3
3=-1.1
4=-2.2
5=-4.7
6=-5.3
7=-6.1
8=-6.2
9=-7.2
10=-7.3
11=-8.2
12=-8.2

[RamLayers]
RamColour=0
HardnessOnly=0
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1100
HandRamScale=0

[CrystalLayerHeight]
SymbolColour=16711680
1=-1
2=40
3=41
4=84
5=87
6=97
7=100
8=106
9=118
10=133
11=144

[CrystalLLayers]
BottomOfPit=0
Count=11

[CrystalLayerWaterContent]
1=Dry
2=Dry
3=Dry
4=Dry
5=Dry
6=Dry
7=Dry
8=Dry
9=Dry
10=Dry
11=Dry

[CrystalLayerGrainForm1]
1=1
2=4
3=9
4=4
5=4
6=4c
7=3
8=3
9=3
10=3
11=2

[CrystalLayerGrainRimed1]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=

[CrystalLayerGrainDiameter1]
1=2-3
2=2-3
3=
4=2
5=1
6=1
7=1
8=.5-1
9=.5
10=.5-1
11=2

[CrystalLayerGrainForm2]
1=2
2=
3=
4=
5=7
6=
7=
8=
9=
10=
11=

[CrystalLayerGrainRimed2]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=

[CrystalLayerGrainDiameter2]
1=2-3
2=
3=
4=
5=2-3
6=
7=
8=
9=
10=
11=

[CrystalLayerHandHardness]
1=N/A
2=4F
3=K
4=4F
5=1F
6=4F+
7=4F
8=1F
9=4F+
10=4F
11=F

[CrystalLayerDensity]
1=0
2=370
3=0
4=270
5=0
6=280
7=0
8=290
9=230
10=170
11=80

[CrystalLayerDensityEstimated]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=

[CrystalLayerComments]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=

[CrystalLayerCommentsPosition]
1=1
2=1
3=1
4=1
5=1
6=1
7=1
8=1
9=1
10=1
11=1

[CrystalLayerCommentsSlope]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0
9=0
10=0
11=0

[Comments]
Stability=N

[ShearLayers]
Count=1

[ShearLayerHeight]
1=97

[ShearLayerType]
1=Compression

[ShearLayerValue]
1=H  - Hard

[ShearHits]
1=26

[ShearLayerComments]
1=

[ShearLayerCommentsPosition]
1=3
