[PopupMenu]
Showlayerslope=0
ShearHideAllComments=0
LayersHideAllComments=0
RamHideAllLayers=0
SnowTempHideAllLayers=0
ShearStress=0
HardnessType=0

[File]
Release=3.0

[Id]
Location=Goat's Eye Plot
Title1=Parks Canada
Title2=Banff-Kootenay-Yoho
Date=
Time=11:50
Observer=BW
Altitude=
AltUnits=Metres
Coords=      ,
Aspect=5
Slope=0
ProfileNbr=01
ProfileType=Full

[Surface]
Roughness=Smooth
AirTemp=-8.5
PackHeight=141
LayerDown=0
PlotDown=0

[Penetration]
Ski= 20
Foot= 30

[Wind]
Speed=Light
Direction=N/A

[Sky]
Condition=Overcast

[Ram]
Hardness=

[Precip]
Type=Snow
Rate=Very Light

[SnowTempLayers]
MinTemperatureScale=-11
Count=2
SnowColour=16711680
SnowLine=16711680

[SnowHeight]
1=0
2=141

[SnowTemp]
1=-2.0
2=-14.1

[RamLayers]
RamColour=0
HardnessOnly=0
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1100
HandRamScale=0

[CrystalLayerHeight]
SymbolColour=16711680
1=-1
2=22
3=39
4=40
5=50
6=58
7=71
8=80
9=94
10=97
11=107
12=119
13=141

[Comments]
Count=1
1=No snowpack temps as battery died in thermo.Estimated ground temp.
Stability=N

[CrystalLLayers]
BottomOfPit=0
Count=13

[CrystalLayerWaterContent]
1=Dry
2=Dry
3=Dry
4=Dry
5=Dry
6=Dry
7=Dry
8=Dry
9=Dry
10=Dry
11=Dry
12=Dry
13=Dry

[CrystalLayerGrainForm1]
1=1
2=5
3=4
4=9e
5=4
6=4
7=4
8=4
9=4c
10=4c
11=3
12=2
13=2

[CrystalLayerGrainRimed1]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=

[CrystalLayerGrainDiameter1]
1=1.0
2=2-5
3=2-4
4=
5=2-3
6=2
7=1.5
8=1.5
9=1
10=1
11=.5
12=1
13=1

[CrystalLayerGrainForm2]
1=
2=4
3=5
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=

[CrystalLayerGrainRimed2]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=

[CrystalLayerGrainDiameter2]
1=
2=2-5
3=2-4
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=

[CrystalLayerHandHardness]
1=N/A
2=P-
3=1F+
4=K-
5=1F-
6=P-
7=P
8=P
9=1F+
10=1F
11=P
12=1F-
13=F+

[CrystalLayerDensity]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0
9=0
10=0
11=0
12=0
13=0

[CrystalLayerDensityEstimated]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=

[CrystalLayerComments]
1=
2=Sintered
3=loose FC grains above and below crust
4=Crust still intact grey ice
5=CTH 26 Clean 10cm above crust
6=
7=
8=
9=CTM 16 @ 94 some SH flakes to size 3 Clean shear.
10=
11=CTM 12 @ 107
12=Tilt & CTE6 @ 119 on DF
13=Tilt & CTE3 @ 130 on DF

[CrystalLayerCommentsPosition]
1=1
2=1
3=1
4=1
5=1
6=1
7=1
8=1
9=1
10=1
11=1
12=1
13=1

[CrystalLayerCommentsSlope]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0
9=0
10=0
11=0
12=0
13=0
