[File]
Release=3.0

[Id]
Location=vermilion plot
Date=3/8/00
Time=12:30
Observer=ml, ghi,mh
Altitude=
AltUnits=
Coords=      ,
Aspect=8
Slope=0
ProfileNbr=20304
ProfileType=full

[Surface]
Roughness=Smooth
AirTemp=-3.9
PackHeight=213
LayerDown=0

[Penetration]
Ski= 20
Foot= 40

[Wind]
Speed=Calm
Direction=N/A

[Sky]
Condition=Overcast

[Ram]
Hardness=

[Precip]
Type=Snow
Rate=Very Light

[SnowTempLayers]
Count=15
SnowColour=16711680
SnowLine=16711680

[SnowHeight]
1=0
2=20
3=40
4=60
5=80
6=100
7=120
8=140
9=150
10=160
11=170
12=180
13=190
14=200
15=203

[SnowTemp]
1=-0.5
2=-1.1
3=-1.6
4=-1.9
5=-2.4
6=-2.7
7=-2.1
8=-3.4
9=-3.6
10=-3.8
11=-3.7
12=-4.3
13=-4.9
14=-4.0
15=-3.6

[RamLayers]
RamColour=0
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1100
HandRamScale=0

[CrystalLayerHeight]
SymbolColour=16711680
1=-1
2=19
3=52
4=56
5=60
6=96
7=98
8=128
9=129
10=165
11=166
12=183
13=193
14=210
15=213

[CrystalLLayers]
BottomOfPit=0
Count=15

[CrystalLayerWaterContent]
1=Dry
2=Dry
3=Dry
4=Dry
5=Dry
6=Dry
7=Dry
8=Dry
9=Dry
10=Dry
11=Dry
12=Dry
13=Dry
14=Dry
15=Dry

[CrystalLayerGrainForm1]
1=1
2=4
3=4
4=8
5=4
6=3
7=8
8=3
9=3
10=3
11=7
12=3
13=3
14=2
15=2

[CrystalLayerGrainRimed1]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=
14=
15=

[CrystalLayerGrainDiameter1]
1=3-5
2=3
3=2
4=
5=3
6=1.5
7=
8=.5
9=1
10=1
11=3
12=.5
13=.5
14=1
15=1

[CrystalLayerGrainForm2]
1=
2=
3=
4=
5=
6=
7=7
8=
9=7
10=
11=
12=
13=
14=3
15=

[CrystalLayerGrainRimed2]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=
14=
15=

[CrystalLayerGrainDiameter2]
1=
2=
3=
4=
5=
6=
7=8
8=
9=
10=
11=
12=
13=
14=.5
15=

[CrystalLayerHandHardness]
1=N/A
2=P
3=P
4=K
5=1F
6=P
7=4F
8=P
9=1F
10=P
11=4F
12=1F
13=4F+
14=4F
15=F

[CrystalLayerDensity]
1=0
2=410
3=390
4=0
5=330
6=350
7=0
8=340
9=0
10=240
11=0
12=200
13=120
14=110
15=100

[CrystalLayerDensityEstimated]
1=
2=
3=
4=
5=
6=
7=
8=
9=
10=
11=
12=
13=
14=
15=

[CrystalLayerComments]
1=
2=
3=
4=
5=
6=
7=
8=CTH15 @ 98  Y2K V
9=
10=
11=
12=CTH5 @ 166 on broken down V, 3 (Feb 22)
13=CTM6 @ 183
14=, CTE5 @ 200
15=

[CrystalLayerCommentsPosition]
1=1
2=1
3=1
4=1
5=1
6=1
7=1
8=1
9=1
10=1
11=1
12=1
13=1
14=1
15=1

[CrystalLayerCommentsSlope]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0
9=0
10=0
11=0
12=0
13=0
14=0
15=0

[Comments]
Stability=N
