[File]
Release=3.0

[Id]
Location=Bow Summit
Date=2000/01/13
Time=12:30
Observer=ML
Altitude=2030
AltUnits=Metres
Coords=      ,
Aspect=8
Slope=0
ProfileNbr=20205
ProfileType=Full

[Surface]
Roughness=
AirTemp=-12.0
PackHeight=102
LayerDown=0

[Penetration]
Ski=
Foot=

[Wind]
Speed=Light
Direction=South West

[Sky]
Condition=Overcast

[Ram]
Hardness=

[Precip]
Type=Snow
Rate=Very Light

[SnowTempLayers]
Count=11
SnowColour=16711680
SnowLine=16711680

[SnowHeight]
1=0
2=10
3=20
4=30
5=40
6=50
7=60
8=70
9=80
10=90
11=102

[SnowTemp]
1=-0.8
2=-1.6
3=-2.3
4=-3.0
5=-4.0
6=-4.8
7=-6.7
8=-8.8
9=-10.3
10=-11.4
11=-12.1

[RamLayers]
RamColour=16711680
Type=0
HammerWeight=0
Hardness=
MaxRamScale=1100
HandRamScale=0

[CrystalLayerHeight]
SymbolColour=16711680
1=-1
2=13
3=46
4=50
5=61
6=87
7=89
8=93
9=102

[CrystalLLayers]
BottomOfPit=0
Count=9

[CrystalLayerWaterContent]
1=Dry
2=Dry
3=Dry
4=Dry
5=Dry
6=Dry
7=Dry
8=Dry
9=Dry

[CrystalLayerGrainForm1]
1=1
2=4
3=9
4=4
5=4
6=3
7=7
8=3
9=3

[CrystalLayerGrainRimed1]
1=
2=
3=
4=
5=
6=
7=
8=
9=

[CrystalLayerGrainDiameter1]
1=1
2=3
3=
4=2
5=1
6=1
7=10-20
8=.25
9=.5

[CrystalLayerGrainForm2]
1=
2=
3=
4=
5=
6=
7=
8=
9=

[CrystalLayerGrainRimed2]
1=
2=
3=
4=
5=
6=
7=
8=
9=

[CrystalLayerGrainDiameter2]
1=
2=
3=
4=
5=
6=
7=
8=
9=

[CrystalLayerHandHardness]
1=N/A
2=P
3=P
4=4F
5=1F
6=4F
7=F
8=4F
9=F

[CrystalLayerDensity]
1=0
2=350
3=280
4=250
5=260
6=230
7=0
8=160
9=110

[CrystalLayerDensityEstimated]
1=
2=
3=
4=
5=
6=
7=
8=
9=

[CrystalLayerComments]
1=
2=
3=November crust laminated with 4F facets
4=
5=
6=
7=
8=
9=

[CrystalLayerCommentsPosition]
1=1
2=1
3=1
4=1
5=1
6=1
7=1
8=1
9=1

[CrystalLayerCommentsSlope]
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0
9=0

[Comments]
Stability=N

[ShearLayers]
Count=2

[ShearLayerHeight]
1=46
2=89

[ShearLayerType]
1=Compression
2=Compression

[ShearLayerValue]
1=Compression
2=Compression

[ShearHits]
1=8
2=2

[ShearLayerComments]
1=Also STH
2=Also SVE and Burp VE

[ShearLayerCommentsPosition]
1=1
2=1
