[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Vermillion"
.
98-01-28
11:30
"GHI/TA"
2100
M
.
SW
0
98302
Full
a
26
12
2
6
2
.
0
0
-4
154
0
[TEMPERATURES:no]
12
[temp_hgt,temp]
0,-0.5
30,-1.8
50,-2.6
70,-3.3
80,-3.6
90,-3.9
100,-3.9
110,-4.5
120,-5.1
130,-5.9
140,-6.5
150,-5.8
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
.
2
 ,""
0
[LAYERS:no]
11
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
032, ,5 , ,  , ,4      ,1,300, ,"",1
035, ,4 , ,8 , ,3      ,3,   , ,"ste after column cut",1
054, ,4 , ,  , ,2      ,2,320, ,"",1
057, ,4 , ,  , ,1.5    ,3,320, ,"",1
078, ,3 , ,  , ,.5-1   ,3,320, ,"",1
102, ,3 , ,  , ,.5     ,3,310, ,"",1
118, ,3 , ,  , ,.5     ,2,280, ,"",1
123, ,3 , ,  , ,.5-1   ,2,240, ,"",1
137, ,2 , ,3 , ,1      ,1,180, ,"",1
140, ,2 , ,  , ,1      ,1,110, ,"burp2 @ 140 stm@140",1
154, ,2 , ,  , ,1      ,0,130, ,"",1
[SHEARS:no]
0
[shr_hgt,shr_test,shr_rslt,comment]
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"2x shovel test inconclusive sue to overall strenght of column in midpack.  Weakness at 35 went ste only after entire column had been cut."
