[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"South of Rock Isle Lake"
.
98-01-18
13:45
"DV"
2300
M
.
NE
25
98516
Test
a
60
18
2
5
3
.
0
0
-6.0
110
0
[TEMPERATURES:no]
5
[temp_hgt,temp]
0,-1.0
30,-3.0
60,-5.0
90,-6.0
100,-6.0
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1 r
7  
2
 ,"Some sz 8 crystals"
0
[LAYERS:no]
6
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
031, ,5 , ,  , ,2 - 8  ,1,   , ,"",1
053, ,3 , ,4 , ,1      ,2,   , ,"",1
073, ,3 , ,  , ,0.5    ,2,   , ,"",1
092, ,3 , ,  , ,0.5    ,1,   , ,"",1
099, ,2 ,r,  , ,1      ,0,   , ,"",1
110, ,1 ,r,  , ,1      ,0,   , ,"",1
[SHEARS:no]
3
[shr_hgt,shr_test,shr_rslt,comment]
031,O, ,"CE"
073,S,H,""
092,O,C,"E  Note 1"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"Note 1: Some well preserved new snow crystals @ 92, layer interface."
