[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Vermillion"
.
98-01-13
12:00
"GHI/AM/KS"
2100
M
.
SW
0
98301
Full
a
38
25
1
0
4
.
1
1
-14
153
0
[TEMPERATURES:no]
16
[temp_hgt,temp]
0,-1.2
10,-1.9
20,-1.6
30,-2.1
40,-2.6
50,-3.3
60,-4.0
70,-4.5
80,-6.1
90,-7.8
100,-10.1
110,-12.5
120,-15.7
130,-17.7
140,-17.7
153,-17.6
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
.
1
 ,"rimed"
0
[LAYERS:no]
6
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
037, ,4 , ,5 , ,2      ,1,250, ,"",1
040, ,5 , ,  , ,2 - 4  ,3,   , ,"cth sth on top of crust",1
060, ,4 , ,  , ,1      ,2,270, ,"",1
105, ,3 , ,  , ,.5     ,2,230, ,"",1
127, ,2 , ,  , ,.5     ,1,170, ,"",1
153, ,2 , ,  , ,.5 - 1 ,0,110, ,"cte at 10 stm at 15",1
[SHEARS:no]
0
[shr_hgt,shr_test,shr_rslt,comment]
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
