[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Bow Summit Ski Hill"
.
97-12-08
11:30
"ML BW TA RB DV PW"
2300
M
.
E
20
98505
Fracture Line
a
.
.
2
7
1
.
0
0
-5
53
0
[TEMPERATURES:no]
7
[temp_hgt,temp]
0,-1.6
10,-2.9
20,-4.2
30,-6.6
40,-9.0
43,-10.0
53,-6.1
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
7  
   
1
0,""
0
[LAYERS:no]
4
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
016,0,5 , ,4 , ,2      ,1,   , ,"",1
020,0,4 , ,  , ,2      ,2,   , ,"Note 1 @ 18",1
045,0,4 , ,  , ,1      ,2,   , ,"",1
053,0,4 , ,  , ,.5     ,0,   , ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
000,S,M,"Collapse"
045,S,M,"Compression"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"  Note 1: RB 4 @ 18, 20 degree slope; CTH4 @ 18 ; Nov. 19 crust"
""
""
""
""
""
""
