[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Bow Summit"
.
97-12-03
14:30
"GI    RB"
2030
M
.
.
0
98201
Full
a
.
.
1
0
1
.
0
0
-8.0
46
0
[TEMPERATURES:no]
6
[temp_hgt,temp]
0,-0.9
10,-2.6
20,-5.2
30,-9.6
36,-12.5
46,-8.0
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
.
.
.
 ,""
0
[LAYERS:no]
6
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
011, ,5 , ,  , ,2-4    ,1,240, ,"",1
012, ,8 , ,  , ,       ,2,   , ,"",1
017, ,5 , ,  , ,2-3    ,0,160, ,"",1
035, ,2 , ,  , ,1      ,1,160, ,"",1
045, ,2 , ,  , ,.5-1   ,0,110, ,"",1
046, ,7 , ,  , ,2-3    ,0,   , ,"",1
[SHEARS:no]
1
[shr_hgt,shr_test,shr_rslt,comment]
010,S,M,"below MF on FC's"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
