[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Bow Summit Ski Hill"
.
98-01-03
13:00
"JO   RB"
7600
F
.
E
38
98510
Fracture Line
a
.
.
2
4
4
.
1
1
.
97
0
[TEMPERATURES:no]
0
[temp_hgt,temp]
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
.
.
.
 ,""
0
[LAYERS:no]
7
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
024, ,4 , ,5 , ,2-3    ,0,   , ,"",1
035, ,4 , ,  , ,1.5-2  ,1,   , ,"",1
049, ,4 , ,  , ,1      ,2,   , ,"",1
053, ,2 , ,1d, ,1-1.5  ,1,   , ,"sd's from start of storm",1
073, ,2 , ,3 , ,.5     ,1,   , ,"",1
087, ,2 , ,  , ,.5     ,2,   , ,"",1
097, ,2 , ,  , ,.5     ,3,   , ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
053,S,E,"stellars of storm start"
087,S,V,"storm snow slab"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"2 x size 2 remote triggered from 25 and 75 m away while observers entered test area"
