[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"bow summit"
.
97-12-17
10:45
"GHI/BW"
2145
M
.
NA
0
98202
Full
a
60
.
1
0
3
.
1
1
-3
64
0
[TEMPERATURES:no]
8
[temp_hgt,temp]
0,-1.0
10,-1.3
20,-2.1
30,-2.7
40,-3.5
50,-4.0
54,-4.1
64,-4.2
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
.
.
.
 ,""
0
[LAYERS:no]
8
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
011,0,5 , ,  , ,4      ,2,230, ,"",1
013,0,5 , ,  , ,6      ,3,230,e,"old crust",1
019,0,5 , ,  , ,6      ,2,170, ,"burp mod ",1
037,0,3 , ,4 , ,1.5    ,1,200, ,"ct easy below V burp Mod",1
038,0,7 , ,4 , ,1-4    ,0,   , ,"V very long needle shape",1
049,0,3 , ,  , ,1      ,1,110, ,"ct easy burp mod",1
061,0,2 , ,  , ,1.5    ,0,070, ,"",1
064,0,1 , ,  , ,2      ,0,090, ,"",1
[SHEARS:no]
0
[shr_hgt,shr_test,shr_rslt,comment]
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
