[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Bow Summit"
.
98-01-01
10:30
"JO"
2030
M
.
.
0
98203
Full
.
.
.
2
1
5
.
1
3
-15.0
86
0
[TEMPERATURES:no]
9
[temp_hgt,temp]
0,-1.2
10,-1.3
20,-1.8
30,-2.3
40,-3.0
50,-3.6
60,-4.0
70,-4.2
76,-5.7
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
.
2-3
 ,"rime"
0
[LAYERS:no]
8
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
013, ,5 , ,  , ,3-4    ,0,   , ,"",1
015, ,5 , ,  , ,3-4    ,2,   , ,"old crust deteriorating",1
033, ,4 , ,  , ,2      ,1,   , ,"striations",1
034, ,7 , ,4 , ,1-2    , ,   , ,"some SH pieces",1
051, ,4 , ,3 , ,1      ,2,   , ,"some rounding",1
077, ,2 , ,  , ,1-2    ,0,   , ,"rime",1
083, ,2 , ,  , ,1-2    ,0,   , ,"rime",1
086, ,1 , ,2 , ,2      ,0,   , ,"rime",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
000,S,C,""
051,S,H,""
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"forgot the density kit"
