[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Bow Summit"
.
98-01-29
10:46
"JO   ML   ALH"
2030
M
.
.
0
98206
Full
a
.
.
2
5
3
.
0
0
-8.5
84
0
[TEMPERATURES:no]
10
[temp_hgt,temp]
0,-0.7
10,-1.5
20,-1.7
30,-2.3
40,-2.3
50,-3.4
60,-4.2
70,-5.9
74,-6.6
84,-6.3
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
1 r
1
 ,""
0
[LAYERS:no]
7
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
010, ,4 , ,5 , ,3-4    ,0,210, ,"",1
013, ,4 , ,9e, ,3      ,0,200, ,"conglomerate",1
030, ,4 , ,  , ,2      ,1,280, ,"4F-",1
033, ,4 , ,  , ,1-1.5  ,2,290, ,"1F+. rounding.",1
047, ,3 , ,  , ,.5-1   ,1,280, ,"",1
070, ,3 , ,  , ,.5     ,2,210, ,"",1
084, ,2 , ,  , ,1      ,0,090, ,"",1
[SHEARS:no]
1
[shr_hgt,shr_test,shr_rslt,comment]
000,S,M,""
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
