[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Bow Summit"
.
98-03-26
10:57
"DV, ML"
2030
M
.
NA
0
98209
.
.
.
.
1
0
3
.
1
1
-2.0
108
0
[TEMPERATURES:no]
12
[temp_hgt,temp]
0,-0.7
10,-0.8
20,-0.9
30,-1.1
40,-1.4
50,-1.6
60,-1.9
70,-2.0
80,-2.3
90,-2.6
98,-1.9
108,-0.5
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1 r
.
1.0
0,""
0
[LAYERS:no]
9
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
030,0,5 , ,  , ,3.0-5.0,2,260, ,"",1
034,0,4 , ,  , ,2.0    ,3,   , ,"variable, old crust",1
064,0,4 , ,  , ,2.0    ,2,320, ,"",1
082,0,4 , ,  , ,2.0    ,1,240, ,"",1
090,0,3 , ,  , ,0.5    ,3,200, ,"",1
092,0,9e, ,  , ,       ,4,   , ,"",1
099,0,2 , ,  , ,1.0    ,0,110, ,"",1
101,0,9e, ,  , ,       ,3,   , ,"",1
108,0,2 , ,  , ,1.0    ,0,090, ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
076,S,M,"Compression"
099,S,M,"also mod burp&CTE"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
