[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Bow Summit"
.
98-04-09
12:00
"PW DV"
2030
M
.
.
0
98210
Full
.
.
.
2
6
2
.
0
0
-1.0
90
0
[TEMPERATURES:no]
10
[temp_hgt,temp]
0,0.0
10,-0.5
20,-0.5
30,-0.5
40,-0.5
50,-1.0
60,-1.5
70,-2.5
80,-3.5
90,0.5
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
2  
1f 
1 - 2
 ,""
0
[LAYERS:no]
10
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
009, ,5 , ,  , ,4 - 8  ,2,300, ,"",1
026, ,5 , ,  , ,3 - 9  ,1,300, ,"",1
030, ,4 , ,  , ,2      ,1,300, ,"",1
037, ,4c, ,  , ,1 - 2  ,2,320, ,"",1
047, ,4c, ,  , ,2.0    ,3,360, ,"",1
077, ,4c, ,  , ,1.0    ,2,310, ,"",1
080, ,3 , ,  , ,0.5    ,2,360, ,"",1
081, ,9e, ,  , ,       ,4,360, ,"",1
083, ,3 , ,  , ,0.5    ,3,360, ,"",1
090,0,9e, ,  , ,       ,4,370, ,"",1
[SHEARS:no]
0
[shr_hgt,shr_test,shr_rslt,comment]
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
