[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Bow Summit"
.
98-01-06
12:30
"BW DV"
2030
M
.
NA
0
98204
Full
a
50
30
2
7
4
.
1
1
-8.0
88
0
[TEMPERATURES:no]
9
[temp_hgt,temp]
0,-1.0
10,-1.5
20,-2.0
30,-3.5
40,-4.5
50,-6.0
60,-7.0
70,-6.5
78,-6.0
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
.
1
 ,""
0
[LAYERS:no]
8
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
012,0,5 , ,  , ,4      ,1,220,e,"",1
014,0,5 , ,9e, ,2-4    ,2,240,e,"  Old crust  DH 6mm under",1
032,0,4 , ,  , ,1.5    ,1,230,e,"",1
050,0,4 , ,  , ,1      ,2,220,e,"  Old  V @ 40 No shear",1
055,0,3 , ,9d, ,.3     ,3,240,e,"",1
078,0,2 , ,  , ,1      ,1,180,e,"",1
083,0,1 , ,  , ,1      ,0,120,e,"",1
088,0,1 , ,  , ,1      ,0,110,e,"",1
[SHEARS:no]
3
[shr_hgt,shr_test,shr_rslt,comment]
018,O,C,"ollapse & ST M"
032,O,C,"TH"
078,O, ,"CTE"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"         Storm snow settling well.  Midpack now holds skier up. Widespread WHOOMPHING with long propogations through pack.  RB3 in facets above old MF crust on adjacent W aspect."
