[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Bow Summit"
.
98-01-15
13:15
"BW DV"
2030
M
.
SW
0
98205
Full
a
80
25
2
6
4
.
1
1
-7.0
85
0
[TEMPERATURES:no]
9
[temp_hgt,temp]
0,-1.5
10,-3.0
20,-5.0
30,-7.0
40,-8.0
50,-9.5
60,-10.0
70,-9.0
75,-8.0
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1 r
.
1
 ,""
0
[LAYERS:no]
8
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
011, ,5 , ,  , ,6      ,1,236, ,"",1
012, ,9e, ,5 , ,4      ,3,   , ,"still conglomerate",1
033, ,4 , ,  , ,2      ,1,248, ,"",1
045, ,4 , ,3 , ,1      ,3,266, ,"",1
056, ,3 , ,  , ,0.5    ,2,260, ,"some facets",1
066, ,4 , ,  , ,0.5    ,1,196, ,"",1
078, ,2 ,r,  , ,1      ,0,152, ,"",1
085, ,1 ,r,  , ,1      ,0,100, ,"",1
[SHEARS:no]
1
[shr_hgt,shr_test,shr_rslt,comment]
016,O, ," CTH in DH to sz 8 "
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
