[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Bow Summit"
.
98-03-12
10:00
"PW DV"
2030
M
.
SW
0
98208
Full
a
51
15
2
6
3
.
0
0
-4.0
90
0
[TEMPERATURES:no]
9
[temp_hgt,temp]
0,0.0
10,-2.0
20,-2.0
30,-3.0
40,-3.0
50,-4.0
60,-6.0
70,-5.0
80,-5.0
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
2  
.
0.3
0,""
0
[LAYERS:no]
11
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
013, ,5 , ,  , ,4 - 6  ,2,200, ,"",1
030, ,5 , ,4 , ,2 - 4  ,1,250, ,"",1
041, ,4 , ,  , ,2.0    ,2,280, ,"",1
043, ,4 , ,  , ,1.0    ,2,280, ,"",1
048, ,4c, ,  , ,1 - 2  ,2,300, ,"",1
065, ,4c, ,  , ,1.0    ,2,270, ,"",1
077, ,4c, ,  , ,1.0    ,1,200, ,"",1
081, ,3 , ,  , ,0.5    ,0,170, ,"",1
084, ,3 , ,4 , ,0.5    ,0,140, ,"",1
086, ,2 , ,  , ,0.5    ,0,140, ,"",1
090, ,2 , ,  , ,0.3    ,0,110, ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
015,O, ," CTH x1  @ 15"
084,O, ," CTE x6  @ 84"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
