[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Bow Summit"
.
98-02-11
12:00
"RB"
2030
M
.
NA
0
98207
Full
a
.
.
2
5
4
.
1
1
-2.0
83
0
[TEMPERATURES:no]
9
[temp_hgt,temp]
0,-1.2
10,-1.8
20,-2.1
30,-2.6
40,-3.2
50,-4.0
60,-4.6
70,-6.3
73,-6.1
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1 r
.
2.0
0,""
0
[LAYERS:no]
6
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
029,0,4 , ,5 , ,3.0-4.0,1,210, ,"CTE(4) x 2 ",1
031,0,4 , ,  , ,2.0    ,2,300,e,"",1
049,0,4 , ,  , ,1.5    ,2,280, ,"Some Rd'g, 1F soft",1
070,0,3 , ,  , ,1.0    ,2,270, ,"Some FC'g",1
078,0,3 , ,4 , ,1.0    ,1,220, ,"",1
083,0,2 , ,  , ,1.0    ,0,100, ,"",1
[SHEARS:no]
0
[shr_hgt,shr_test,shr_rslt,comment]
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
