[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Corral Creek 1"
.
98-01-03
12:30
"PW DV JB"
2180
M
.
SE
26
98513
Test
a
108
30
1
0
3
.
1
1
-10
108
0
[TEMPERATURES:no]
12
[temp_hgt,temp]
0,-0.9
10,-1.6
20,-2.3
30,-3.0
40,-3.6
50,-5.2
60,-7.2
70,-9.1
80,-10.9
90,-11.5
98,-11.5
108,-7.6
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
.
1-1.5
0,""
0
[LAYERS:no]
10
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
019,0,4 , ,  , ,1.5-3  ,1,   , ,"",1
033,0,4 , ,  , ,1-3    ,0,   , ,"",1
037,0,4 , ,  , ,.5     ,3,   , ,"",1
049,0,4 , ,  , ,.5-1   ,2,   , ,"",1
050,0,4 , ,  , ,1      ,3,   , ,"",1
054,0,4 , ,  , ,.5     ,2,   , ,"",1
059,0,4 , ,7 , ,.5   3 ,2,   , ,"",1
074,0,4 , ,  , ,.5     ,2,   , ,"",1
090,0,2 , ,  , ,.5-1   ,1,   , ,"",1
108,0,2 , ,  , ,1      ,0,   , ,"",1
[SHEARS:no]
3
[shr_hgt,shr_test,shr_rslt,comment]
036,R,3,"  RB 3 @ 36 Note 2"
054,S,M,"  SM @ 54"
090,S,V,"  SV @ 90 Note 1"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"Note 1   compression test @ 90 also"
""
"Note 2   RB 3 @ 36 on 24 degree slope,  collapse in F facets "
