[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Crowfoot Glades"
.
97-12-07
10:45
"PW"
7500
F
.
SW
28
98504
Test
a
.
.
2
6
2
.
0
0
-6.6
35
0
[TEMPERATURES:no]
5
[temp_hgt,temp]
0,-1.0
10,-2.0
20,-3.0
25,-4.5
35,-6.5
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
4  
7  
1-3
0,""
0
[LAYERS:no]
4
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
024,0,4 , ,5 , ,2-3    ,1,   , ,"",1
026,0,4 , ,  , ,1.2    ,3,   , ,"FC conglomerate",1
033,0,4 , ,  , ,.5     ,2,   , ,"",1
035,0,4 , ,  , ,1      ,3,   , ,"easy pencil, sun crust",1
[SHEARS:no]
0
[shr_hgt,shr_test,shr_rslt,comment]
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
