[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Crowfoot Glades"
.
98-04-05
12:30
"RB  AH  MM"
7700
F
.
NE
28
98534
Test
.
30
.
2
6
3
.
0
0
-0.9
157
0
[TEMPERATURES:no]
12
[temp_hgt,temp]
0,-1.5
20,-1.8
40,-2.0
60,-2.2
80,-2.3
100,-2.3
110,-2.2
120,-2.1
130,-2.0
140,-1.5
147,-0.7
157,-0.2
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
9e 
.
2-3
 ,"some FCing"
0
[LAYERS:no]
12
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
044, ,4 , ,  , ,3      ,0,   , ,"striations.",1
052, ,4 , ,  , ,1-1.5  ,3,   , ,"",1
064, ,4 , ,  , ,1.5    ,2,   , ,"1Fe. some rounding.",1
083, ,4 , ,  , ,1.5    ,2,   , ,"1Fh. some rounding.",1
123, ,4 , ,3 , ,1.5    ,2,   , ,"",1
127, ,3 , ,  , ,.5-1   ,3,   , ,"some FCing.",1
131, ,4 , ,  , ,1.5    ,1,   , ,"4Fe. late March FC.",1
144, ,3 , ,  , ,.5     ,2,   , ,"CTM3",1
145, ,8 , ,  , ,       ,4,   , ,"MF",1
152, ,2 , ,3 , ,1      ,2,   , ,"",1
154, ,3 , ,  , ,.5-1   ,1,   , ,"",1
157, ,9e, ,  , ,2-3    ,3,   , ,"",1
[SHEARS:no]
3
[shr_hgt,shr_test,shr_rslt,comment]
000,S,n,"o result"
044,R,3,"step to ground"
131,R,2,"were suprised"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"RB3 at 44 not representative because of boulder at top of pit."
