[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Crowfoot Glades"
.
98-01-10
14:00
"PW  RB  JO"
8000
F
.
E
28
98514
Test
a
.
.
2
2
1
.
0
0
-28.0
115
0
[TEMPERATURES:no]
13
[temp_hgt,temp]
0,-2.9
10,-2.5
20,-3.0
30,-3.6
40,-3.9
50,-5.1
60,-6.4
70,-7.8
80,-9.9
90,-13.8
100,-17.4
105,-20.0
115,-27.0
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
9a 
.
.3
0,""
0
[LAYERS:no]
9
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
034, ,4 , ,5 , ,2-3    ,0,   , ,"Fh",1
038, ,4 , ,  , ,1-1.5  ,3,   , ,"Nov crust remnants.",1
058, ,4 , ,  , ,.5     ,1,   , ,"4Fh",1
074, ,4 , ,  , ,1      ,2,   , ,"some rounding.",1
079, ,4 , ,  , ,.5     ,2,   , ,"1Fh",1
081, ,4 , ,  , ,.5-1   ,2,   , ,"",1
091, ,4 , ,  , ,.5     ,2,   , ,"1Fh. some rounding.",1
099, ,4 , ,  , ,1      ,1,   , ,"",1
115, ,4 , ,  , ,1      ,0,   , ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
034,R,4,"SM"
074,R,4,"SM"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
