[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Chikadee/Boom Col"
.
98-02-22
12:30
"DV/GHI/RB"
2272
M
.
NA
29
98528
Test
a
35
.
2
5
3
.
1
1
-4.0
270
1
[TEMPERATURES:no]
0
[temp_hgt,temp]
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
.
.
 ,""
0
[LAYERS:no]
7
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
024, ,1 , ,  , ,       ,0,   , ,"",1
025, ,  , ,  , ,       ,2,   , ,"",1
034, ,  , ,  , ,       ,1,   , ,"",1
039, ,  , ,  , ,       ,3,   , ,"",1
043, ,  , ,  , ,       ,1,   , ,"",1
150, ,  , ,  , ,       ,3,   , ,"",1
270, ,  , ,  , ,       , ,   , ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
020,R,5,"HST on Sun Crust"
039,R,5,""
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
