[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Crowfoot Cirque"
.
98-02-11
13:00
"DV MH PW"
2160
M
.
E
27
98526
Test
a
.
.
1
0
3
.
1
1
-4
73
0
[TEMPERATURES:no]
7
[temp_hgt,temp]
0,0.0
10,-0.5
30,-1.5
50,-3.5
60,-3.5
63,-4.0
73,-1.0
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
.
1
0,""
0
[LAYERS:no]
6
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
003, ,5 , ,  , ,3-5    ,1,   , ,"",1
015,0,  , ,  , ,3-5    ,4,   , ,"conglomerate facets",1
040,0,  , ,  , ,       ,2,   , ,"",1
045,0,  , ,  , ,       ,3,   , ,"",1
066,0,3 , ,  , ,.5     ,1,   , ,"",1
073,0,  , ,  , ,       ,0,   , ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
025,O, ,"  CTH x5 ON FC  1-3"
060,R,6,"RB6 @60 on FC size1"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
