[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Hidden Bowl"
.
98-02-08
13:30
"B. WHITE D. VOLKERS"
7000
F
.
NE
36
98525
Test
a
35
10
2
6
3
.
0
0
-2.5
136
0
[TEMPERATURES:no]
13
[temp_hgt,temp]
0,-1.5
20,-2.0
40,-2.5
50,-3.0
60,-3.5
70,-4.0
80,-4.0
90,-5.0
100,-5.0
110,-5.0
120,-5.0
130,-5.5
136,-5.0
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
.
4
0,"Cold Large Stellars"
0
[LAYERS:no]
8
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
030, ,5b, ,  , ,6      ,1,   , ,"rounding",1
048, ,4c, ,  , ,1.5    ,2,   , ,"",1
060, ,3 , ,  , ,1      ,3,   , ,"",1
079, ,3 , ,  , ,1.     ,3,   , ,"",1
098, ,3 , ,  , ,1      ,2,   , ,"",1
103, ,3 , ,  , ,0.5    ,3,   , ,"",1
121, ,3 , ,  , ,0.5    ,2,   , ,"",1
136, ,2 , ,4 , ,1      ,1,   , ,"",1
[SHEARS:no]
3
[shr_hgt,shr_test,shr_rslt,comment]
030,R,6,"4 jumps at 6"
098,S,M,"fc below  WC"
103,S,M,"FC above WC"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"   No natural activity in Hidden Bowl all season except for some in steep rocky terrain to the north.  Snowpack is variable but very strong for early Feb."
