[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Hidden Bowl top of bowl "
.
98-03-04
13:20
"WHITE/WOODS"
8300
F
.
E
38
98531
Test
a
50
20
2
4
3
.
0
0
-8.4
124
0
[TEMPERATURES:no]
9
[temp_hgt,temp]
30,-3.9
50,-4.5
70,-5.3
80,-6.0
90,-6.6
100,-7.0
110,-7.5
114,-7.8
124,-8.4
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
.
2
0,""
0
[LAYERS:no]
8
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
027,0,5 , ,  , ,6      ,2,   , ,"Sintered & rounded",1
039,0,4c, ,  , ,       ,3,   , ,"",1
060,0,3 , ,  , ,       ,3,   , ,"",1
082,0,3 , ,  , ,       ,3,   , ,"",1
103,0,3 , ,  , ,       ,3,   , ,"",1
105,0,4 , ,  , ,3      ,1,   , ,"SEE NOTE 1",1
120,0,2 , ,  , ,1      ,1,   , ,"",1
124,0,1 , ,  , ,2      ,0,   , ,"",1
[SHEARS:no]
0
[shr_hgt,shr_test,shr_rslt,comment]
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"   Note 1: Comp test easy on FC size 3 (FEB 24 INTERFACE). This layer is present throuhout the forecast district and will likely become active after further load."
""
"RB7 on bottom of pack."
""
""
""
