[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Instructor's Gulley"
.
98-03-02
13:00
"B. WHITE"
7200
F
.
SW
35
98529
Test
a
50
10
2
4
2
.
0
0
5.0
76
0
[TEMPERATURES:no]
7
[temp_hgt,temp]
0,-0.9
20,-1.5
40,-2.0
50,-2.4
60,-1.9
66,-0.1
76,0.0
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
.
.
.
 ,""
0
[LAYERS:no]
6
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
025, ,5 , ,  , ,4      ,1,   , ,"",1
030, ,4 , ,  , ,2      ,3,   , ,"old Oct MF crust",1
064, ,4 , ,  , ,1-1.5  ,1,   , ,"",1
067, ,9 , ,  , ,       ,2,   , ,"lt. mf crust",1
073, ,2 , ,  , ,       ,0,   , ,"",1
076,1,9e, ,  , ,       ,2,   , ,"Thin MF forming",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
030,R,7,"Not clean/ collapse"
067,S,M,"Moist snow ovr crust"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"   Warm temps creating surface crust. Shallow snowpack area is weak, foot pen to near ground, but no result with Rutschblock."
