[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Little Wawa"
.
97-12-28
.
"PW, DW"
2455
M
.
E
24
98508
Test
b
.
.
3
5
3
.
1
1
-6.7
99
0
[TEMPERATURES:no]
11
[temp_hgt,temp]
0,-1.4
10,-2.0
20,-2.9
30,-3.7
40,-4.1
50,-5.7
60,-7.1
70,-8.4
80,-9.6
89,-8.8
99,-5.9
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
.
2
0,""
0
[LAYERS:no]
12
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
015,0,4 , ,  , ,2-3    ,2,   , ,"",1
031,0,4 , ,  , ,2-3    ,1,   , ,"",1
032,0,4 , ,  , ,2      ,3,   , ,"Nov 18 MF",1
035,0,4 , ,  , ,1      ,2,   , ,"",1
041,0,4 , ,3 , ,1      ,3,   , ,"",1
050,0,4 , ,3 , ,1.5    ,2,   , ,"",1
055,0,4 , ,3 , ,1      ,2,   , ,"",1
073,0,3 , ,4 , ,.5     ,2,   , ,"",1
074,0,7 , ,  , ,6-8    , ,   , ,"",1
083,0,2 , ,  , ,1-1.5  ,1,   , ,"",1
084,0,1 , ,2 , ,2-3    ,5,   , ,"",1
099,0,1 , ,2 , ,1-2    ,0,   , ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
073,S,E,"  SE @73 on V  Note 2"
083,S,E,"  SE @83  Note 1"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"Note 1 Both SE & CTE X2 @ 83, repeatable."
""
"Note 2 Both SE & CTE X8 @ 73, repeatable."
