[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Little Wawa"
.
98-01-03
10:55
"PW, ML"
2455
M
.
E
26
98509
Test
.
.
.
2
5
4
.
1
1
-15.0
84
0
[TEMPERATURES:no]
10
[temp_hgt,temp]
0,-1.3
10,-1.9
20,-2.7
30,-3.8
40,-5.5
50,-8.7
60,-11.9
70,-16.0
74,-17.6
84,-16.9
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
2  
.
.5
 ,""
0
[LAYERS:no]
9
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
015,0,4 , ,5 , ,2 - 3  ,2,   , ,"",1
030,0,4 , ,5 , ,2 - 4  ,1,   , ,"",1
040,0,4 , ,  , ,.5 -1  ,3,   , ,"",1
048,0,4 , ,  , ,.5     ,2,   , ,"1Finger plus",1
054,0,2 , ,4 , ,.5 - 1 ,3,   , ,"",1
063,0,2 , ,4 , ,.5 - 1 ,3,   , ,"",1
069,0,2 , ,  , ,.5 - 1 ,2,   , ,"",1
077,0,2 , ,4 , ,.5     ,2,   , ,"1Finger plus",1
084,0,2 , ,  , ,.5     ,3,   , ,"",1
[SHEARS:no]
0
[shr_hgt,shr_test,shr_rslt,comment]
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
