[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Main Camp"
.
90-01-06
14:30
"BC"
1370
M
.
SE
0
01
Full
a
30
.
1
0
1
.
0
0
-15.0
114
0
[TEMPERATURES:no]
11
[temp_hgt,temp]
0,0.0
20,-1.0
30,-1.5
40,-2.5
50,-3.0
60,-4.0
70,-4.5
80,-5.0
90,-7.0
104,-9.0
114,-13.0
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
.
1.5
 ,""
0
[LAYERS:no]
10
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
018,0,4 , ,  , ,1-3    ,2,300, ,"",1
035,0,4c, ,  , ,1      ,2,310, ,"",1
040,0,9 , ,4 , ,1.5    ,3,   , ,"crust",1
075,0,3 , ,4c, ,.5     ,2,270, ,"",1
085,0,3 , ,  , ,.5     ,2,290, ,"",1
096,0,4c, ,  , ,1      ,1,270, ,"",1
099,0,9e, ,  , ,2      ,3,300, ,"mid-December Rain Crust",1
101,0,7 , ,4c, ,4      ,1,   , ,"",1
111,0,4 , ,  , ,1      ,1,200, ,"",1
114,0,2 , ,  , ,1      ,0,120, ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
092,S,M,""
101,S,E," comp easy"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
