[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Niblock Whyte col"
.
98-02-13
14:10
"PW DV"
2800
M
.
NA
26
98527
Test
a
.
.
0
0
4
.
1
1
-7.3
62
0
[TEMPERATURES:no]
8
[temp_hgt,temp]
0,-5.8
10,-5.8
20,-6.4
30,-7.0
40,-8.1
50,-8.2
52,-8.2
62,-4.9
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
.
.
.
 ,""
0
[LAYERS:no]
8
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
026, ,  , ,  , ,       ,3,   , ,"",1
030, ,  , ,  , ,       ,3,   , ,"",1
043, ,  , ,  , ,       ,2,   , ,"",1
049, ,  , ,  , ,       ,2,   , ,"",1
053, ,  , ,  , ,       ,2,   , ,"",1
059, ,  , ,  , ,       ,1,   , ,"",1
060, ,  , ,  , ,       ,2,   , ,"",1
062, ,  , ,  , ,       ,0,   , ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
030,S,H,"   STH @ 30"
059,S,M,"  STM @ 59"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"Note 1:  CTE X5 @ 59"
