[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Observation Peak"
.
97-12-04
12:00
"JO    RB"
7100
F
.
SE
15
98502
Test
a
40
35
1
0
1
.
0
0
-1
46
0
[TEMPERATURES:no]
5
[temp_hgt,temp]
0,-1.6
10,-2.6
20,-4.0
30,-6.6
36,-8.1
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
2  
.
.5
 ,""
0
[LAYERS:no]
4
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
010, ,4 , ,5 , ,2      ,1,   , ,"",1
012, ,8 , ,  , ,       ,3,   , ," facets to 2 above crust ",1
040, ,2 , ,  , ,.5     ,2,   , ,"some facetting",1
046, ,2 , ,  , ,.5     ,0,   , ,"some rounding",1
[SHEARS:no]
1
[shr_hgt,shr_test,shr_rslt,comment]
010,S,M,"just below crust"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"- some natural activity observed on north and east aspects.....size 1 to 2"
"- SH to size 20mm evident in area around 6200'."
