[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Observation Peak"
.
98-01-27
11:30
"ML"
2315
M
.
W
25
98521
Test
.
.
.
1
0
3
.
0
0
-2.0
93
0
[TEMPERATURES:no]
10
[temp_hgt,temp]
0,-0.9
10,-1.4
30,-2.0
40,-2.4
50,-3.0
60,-3.6
70,-4.3
80,-6.1
83,-6.7
93,-5.9
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
.
.
.
 ,""
0
[LAYERS:no]
7
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
013, ,  , ,  , ,       ,2,   , ,"",1
031, ,  , ,  , ,       ,1,   , ,"",1
032, ,  , ,  , ,       ,2,   , ,"Nov crust",1
047, ,  , ,  , ,       ,1,   , ,"",1
073, ,  , ,  , ,       ,2,   , ,"",1
088, ,  , ,  , ,       ,1,   , ,"",1
093, ,  , ,  , ,       ,0,   , ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
031,R,4,"also STM"
088,S,B,"urp nil"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
