[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Pipestone Bowl"
.
98-01-12
14:15
"BW DV"
.
M
.
NE
27
98515
Test
a
.
.
1
0
4
.
0
0
-21.0
100
0
[TEMPERATURES:no]
2
[temp_hgt,temp]
90,-19.0
100,-25.0
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
.
.
.
 ,""
0
[LAYERS:no]
6
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
024, ,4 , ,5 , ,       ,1,   , ,"",1
028, ,9e, ,3 , ,       ,3,   , ,"",1
046, ,4 , ,  , ,       ,1,   , ,"",1
057, ,3 , ,  , ,       ,3,   , ,"",1
076, ,2 , ,3 , ,       ,1,   , ,"",1
100, ,2 , ,4 , ,       ,0,   , ,"",1
[SHEARS:no]
3
[shr_hgt,shr_test,shr_rslt,comment]
028,S,H,"    ,  RB IRREG"
057,R,4,"  ABOVE P LAYER"
076,O, ,"Burp easy  CTE"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"       ADJACENT TO NATURAL ACTIVITY ON NOV MC CRUST. ( OCCURRED AROUND 980101)  25CM ON BED SURFACE  BED SURFACE IS NOW P-K HARDNESS WITH GOOD BOND TO NEW SNOW."
