[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Pipestone Bowl"
.
98-01-05
11:30
"GHI  ML"
2200
M
.
N
20
98511
Test
a
100
.
3
6
4
.
1
1
-10.5
100
0
[TEMPERATURES:no]
7
[temp_hgt,temp]
0,-2.1
50,-3.7
60,-4.9
70,-6.1
80,-8.1
90,-9.5
100,-9.5
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
.
.
.
 ,""
0
[LAYERS:no]
6
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
037, ,4 , ,  , ,2      ,1,   , ,"bigger DH near bottom ctm4",2
041, ,  , ,  , ,       ,3,   , ,"",1
052, ,  , ,  , ,       ,2,   , ,"R4 @ 52 ctm6 @ 52",1
070, ,  , ,  , ,       ,2,   , ,"",1
094, ,  , ,  , ,       ,0,   , ,"cte3 @ 94",1
100, ,  , ,  , ,       ,0,   , ,"",1
[SHEARS:no]
0
[shr_hgt,shr_test,shr_rslt,comment]
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
