[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Paget Peak"
.
98-02-07
10:20
"PW   RB   JO"
6640
F
.
S
24
98523
Test
a
15
15
2
6
4
.
1
1
-2.9
123
0
[TEMPERATURES:no]
10
[temp_hgt,temp]
0,-1.3
30,-2.2
50,-2.7
60,-2.5
70,-3.0
80,-3.2
90,-3.4
100,-3.5
110,-3.4
113,-3.1
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
2  
1
 ,"riming"
0
[LAYERS:no]
11
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
030, ,4 , ,5 , ,2-3    ,1,   , ,"",1
069, ,3 , ,  , ,       ,3,   , ,"",1
077, ,3 , ,  , ,       ,2,   , ,"1F+",1
085, ,3 , ,  , ,       ,3,   , ,"",1
095, ,3 , ,  , ,       ,3,   , ,"",1
103, ,3 , ,  , ,       ,3,   , ,"",1
106, ,3 , ,  , ,       ,2,   , ,"",1
114, ,3 , ,  , ,       ,1,   , ,"",1
116, ,3 , ,  , ,       ,1,   , ,"",1
119, ,3 , ,  , ,       ,1,   , ,"",1
123, ,4 , ,  , ,       ,3,   , ,"",1
[SHEARS:no]
1
[shr_hgt,shr_test,shr_rslt,comment]
095,R,6,""
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"bushy at base of pit.  "
