[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Purple Bowl"
.
98-01-22
13:22
"BW, ML"
2455
M
.
N
21
98520
Test
.
.
.
3
2
3
.
0
0
-8.0
102
0
[TEMPERATURES:no]
11
[temp_hgt,temp]
0,-3.5
10,-3.3
20,-3.6
30,-3.7
40,-3.9
50,-4.6
60,-5.5
70,-6.0
80,-7.1
92,-9.0
102,-8.7
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
.
.
 ,""
0
[LAYERS:no]
7
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
019,0,5 , ,  , ,4      ,1,   , ,"",1
023,0,5 , ,  , ,       ,3,   , ,"",1
042,0,5 , ,  , ,4 - 8  ,1,   , ,"",1
053,0,4 , ,  , ,       ,2,   , ,"",1
069,0,3 , ,  , ,       ,2,   , ,"1F minus",1
092,0,3 , ,  , ,       ,2,   , ,"",1
102,0,3 , ,  , ,       ,0,   , ,"",1
[SHEARS:no]
3
[shr_hgt,shr_test,shr_rslt,comment]
015,S,M,"Collapse"
023,S,E,"Compression"
092,S,E,"see Note 1"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"Note 1: Also easy compression and moderate burp."
""
""
""
""
