[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Purple Bowl"
.
98-01-31
12:45
"JO    MH"
2530
M
.
N
24
98522
Test
a
.
15
1
0
1
.
0
0
-5.7
101
0
[TEMPERATURES:no]
10
[temp_hgt,temp]
0,-2.3
10,-2.7
20,-3.0
40,-3.6
50,-3.9
60,-4.9
70,-6.0
80,-7.6
90,-10.6
101,-13.8
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
7  
.
2-3
 ,""
0
[LAYERS:no]
6
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
031, ,4 , ,5 , ,3      ,1,   , ,"4F-",1
044, ,4 , ,  , ,1-1.5  ,2,   , ,"1F-",1
050, ,3 , ,  , ,1      ,2,   , ,"some FCing",1
077, ,3 , ,  , ,.5     ,2,   , ,"",1
080, ,3 , ,  , ,.3     ,2,   , ,"1F+",1
101, ,3 , ,  , ,.5     ,1,   , ,"4F+",1
[SHEARS:no]
1
[shr_hgt,shr_test,shr_rslt,comment]
000,S,E,""
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"R6 - block just broke apart"
