[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Quartz Ridge"
.
98-03-01
14:00
"DV HD"
8200
F
.
NE
39
98530
Test
a
.
15
2
6
3
.
0
0
-7.0
162
0
[TEMPERATURES:no]
1
[temp_hgt,temp]
162,-7.0
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
7  
.
3
 ,""
0
[LAYERS:no]
9
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
023, ,  , ,  , ,       ,1,   , ,"",1
030, ,  , ,  , ,       ,3,   , ,"",1
040, ,  , ,  , ,       ,2,   , ,"",1
060, ,  , ,  , ,       ,3,   , ,"",1
108, ,  , ,  , ,       ,3,   , ,"",1
123, ,  , ,  , ,       ,2,   , ,"",1
124, ,  , ,  , ,       ,1,   , ,"Old SH 3",1
147, ,  , ,  , ,       ,2,   , ,"",1
162, ,  , ,  , ,       ,0,   , ,"",1
[SHEARS:no]
1
[shr_hgt,shr_test,shr_rslt,comment]
124,R,6,""
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
