[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Standish - south side"
.
98-03-10
14:00
"DV"
7800
F
.
SW
27
98532
Test
a
75
.
2
6
4
.
0
0
-5.0
99
0
[TEMPERATURES:no]
5
[temp_hgt,temp]
0,-1.0
20,-2.0
50,-3.5
89,-2.0
99,-0.5
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
.
.
.
 ,""
0
[LAYERS:no]
11
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
021, ,  , ,  , ,       ,2,   , ,"",1
044, ,  , ,  , ,       ,1,   , ,"",1
070, ,  , ,  , ,       ,2,   , ,"",1
072, ,  , ,  , ,       ,3,   , ,"",1
076, ,  , ,  , ,       ,1,   , ,"",1
078, ,  , ,  , ,       ,4,   , ,"",1
083, ,  , ,  , ,       ,0,   , ,"",1
087, ,  , ,  , ,       ,4,   , ,"",1
093, ,  , ,  , ,       ,0,   , ,"",1
096, ,  , ,  , ,       ,3,   , ,"",1
099, ,  , ,  , ,       ,0,   , ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
078, , ,"Failed when cut"
087, ,C,"TE  2 taps"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
