[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Schaeffer Bowl"
.
97-12-05
12:00
"PW   JO"
7300
F
.
N
30
98503
Test
a
.
.
1
0
1
.
0
0
-8.0
62
0
[TEMPERATURES:no]
7
[temp_hgt,temp]
0,-1.6
10,-2.4
20,-2.3
30,-4.8
40,-7.7
52,-11.1
62,-16.0
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
4  
.
.5
 ,"few SH to size 2"
0
[LAYERS:no]
6
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
025, ,4 , ,5 , ,2-3    ,1,   , ,"",1
028, ,4 , ,  , ,1-1.5  ,3,   , ,"FC conglomerate",1
029, ,4 , ,  , ,2      , ,   , ,"4F?",1
049, ,4 , ,  , ,1      ,2,   , ,"",1
052, ,4 , ,  , ,.5     ,2,   , ,"",1
062, ,4 , ,  , ,1      ,0,   , ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
000,S,E,"when cut to grnd"
029,R,1,"boooo! top MF"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
P
[COMMENTS]
""
