[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Schaeffer Bowl"
.
97-12-19
13:00
"RB/MH"
2212
M
.
N
30
98506
Test
a
60
15
1
0
4
.
0
0
-10.5
90
0
[TEMPERATURES:no]
9
[temp_hgt,temp]
0,-1.2
10,-1.4
20,-1.9
30,-2.8
40,-3.3
50,-4.0
60,-5.7
70,-7.7
80,-9.1
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1 r
2  
1.5-2.0
0,""
0
[LAYERS:no]
9
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
016,0,5 , ,4 , ,2.0-3.0,2,   , ,"",1
032,0,4 , ,  , ,1.5-2.0,1,   , ,"",1
033,0,4 , ,8 , ,2.0    ,2,   , ,"1F Hard Mid Nov MF",1
046,0,4 , ,  , ,1.5    ,2,   , ,"",1
059,0,4 , ,  , ,1.0    ,2,   , ,"1F Easy",1
066,0,9 , ,  , ,1.5    ,3,   , ,"Wind Crust",1
067,0,4 , ,  , ,1.5    ,0,   , ,"",1
072,0,3 , ,  , ,0.5    ,0,   , ,"F Hard",1
090,0,2 , ,3 , ,0.5-1.0,0,   , ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
032,R,4,"Sht Burp/Comp Mod"
066,R,4,"Sht Comp Easy"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"Mid Nov MF FC'ng out.   No sign of Mid Dec SH."
