[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Schaeffer Bowl"
.
98-01-15
12:40
"DV ML BW"
2400
M
.
N
35
98517
Test
a
.
.
1
0
4
.
1
1
-7.0
127
0
[TEMPERATURES:no]
14
[temp_hgt,temp]
0,-1.4
10,-1.8
20,-2.3
30,-3.3
40,-4.0
50,-5.7
60,-5.9
70,-7.3
80,-8.8
90,-9.4
100,-9.4
110,-9.3
117,-7.7
127,-3.3
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
.
.
.
 ,""
0
[LAYERS:no]
6
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
019, ,  , ,  , ,       ,1,   , ,"",1
047, ,4 , ,  , ,       ,1,   , ,"",1
063, ,  , ,  , ,       ,2,   , ,"",1
075, ,2 , ,  , ,       ,2,   , ,"",1
099, ,2 , ,  , ,       ,1,   , ,"",1
127, ,1 , ,  , ,       ,0,   , ,"",1
[SHEARS:no]
3
[shr_hgt,shr_test,shr_rslt,comment]
019, , ,"MF crust"
063,O,C,"M on V 4-8"
117,O,C,"E"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
