[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Stanley Glacier Valley"
.
98-01-20
14:00
"DV"
2000
M
.
W
19
98519
Test
a
.
20
1
0
4
.
1
1
-1.0
88
0
[TEMPERATURES:no]
1
[temp_hgt,temp]
88,0.0
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
.
.
.
 ,""
0
[LAYERS:no]
5
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
024, ,  , ,  , ,       ,0,   , ,"",1
034, ,  , ,  , ,       ,2,   , ,"",1
044, ,  , ,  , ,       ,2,   , ,"",1
072, ,  , ,  , ,       ,1,   , ,"",1
088, ,  , ,  , ,       ,0,   , ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
019, , ,"CM collapse"
072, , ,"CE"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
