[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"South of Rock Isle Lake"
.
97-12-22
13:15
"DV"
2300
M
.
N
20
98507
Test
a
.
.
2
5
4
.
0
0
-13.0
122
0
[TEMPERATURES:no]
14
[temp_hgt,temp]
0,-0.5
10,-1.0
20,-1.5
30,-2.0
40,-3.0
50,-4.0
60,-4.5
70,-6.0
80,-7.0
90,-9.5
100,-11.0
110,-13.0
112,-13.0
122,-11.0
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
2  
.
0.5
 ,""
0
[LAYERS:no]
8
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
013, ,5 , ,  , ,3      ,1,   , ,"",1
017, ,  , ,  , ,       ,3,   , ,"Hard pencil",1
058, ,4 , ,  , ,2.0    ,1,   , ,"Variable hardness",1
088, ,  , ,  , ,       ,2,   , ,"",1
094, ,4 , ,  , ,1.0    ,1,   , ,"",1
098, ,3 , ,  , ,0.5    ,3,   , ,"",1
105, ,  , ,  , ,       ,1,   , ,"",1
122, ,  , ,  , ,       ,0,   , ,"",1
[SHEARS:no]
3
[shr_hgt,shr_test,shr_rslt,comment]
058,S,M,"on V 3 - 6"
093,S,M,"on V 4 - 6"
118,O,C,"T east on stellars 2"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
