[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Surprise Pass"
.
98-02-09
12:30
"JO  DV  IP"
8100
F
.
NW
40
98524
Test
a
25
.
1
0
3
.
1
1
-3.0
105
0
[TEMPERATURES:no]
2
[temp_hgt,temp]
0,-1.2
105,-2.6
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
1d 
2
 ,"rime"
0
[LAYERS:no]
7
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
030, ,4 , ,5 , ,2      ,1,   , ,"very few DH",1
043, ,4 , ,  , ,1.5    ,2,   , ,"1F-",1
046, ,3 , ,  , ,.5     ,3,   , ,"",1
065, ,3 , ,  , ,.3     ,2,   , ,"",1
091, ,4 , ,  , ,2      ,0,   , ,"some striations",1
093, ,8 , ,  , ,.3     ,3,   , ,"",1
105, ,3 , ,4 , ,.5     ,0,   , ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
000,S,M,""
065,S,E,""
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"comp moderate at 65 and 46"
