[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Takakkaw"
.
97-12-24
12:30
"GHI/RB"
1560
M
.
NA
0
98402
Full
a
.
.
1
0
2
.
0
0
-6.5
58
0
[TEMPERATURES:no]
6
[temp_hgt,temp]
0,-1.0
10,-1.9
20,-3.0
30,-3.9
40,-6.0
50,-10.2
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
.
.
.
 ,""
0
[LAYERS:no]
7
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
005,0,5 , ,  , ,3.0    ,0,180, ,"",1
010,0,4 , ,  , ,2.0    ,3,280, ,"FC c Mid Nov M-F",1
034,0,4 , ,  , ,1.5    ,2,210, ,"",1
035,0,4 , ,7 , ,0.5-1.0,0,   , ,"SH almost FC'd out",1
052,0,2 , ,3 , ,0.5-1.0,1,170, ,"",1
057,0,1 , ,2 , ,1.0-2.0,0,070, ,"",1
058,0,1 , ,  , ,2.0    ,0,070,e,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
035,S,M,"Comp @ 1"
054,S,V,"Comp @1"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
