[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Takakkaw"
.
97-12-11
10:20
"JO  DV  BW"
1560
M
.
NA
0
98401
Full
.
28
.
1
0
3
.
0
0
-14.3
41
0
[TEMPERATURES:no]
5
[temp_hgt,temp]
0,-1.1
10,-3.0
20,-5.9
31,-9.1
41,-14.0
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
1d 
2
 ,""
0
[LAYERS:no]
4
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
007, ,4 , ,5 , ,2-3    ,2,250, ,"1F to 4F",1
010, ,9 , ,  , ,2      ,3,310, ,"FC2 on crust. FCing",1
039, ,4 , ,7 , ,1      ,1,210, ," long needle SH under HN",1
041, ,4 , ,  , ,1      ,0,090, ,"",1
[SHEARS:no]
1
[shr_hgt,shr_test,shr_rslt,comment]
007,S,M,"    Note 1"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"    No conclusive shears in plot. Tests on adjacent roof slope show easy shear on surface hoar       up to 30mm size on top of  crust."
""
""
