[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Takakkaw"
.
98-03-19
10:40
"ML BW"
.
M
.
NA
0
98407
Full
a
15
10
1
0
1
.
0
0
1.0
111
0
[TEMPERATURES:no]
9
[temp_hgt,temp]
0,0.0
20,-0.5
40,-0.9
60,-1.4
70,-2.0
80,-2.6
90,-3.7
101,-7.8
111,-3.2
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
4  
7  
1-2
 ,""
0
[LAYERS:no]
8
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
014,0,5 , ,  , ,4-6    ,2,360, ,"Well bonded rounded",1
031,0,5 , ,  , ,3      ,2,330, ,"Sintered and rounded",1
050,0,4c, ,  , ,1.5    ,3,370, ,"",1
086,0,3 , ,  , ,1      ,3,360, ,"some FC'ing",1
101,0,3 , ,4 , ,1      ,2,240, ,"FC just under crust",1
105,0,9e, ,4 , ,       ,4,290, ,"laminated MF CR & FC",1
108,0,4 , ,9e, ,       ,4,290, ,"108 -101 MF crust and FC",1
111,0,4 , ,  , ,1.5    ,0,   , ,"",1
[SHEARS:no]
0
[shr_hgt,shr_test,shr_rslt,comment]
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"   Comp test M under Crust @ 101 on FC. Midpack and base extremely strong. Naturals on adjacent terrain thin slabs in new snow some trenching down to ground at lower elevations as they encountered near isothermal pack."
""
""
