[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Takakkaw"
.
98-01-08
12:30
"JO   RB"
1560
M
.
NA
0
98403
Full
a
.
.
1
0
2
.
0
0
-23.5
119
0
[TEMPERATURES:no]
12
[temp_hgt,temp]
0,-0.8
10,-1.2
20,-1.8
30,-2.5
40,-3.0
50,-4.0
60,-4.6
70,-5.5
80,-6.6
90,-7.6
100,-10.9
109,-15.0
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
2  
1
 ,"rime"
0
[LAYERS:no]
9
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
007, ,4 , ,5 , ,2-3    ,1,230, ,"4F easy",1
031, ,4 , ,  , ,1.5    ,1,260, ,"",1
050, ,3 , ,  , ,1      ,2,290, ,"some FCing. 1F hard",1
060, ,3 , ,  , ,.5     ,2,230, ,"",1
067, ,3 , ,  , ,.25-.5 ,2,240, ,"1F hard",1
077, ,3 , ,  , ,.5-1   ,2,220, ,"",1
088, ,2 , ,3 , ,1      ,1,180, ,"",1
113, ,2 , ,  , ,1.5    ,0,120, ,"",1
119, ,2 , ,  , ,1      ,0,120, ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
007,S,M,"old crust"
113,S,E,"overnight snow"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
