[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Takakkaw"
.
98-03-05
11:30
"JO   RB"
1560
M
.
NA
0
98406
Full
a
.
.
2
1
2
.
0
0
-5.7
113
0
[TEMPERATURES:no]
12
[temp_hgt,temp]
0,-0.2
10,-0.7
20,-1.2
30,-1.8
40,-2.1
50,-2.4
60,-2.8
70,-3.2
80,-3.7
90,-4.7
100,-6.6
103,-7.7
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
2  
1d 
1
 ,"some FCing"
0
[LAYERS:no]
10
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
013, ,4 , ,  , ,2      ,2,280, ,"variable R.  striations.",1
035, ,4c, ,  , ,.5-1   ,2,320, ,"",1
085, ,3 , ,  , ,.5     ,3,360, ,"P-",1
087, ,4 , ,  , ,.5     ,1,260, ,"some RG",1
088, ,4 , ,  , ,1      ,2,260, ,"some RG",1
089, ,4 , ,  , ,.5     ,1,260, ,"some RG",1
091, ,4 , ,  , ,.5     ,2,260, ,"some RG",1
095, ,4 , ,  , ,.5     ,1,240, ,"4F-",1
111, ,4 , ,  , ,.3     ,1,210, ,"thin cr @ 111. ",1
113, ,4 , ,  , ,.5     ,0,210, ,"",1
[SHEARS:no]
1
[shr_hgt,shr_test,shr_rslt,comment]
111,O,C,"TM x 7"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
