[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Takakkaw"
.
98-02-05
10:15
"PW   MH"
1560
M
.
NA
0
98405
Full
a
.
.
2
6
4
.
1
1
-0.5
106
0
[TEMPERATURES:no]
12
[temp_hgt,temp]
0,-1.0
10,-1.6
20,-2.3
30,-2.8
40,-3.3
50,-3.9
60,-4.0
70,-4.6
80,-5.2
90,-5.4
96,-4.8
106,-0.5
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1f 
1  
3-1
 ,""
0
[LAYERS:no]
9
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
011, ,4 , ,5 , ,2-3    ,2,280, ,"",1
027, ,4 , ,  , ,2      ,1,260, ,"",1
047, ,3 , ,4 , ,1-1.5  ,3,340, ,"",1
060, ,3 , ,4 , ,.5-1   ,3,320, ,"P+",1
061, ,3 , ,4 , ,1      , ,   , ,"",1
082, ,3 , ,4 , ,.5-1   ,3,260, ,"",1
097, ,3 , ,  , ,.5     ,1,190, ,"4F+",1
105, ,3 , ,  , ,.5     ,0,140, ,"",1
106, ,1f, ,1 , ,3-1    , ,   , ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
082,O,c,"omp hard"
097,O,c,"omp mod"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
