[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Takakkaw"
.
98-01-22
10:15
"JO   KH"
1560
M
.
NA
0
98404
Full
a
.
.
1
0
8
.
1
1
-4.0
120
0
[TEMPERATURES:no]
13
[temp_hgt,temp]
0,-0.6
10,-1.0
20,-1.5
30,-2.1
40,-2.5
50,-2.9
60,-3.2
70,-3.4
80,-3.7
90,-4.0
100,-4.7
110,-5.9
120,-4.0
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
1 r
1
 ,""
0
[LAYERS:no]
11
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
028, ,4 , ,5 , ,2-3    ,1,210, ,"",1
043, ,4 , ,  , ,1      ,2,300, ,"",1
051, ,4 , ,  , ,1      ,2,280, ,"1F-",1
056, ,4 , ,  , ,.5     ,2,300, ,"",1
061, ,3 , ,  , ,.5     ,2,290, ,"",1
065, ,3 , ,  , ,.5     ,2,270, ,"1F+",1
082, ,3 , ,  , ,.3     ,2,230, ,"",1
083, ,2 , ,3 , ,.5     ,2,190,e,"",1
112, ,3 , ,  , ,.3     ,2,140, ,"",1
117, ,3 , ,  , ,1      ,0,080, ,"",1
120, ,2 , ,9a, ,1.5    ,0,050, ,"",1
[SHEARS:no]
0
[shr_hgt,shr_test,shr_rslt,comment]
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"83-82 stellar arms rounding.  no results from 3 shovel tests but did plane when pulling pit apart."
