[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Takakkaw"
.
98-04-02
12:00
"DV JB"
1560
M
.
NA
0
98408
Full
a
3
1
2
6
3
.
0
0
6.5
111
0
[TEMPERATURES:no]
13
[temp_hgt,temp]
0,-1.1
10,-1.1
20,-1.1
30,-1.1
40,-1.2
50,-1.2
60,-1.2
70,-1.1
80,-0.7
90,-0.6
100,-0.4
110,-0.2
111,-0.3
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
4c 
.
1 - 2
1,""
0
[LAYERS:no]
9
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
004, ,5 , ,  , ,3 - 7  ,4,   , ," Rounding",1
010, ,5 , ,  , ,3 - 5  ,2,   , ," Rounding",1
013, ,4c, ,  , ,2 - 3  ,3,   , ,"",1
028, ,4c, ,  , ,2      ,2,   , ,"",1
045, ,4c, ,  , ,1      ,3,   , ,"",1
073, ,4c, ,  , ,1      ,3,   , ," Rounded SH @ 45",1
096, ,3 , ,  , ,.5 - 1 ,2,   , ,"",1
109, ,9e, ,  , ,1 - 3  ,4,   , ,"",1
111,1,4c, ,  , ,1 - 2  ,0,   , ,"",1
[SHEARS:no]
1
[shr_hgt,shr_test,shr_rslt,comment]
089,O,T,"M under crust"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
