[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Teepee Town"
.
97-12-10
12:30
"TA BW DV"
2275
M
.
NA
0
98102
Full
a
35
.
2
5
3
.
0
0
-9.0
47
0
[TEMPERATURES:no]
5
[temp_hgt,temp]
0,-1.0
10,-2.5
20,-4.5
30,-9.0
37,-11.0
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
7  
   
1 - 1.5
 ,""
0
[LAYERS:no]
4
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
021, ,5 , ,  , ,3      ,1,220, ,"Variable hardness",1
023, ,4 , ,  , ,3      ,3,210, ,"Depth hoar 3 - 5 under crust",1
036, ,4 , ,  , ,2      ,1,220, ,"",1
047, ,4 , ,  , ,1      ,0,160, ,"Surface hoar  6 below surface",1
[SHEARS:no]
0
[shr_hgt,shr_test,shr_rslt,comment]
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"No results with shear tests due to noncohesive snow."
