[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Teepee Town"
.
97-12-23
10:30
"TW  BW"
.
M
.
NA
0
98103
Full
a
60
40
3
2
4
.
0
0
-11.0
67
0
[TEMPERATURES:no]
7
[temp_hgt,temp]
0,-1.5
10,-2.5
20,-3.5
30,-4.5
40,-7.5
50,-9.5
57,-11.5
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1d 
.
2
0,""
0
[LAYERS:no]
10
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
017,0,5 , ,  , ,5      ,1,220, ,"",1
018,0,9e, ,5 , ,3-5    ,2,220, ,"    See Note 2",1
028,0,5 , ,  , ,3      ,1,210, ,"",1
040,0,4 , ,  , ,2      ,1,230, ,"",1
041,0,7 , ,4 , ,3      ,0,200,e,"   See Note 1",1
044,0,3 , ,  , ,.5     ,1,220, ,"",1
048,0,3 , ,9d, ,.5     ,3,250, ,"  Laminated Wind Crusts",1
050,0,3 , ,  , ,.5     ,1,220, ,"",1
063,0,2 , ,  , ,1-2    ,0,110, ,"",1
067,0,1 , ,  , ,2      ,0,060, ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
018,O,,""
040,O,,""
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"      Note 1: Old needle surface hoar (971208) mixed with large facetted grains .Comp /burp/and shear results moderate but clean."
""
"      Note 2: Old (9711) M/F crust turning to facetted lattice of depth hoar. Crust still holds together in places and gives irregular shear results and moderate collapse in comp."
""
""
