[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Teepee Town"
.
97-11-26
11:00
"PW SW"
2275
M
.
NA
0
98101
Full
a
.
.
1
0
3
.
0
0
-5
41
0
[TEMPERATURES:no]
5
[temp_hgt,temp]
0,-0.5
10,-1.4
20,-2.0
31,-3.5
41,-4.5
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
7  
2  
2-5
0,""
0
[LAYERS:no]
5
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
009,0,4 , ,5 , ,2-3    ,3,   , ,"",1
024,0,4 , ,  , ,1-2    ,0,   , ,"",1
027,0,4 , ,5 , ,1-2    ,2,   , ,"",1
037,0,4 , ,  , ,.5-1   ,1,   , ,"",1
041,0,2 , ,  , ,.5     ,0,   , ,"",1
[SHEARS:no]
1
[shr_hgt,shr_test,shr_rslt,comment]
023,S,M,"C in facettes"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
