[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Teepee Town"
.
98-03-03
14:00
"B. WHITE"
.
M
.
NA
0
98108
Full
a
20
10
2
2
4
.
1
1
-3.0
112
0
[TEMPERATURES:no]
12
[temp_hgt,temp]
0,-0.4
10,-1.3
20,-2.4
30,-3.1
40,-3.7
50,-3.9
60,-4.5
70,-5.1
80,-5.4
90,-5.4
102,-4.5
112,-2.4
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1 r
.
1.5
 ,""
0
[LAYERS:no]
9
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
015,0,5 , ,  , ,4-6    ,2,320, ,"Sintered and rounded",0
032,0,3 , ,  , ,2-3    ,2,230, ,"old striations",1
047,0,3 , ,  , ,2      ,3,330, ,"",1
055,0,3 , ,  , ,1.5    ,3,290, ,"",1
075,0,3 , ,  , ,1      ,3,310, ,"",1
087,0,4 , ,  , ,1.5    ,3,230, ,"",1
092,0,4 , ,  , ,2      ,2,210, ,"",1
108,0,2 , ,3 , ,.5     ,1,170, ,"",1
112,0,1 ,r,  , ,1.5    ,0,090, ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
015,O,H," Comp irreg Oct MF "
092,S,M,"in FC slightly less resist."
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"  Wellsettled midpack. Base of FC and DH very rounded and strong. 320 kg/m in DH! Suface layers most significant for further snowfalls."
""
""
""
