[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Teepee Town"
.
98-02-04
13:40
"GHI PW"
2275
M
.
.
0
98106
Full
a
.
.
2
6
3
.
0
0
-1
101
0
[TEMPERATURES:no]
12
[temp_hgt,temp]
0,-1.0
10,-2.0
20,-2.5
30,-4.0
40,-4.0
50,-5.0
60,-5.0
70,-6.0
80,-6.0
90,-5.0
91,-5.0
101,0.0
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
7  
.
2
1,""
0
[LAYERS:no]
8
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
013,0,5 , ,  , ,3-5    ,1,230, ,"",1
016,0,5 , ,  , ,3-4    ,1,230, ,"",1
033,0,4 , ,  , ,2      ,0,230, ,"",1
053,0,3 , ,4 , ,1      ,2,330, ,"",1
080,0,3 , ,4 , ,1-1.5  ,3,310, ,"",1
089,0,3 , ,  , ,.5-1   ,2,240, ,"",1
100,0,3 , ,  , ,.5-1   ,0,190, ,"",1
101,1,3 , ,  , ,1      ,0,   , ,"",1
[SHEARS:no]
1
[shr_hgt,shr_test,shr_rslt,comment]
013,O, ,"   CTH X1 @13-16"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
