[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Teepee Town"
.
98-03-18
12:30
"DV BW"
2275
M
.
NA
0
98109
Full
a
30
20
2
7
2
.
0
0
-2.0
136
0
[TEMPERATURES:no]
14
[temp_hgt,temp]
0,-0.2
10,-0.5
20,-0.9
30,-1.4
40,-1.7
50,-1.9
60,-2.3
70,-2.6
80,-3.0
90,-3.0
100,-3.9
110,-4.1
120,-6.0
126,-4.6
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
.
4
 ,"stellars"
0
[LAYERS:no]
8
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
037,0,5 , ,  , ,3-6    ,2,290, ,"Sintered and rounded",1
048,0,4 , ,  , ,1.5    ,3,330, ,"",1
079,0,3 , ,  , ,1.0    ,3,350, ,"",1
088,0,4c, ,  , ,1.5    ,3,300, ,"P-",1
094,0,4 , ,7 , ,1.5-2  ,2,240, ,"Old SH Feb 24 mixed in",1
107,0,3 , ,  , ,1      ,2,220, ,"",1
119,0,2 , ,  , ,1.0    ,1,160, ,"",1
136,0,1 , ,2 , ,1.5    ,0,120, ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
094,S,M,"See note 2"
119,S,E,"See Note 1"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"   Note 1: Burp easy and comp M(5) @ 119 on stellars/dendrites in storm snow. Will likely settle out rapidly with warm temps."
"  Note 2: Burp M and Comp H(4) on old Feb 24 interface. SH rounded and mixed in with faceted grains.   "
"  Numerous naturals running throughout day Size 1.5-2.5 mostly Southerly aspects, slabs new snow over crust. Also a couple of northerly aspects slabs suspect down to Feb 24 layer."
"Skier triggered size 2 in U2 (Goatseye OOB) while pit was being dug."
