[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Teepee Town"
.
98-03-31
12:30
"BW DV"
2275
M
.
NA
0
98110
Full
a
20
.
2
5
4
.
0
0
5.0
139
0
[TEMPERATURES:no]
15
[temp_hgt,temp]
0,-0.1
10,-0.3
20,-0.6
30,-0.9
40,-1.2
50,-1.4
60,-1.7
70,-1.9
80,-2.3
90,-2.8
100,-3.3
110,-3.7
120,-3.6
129,-2.9
139,0.0
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
2  
.
1.0
1,""
0
[LAYERS:no]
10
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
015, ,5 , ,  , ,3 - 4  ,2,320, ," rounded",1
034, ,5 , ,  , ,2 - 3  ,2,340, ," rounded",1
037, ,4c, ,  , ,1      ,4,440, ," old crust",1
058, ,4c, ,  , ,2      ,3,360, ,"",1
077, ,4c, ,  , ,1 - 2  ,3,380, ,"",1
095, ,4c, ,  , ,1.0    ,1,290, ,"",1
118, ,3 , ,  , ,0.5    ,2,260, ,"",1
119, ,9e, ,  , ,       ,4,   , ,"",1
135, ,2 , ,3 , ,0.5    ,1,200, ,"",1
139, ,2 , ,  , ,1.0    ,1,180, ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
095,O, ,"CTM on old SH 3 - 8"
119,O, ,"CTM @ 120 on crust"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
