[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Teepee Town"
.
98-04-15
12:00
"PW"
2275
M
.
NA
0
98111
Full
a
.
.
2
6
2
.
0
0
-5
142
0
[TEMPERATURES:no]
16
[temp_hgt,temp]
0,-1.0
10,-1.0
20,-2.0
30,-2.0
40,-2.5
50,-2.5
60,-3.0
70,-3.0
80,-3.5
90,-4.0
100,-4.0
110,-5.0
120,-8.0
130,-9.0
132,-8.0
142,-5.0
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
2  
1
0,""
0
[LAYERS:no]
12
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
039,0,5 , ,4 , ,3-4    ,2,280, ,"",1
044,0,4 , ,  , ,2      ,3,410, ,"",1
063,0,3 , ,4 , ,1-2    ,2,380, ,"",1
080,0,4 , ,3 , ,1      ,3,360, ,"",1
083,0,3 , ,  , ,1      ,3,300, ,"",1
098,0,3 , ,  , ,1-2    ,2,330, ,"",1
114,0,3 , ,  , ,.5     ,2,290, ,"",1
118,0,3 , ,4 , ,.5     ,3,270, ,"",1
130,0,3 , ,4 , ,.5     ,2,300, ,"",1
131,0,3 , ,4 , ,1.5    ,2,280, ,"",1
135,0,6 , ,  , ,1-2    ,4,340, ,"",1
142,0,2 , ,  , ,1      ,0,150, ,"",1
[SHEARS:no]
1
[shr_hgt,shr_test,shr_rslt,comment]
131, , ," CTM X4 on 1.5 facets"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
