[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Teepee Town"
.
98-01-07
13:30
"BW  DV"
2275
M
.
NA
0
98104
Full
a
90
35
1
0
4
.
1
2
-9.5
130
0
[TEMPERATURES:no]
13
[temp_hgt,temp]
0,-1.0
10,-2.0
20,-2.0
30,-2.5
40,-3.5
50,-4.5
60,-5.0
70,-6.0
80,-7.0
90,-7.5
100,-8.5
110,-9.0
120,-9.5
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1 r
.
1
0,""
0
[LAYERS:no]
8
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
018, ,5 , ,  , ,3      ,1,260, ,"",1
021, ,4 , ,9e, ,2 - 3  ,2,240, ,"  Note 2",1
042, ,4 , ,  , ,2      ,1,250, ,"",1
069, ,3 , ,  , ,0.5 - 1,2,270, ,"  Note 1",1
075, ,3 , ,  , ,0.5    ,2,260, ,"",1
093, ,2 , ,  , ,0.5    ,1,170, ,"  ",1
118, ,2 , ,1 , ,0.5 - 1,0,110, ,"",1
130, ,1 ,r,  , ,1      ,0,090, ,"  Several CTEs in HST",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
021,O,C,"TM, collapse"
093,S,M,"Also CTM"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
"Note 1: Surface hoar sz 6 - 8 at 55; clean shear obtained only by whacking column. Note 2: Nov crust still recognizable, but quite weak.    "
