[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Teepee Town"
.
98-02-19
13:30
"B. WHITE"
.
M
.
NA
0
98107
Full
.
20
5
2
6
4
.
0
0
0.0
104
0
[TEMPERATURES:no]
11
[temp_hgt,temp]
0,-1.0
10,-2.5
20,-3.0
30,-4.0
40,-4.5
50,-4.5
60,-5.0
70,-6.0
80,-6.0
90,-5.0
94,-5.0
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
2  
.
1
 ,""
0
[LAYERS:no]
6
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
035, ,5 , ,  , ,4-6    ,2,270, ,"rounded",1
054,0,4c, ,  , ,1.5    ,3,340, ,"",1
065,0,3 , ,  , ,.5     ,3,390, ,"",1
077,0,3 , ,  , ,.5-1   ,3,350, ,"",1
090,0,3c, ,  , ,1      ,2,270, ,"",1
104,0,2 , ,  , ,1      ,0,170, ,"",1
[SHEARS:no]
1
[shr_hgt,shr_test,shr_rslt,comment]
035,O,V,"ery Hard Comp/burp"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"      Very well settled midpack. DH at base rounding and sintering. Shear at 35 only produced with smashing with shovel (comp) or bashing aginst column (banzai burp)"
