[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Teepee Town"
.
98-04-30
13:00
"B. WHITE"
.
M
.
NA
0
98112
Other
a
0
0
1
0
6
.
0
0
8.0
118
0
[TEMPERATURES:no]
3
[temp_hgt,temp]
0,0.0
108,-0.1
118,-0.5
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
.
.
.
0,""
0
[LAYERS:no]
2
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
108,2,6c, ,  , ,       ,1,   , ,"",1
118,0,9e, ,  , ,       ,4,   , ,"",1
[SHEARS:no]
0
[shr_hgt,shr_test,shr_rslt,comment]
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
