[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Teepee Town"
.
98-01-22
13:20
"DV"
2275
M
.
NA
0
98105
Full
a
40
23
2
1
3
.
0
0
-6.5
118
0
[TEMPERATURES:no]
13
[temp_hgt,temp]
0,-1.0
10,-1.5
20,-2.0
30,-3.0
40,-4.0
50,-4.5
60,-5.0
70,-5.5
80,-6.0
90,-6.5
100,-7.0
110,-6.5
118,-5.5
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1 r
1 r
2
 ,""
0
[LAYERS:no]
11
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
016, ,5 , ,  , ,3 - 6  ,1,240, ,"",1
018, ,9e, ,  , ,3      ,3,   , ,"",1
037, ,4 , ,  , ,2 - 3  ,1,280, ,"",1
041, ,3 , ,  , ,0.5    ,3,350, ,"",1
052, ,4 , ,  , ,1      ,2,320, ,"",1
059, ,3 , ,  , ,0.5 - 1,3,300, ,"",1
063, ,3 , ,  , ,0.5    ,3,330, ,"",1
093, ,3 , ,  , ,0.5    ,2,250, ,"",1
097, ,2 , ,  , ,1      ,1,150, ,"",1
112, ,1 , ,2 , , 1 - 2 ,0,110, ,"",1
118, ,1 ,r,  , ,2      ,0,080, ,"",1
[SHEARS:no]
3
[shr_hgt,shr_test,shr_rslt,comment]
016, , ,"  CM, collapse"
052, , ," Old V sz 8"
093, , ,"CM, Note 1 "
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
"   Note 1: Failed on well preserved stellars."
