[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Vermillion"
.
98-02-12
12:00
"JO, RB, ML"
2100
M
.
SW
0
98303
Full
.
.
.
2
5
4
.
1
1
-4.9
147
0
[TEMPERATURES:no]
16
[temp_hgt,temp]
0,-0.5
10,-1.2
20,-1.6
30,-2.1
40,-2.6
50,-3.0
60,-3.3
70,-3.5
80,-3.7
90,-4.0
100,-4.1
110,-4.7
120,-5.4
130,-6.0
137,-5.8
147,-4.2
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
2  
.
1
 ,""
0
[LAYERS:no]
9
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
033,0,4 , ,5 , ,2-4    ,1,   , ,"",1
036,0,4 , ,  , ,2      ,3,   , ,"Nov crust?",1
055,0,4 , ,  , ,1-1.5  ,1,   , ,"",1
078,0,4 , ,  , ,.5     ,2,   , ,"",1
111,0,3 , ,  , ,.3     ,3,   , ,"",1
113,0,3 , ,  , ,.5     ,3,   , ,"",1
136,0,4 , ,  , ,.5     ,2,   , ,"",1
143,0,4 , ,7 , ,1      ,0,   , ,"SH to 3.0",1
147,0,2 , ,  , ,1      ,0,   , ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
055,S,H,"compression"
144,S,M,"burp @ 141"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
