[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Vermillion"
.
98-03-26
12:30
"TA DV"
2100
M
.
SW
0
98307
Full
a
40
20
2
6
3
.
1
1
1.0
187
0
[TEMPERATURES:no]
15
[temp_hgt,temp]
0,-0.6
20,-0.9
40,-1.3
60,-1.8
80,-2.0
100,-2.3
110,-2.4
120,-2.5
130,-2.5
140,-2.5
150,-2.5
160,-2.4
170,-1.5
177,-0.4
187,0.0
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
.
.
.
 ,""
0
[LAYERS:no]
13
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
020, ,5 , ,  , ,3      ,3,   , ,"",1
035, ,5 , ,  , ,2 - 3  ,2,   , ,"",1
037, ,9e, ,  , ,2 - 3  ,3,   , ,"",1
057, ,4 , ,  , ,2.0    ,2,   , ,"",1
105, ,4 , ,  , ,2.0    ,3,   , ,"",1
127, ,3 , ,  , ,1.0    ,3,   , ,"",1
148, ,3 , ,  , ,0.5    ,2,   , ,"",1
150, ,4c, ,  , ,3.0    ,3,   , ,"old SH",1
162, ,2 , ,  , ,0.5    ,2,   , ,"",1
164, ,9e, ,  , ,0.3    ,3,   , ,"",1
183,1,2 , ,  , ,0.5 - 1,1,   , ,"",1
186,1,2 , ,  , ,1.0    ,2,   , ,"",1
187,1,1f, ,  , ,1.5    ,0,   , ,"",1
[SHEARS:no]
3
[shr_hgt,shr_test,shr_rslt,comment]
115,S,M,"on old SH sz 3"
164,S,M," above crust on +"
174,S,M," on + 1.5"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
