[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Vermillion"
.
98-03-11
12:45
"GI DV"
2100
M
.
SW
0
98305
Full
a
.
27
1
0
4
.
1
1
-1.7
174
0
[TEMPERATURES:no]
18
[temp_hgt,temp]
0,-0.5
10,0.0
20,-1.2
30,0.0
40,-2.0
50,0.0
60,-3.0
70,0.0
80,-3.5
90,0.0
100,-4.0
110,-4.0
120,-4.2
130,-4.3
140,-4.5
150,-4.3
154,-3.6
164,-2.4
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
.
2-4
0,""
0
[LAYERS:no]
13
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
015,0,5 , ,  , ,2-4    ,3,290, ,"",1
032,0,5 , ,  , ,3      ,2,320, ,"",1
035,0,8 , ,  , ,       ,4,300, ,"",1
053,0,4 , ,  , ,2      ,2,320, ,"",1
104,0,3 , ,  , ,.5-1   ,3,410, ,"",1
108,0,3 , ,  , ,.5     ,3,330, ,"",1
118,0,3 , ,  , ,.5     ,3,290, ,"",1
132,0,  , ,3 , ,1      ,2,250, ,"",1
135,0,3 , ,  , ,.5     ,2,230, ,"",1
146,0,3 , ,2 , ,.5     ,1,210, ,"",1
168,0,1 , ,2 , ,1      ,0,130, ,"",1
171,0,1f, ,  , ,2-3    ,1,130, ,"",1
174,0,1 , ,  , ,1.5    ,0,110, ,"",1
[SHEARS:no]
4
[shr_hgt,shr_test,shr_rslt,comment]
134,O, ," CTM  @ 134"
150,S,M,"   STM  @ 150"
152,O, ,"  "
153,S,M,"  STM @ 153"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"Note 1  CTE @ 152"
