[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Vermillion"
.
98-02-25
13:40
"B. WHITE D. VOLKERS"
6800
F
.
SE
0
98304
Full
.
25
10
1
0
3
.
0
0
-3.0
155
0
[TEMPERATURES:no]
12
[temp_hgt,temp]
0,0.0
20,-0.5
40,-1.5
60,-2.0
80,-3.0
90,-3.5
100,-4.0
110,-5.0
120,-6.0
130,-7.0
140,-8.0
145,-8.0
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
.
.
.
 ,""
0
[LAYERS:no]
11
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
014,0,5 , ,3 , ,2      ,3,300,e,"",1
033,0,5 , ,  , ,3-6    ,2,280,e,"rounding",1
035,0,9 , ,  , ,       ,4,   , ,"old Oct MF Crust",1
054,0,4c, ,  , ,1.5    ,2,290,e,"",1
076,0,3 , ,  , ,.5     ,3,400,e,"",1
121,0,3 , ,  , ,.5     ,3,380,e,"",1
128,0,3 , ,7 , ,.5 4-6 ,3,340,e,"",1
136,0,2 , ,3 , ,.5     ,2,260,e,"",1
151,0,2 , ,  , ,1      ,1,220,e,"",1
153,0,2 , ,1f, ,1      ,1,180,e,"",1
155,0,7 , ,  , ,2-4    ,0,130,e,"",1
[SHEARS:no]
1
[shr_hgt,shr_test,shr_rslt,comment]
128,O,o,"mp H on V irreg."
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
G
[COMMENTS]
"  Very Strong well settled snowpack. Surface Hoar down 20cm. is mixed with other grains and not producing clean shear.  No other significant shears in pack."
""
""
