[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Wawa Bowl"
.
98-01-19
14:00
"BW DV"
2400
M
.
SE
29
98518
Test
a
45
.
2
3
4
.
1
1
.
54
0
[TEMPERATURES:no]
0
[temp_hgt,temp]
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
.
.
.
 ,""
0
[LAYERS:no]
5
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
008, ,4 , ,5 , ,       ,1,   , ,"",1
009, ,  , ,  , ,       ,3,   , ,"",1
018, ,4 , ,5 , ,       ,1,   , ,"",1
035, ,  , ,  , ,       ,2,   , ,"",1
054, ,  , ,  , ,       ,0,   , ,"",1
[SHEARS:no]
1
[shr_hgt,shr_test,shr_rslt,comment]
018, , ,"CE, RB3"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
