[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Wolverine Ridge"
.
98-04-07
14:00
"DV  RB"
7900
F
.
S
0
98535
Test
.
.
.
2
5
4
.
1
1
-3.0
93
0
[TEMPERATURES:no]
0
[temp_hgt,temp]
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
.
.
.
 ,""
0
[LAYERS:no]
6
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
013, ,  , ,  , ,       , ,   , ,"",1
064, ,  , ,  , ,       , ,   , ,"CTM@80.  weakest snow",1
067, ,  , ,  , ,       ,4,   , ,"CTM@34 under 3rd crust",1
081, ,  , ,  , ,       ,1,   , ,"CTM@26 top crust. FCs",1
088, ,  , ,  , ,       ,4,   , ,"CTM@12 under crust",1
093, ,  , ,  , ,       , ,   , ,"",1
[SHEARS:no]
0
[shr_hgt,shr_test,shr_rslt,comment]
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
