[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Vermillion"
.
99-02-24
10:40
"BW,MH"
2100
M
.
SW
0
99304
Full
a
25
.
3
7
4
.
1
1
-2.6
223
0
[TEMPERATURES:no]
13
[temp_hgt,temp]
110,-3.9
120,-4.3
130,-4.8
140,-5.2
150,-5.1
160,-5.9
170,-6.3
180,-6.6
190,-7.0
200,-7.2
210,-7.1
213,-4.1
223,-3.7
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
.
1
0,"rimed"
0
[LAYERS:no]
7
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
124,0,3 , ,  , ,.5     , ,   , ,"no tests done below",1
160,0,3 , ,  , ,.5     ,2,340, ,"P+",1
176,0,3 , ,  , ,.5     ,3,280, ,"",1
187,0,2 , ,3 , ,1      ,2,250, ,"",1
201,0,2 , ,  , ,1      ,2,190, ,"1F+",1
210,0,2 , ,  , ,2      ,1,110, ,"",1
223,0,2 , ,  , ,1      ,1,120, ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
201,S,M,"CTM on DF "
210,S,M,"CTM on + 2mm"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"Mod to strong winds creating soft slab at treeline and in alpine. Cornice test produces some failure along ridge which does not propogate very far. Substainal load on bedsurface below triggers class 1 small 10cm wind slab. No new activity seen today."
