[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Vermillion"
.
99-03-09
14:20
"AH MH"
2100
M
.
SW
0
99305
Full
a
20
10
2
6
2
.
0
0
-1.2
210
0
[TEMPERATURES:no]
12
[temp_hgt,temp]
100,-3.2
110,-3.5
120,-3.7
130,-4.0
140,-4.2
150,-4.8
160,-5.5
170,-6.4
180,-7.5
190,-7.2
200,-4.6
210,-3.0
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
7  
.
3
0,"SOME STELLARS"
0
[LAYERS:no]
7
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
137,0,3 , ,  , ,1      ,3,350, ,"no tests below",1
150,0,3 , ,  , ,.5     ,3,300, ,"",1
169,0,3 , ,  , ,.5     ,3,240, ,"",1
191,0,4 , ,3 , ,1      ,2,210, ,"",1
200,0,2 , ,4 , ,1-2    ,1,160, ,"",1
209,0,2 , ,4 , ,1-2    ,0,120, ,"",1
210,0,9c, ,  , ,       ,2,   , ,"",1
[SHEARS:no]
3
[shr_hgt,shr_test,shr_rslt,comment]
150,H,v,"ery hard shear "
190,M,D,"F & stellars 2- 2.5mm"
209,M,c,"ollapse"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"Surface hoar to size 3 +, suncrusts and facetted snow with a steep TG in the top 30 cm.  The surface is a mixxed bag of poor interfaces for the next storm cycle. Some pt. releases on South slopes. Glide cracks present in start zones. Ski cut steep rolls "
