[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Vermillion"
.
99-01-27
13:20
"BW, MH"
2100
M
.
SW
0
99303
Test
a
20
30
2
8
4
.
1
1
-12.6
200
0
[TEMPERATURES:no]
10
[temp_hgt,temp]
80,-3.0
100,-3.9
130,-5.2
140,-5.9
150,-6.9
160,-8.1
170,-10.0
180,-11.2
190,-12.6
200,-11.8
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
7  
2
0,""
0
[LAYERS:no]
11
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
060,0,4 , ,  , ,1      ,3,   , ,"",1
083,0,4c, ,  , ,1      ,3,   , ,"",1
092,0,4c, ,  , ,1      ,3,   , ,"",1
126,0,3 , ,  , ,.5     ,3,   , ,"P +",1
141,0,3 , ,  , ,1      ,3,   , ,"",1
150,0,3c, ,  , ,.5     ,3,   , ,"",1
163,0,3 , ,  , ,.5     ,3,   , ,"",1
170,0,3 , ,  , ,.5     ,2,   , ,"P -",1
178,0,2 , ,  , ,1      ,2,   , ,"",1
185,0,2 , ,4 , ,.5     ,1,   , ,"",1
200,0,2 , ,4 , ,.5-1   ,0,   , ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
140,S,H,"CTM 4 DF & RNDS"
170,S,E,"DF & FACETS"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"Strong mid pack with P + layers. No new natural activity. Slab building under cornices in targets. "
""
