[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Bow Summit"
.
99-02-11
12:30
"RW"
2030
M
.
NA
0
99206
Full
a
.
.
2
5
3
.
0
0
-10.5
141
0
[TEMPERATURES:no]
15
[temp_hgt,temp]
0,-0.1
10,-0.1
20,-0.5
30,-0.7
40,-1.1
50,-1.6
60,-1.9
70,-2.5
80,-3.1
90,-4.0
100,-5.7
110,-7.6
120,-10.1
131,-13.0
141,-9.3
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
4  
.
0.5-1
0,""
0
[LAYERS:no]
16
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
004,0,8 , ,  , ,       ,4,   , ,"",1
008,0,5 , ,  , ,2-3    ,3,410, ,"",1
011,0,4 , ,  , ,1-2    ,3,   , ,"",1
015,0,4 , ,  , ,2-4    ,2,350, ,"some striations",1
020,0,4 , ,  , ,2      ,3,370, ,"",1
031,0,4 , ,  , ,1-2    ,3,350, ,"",1
062,0,4 , ,  , ,1.5    ,3,320, ,"",1
066,0,4 , ,  , ,1      ,2,340, ,"",1
069,0,4 , ,  , ,1      ,3,   , ,"",1
101,0,4 , ,  , ,0.5-1  ,3,320, ,"",1
104,0,3 , ,4 , ,0.3    ,3,   , ,"",1
116,0,2 , ,4 , ,1/0.5  ,3,223, ,"",1
119,0,2 , ,4 , ,1.5/1  ,1,   , ,"",1
121,0,3 , ,4 , ,0.3    ,2,   , ,"",1
126,0,4 , ,2 , ,0.5/1  ,1,220, ,"",1
141,0,2 , ,4 , ,1/0.5  ,0,150, ,"",1
[SHEARS:no]
3
[shr_hgt,shr_test,shr_rslt,comment]
004,O,C,"T H6"
104,O,C,"T H1"
121,O,C,"T M4 & M5"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
