[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Bottom of Purple Bowl"
.
99-02-03
13:30
"BW, DI, ML"
2290
M
.
W
25
99521
Test
.
.
.
2
7
4
.
0
0
-9.5
105
0
[TEMPERATURES:no]
5
[temp_hgt,temp]
0,-2.4
20,-3.2
50,-4.0
80,-6.5
95,-7.0
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
.
.
.
 ,""
0
[LAYERS:no]
6
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
027, ,  , ,  , ,       ,3,   , ,"",1
037, ,  , ,  , ,       ,3,   , ,"",1
069, ,  , ,  , ,       ,2,   , ,"1F+",1
075, ,  , ,  , ,       ,2,   , ,"",1
086, ,  , ,  , ,       ,1,   , ,"4F+",1
105, ,  , ,  , ,       ,3,   , ,"",1
[SHEARS:no]
1
[shr_hgt,shr_test,shr_rslt,comment]
086,O,C,"TM2 repeated twice"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
