[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Chickidy Valley"
.
99-03-04
12:40
"RW"
2380
M
.
SE
21
99525
Test
a
60
.
2
3
3
.
0
0
-7.5
240
1
[TEMPERATURES:no]
12
[temp_hgt,temp]
0,-5.4
10,-1.0
20,-1.8
30,-2.9
40,-3.2
50,-2.8
60,-2.4
70,-1.7
80,-1.9
90,-1.9
100,-1.5
110,-1.3
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1f 
.
2
0,""
0
[LAYERS:no]
5
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
004,0,1 , ,  , ,2      ,0,   , ,"",1
027,0,1 , ,2 , ,2/1.5  ,0,   , ,"",1
055,0,3 , ,2 , ,0.5/1.0,2,   , ,"",1
061,0,4c, ,  , ,1.0-1.5,3,   , ,"Variable MF ?",1
115,0,4c, ,  , ,1.0-1.5,2,   , ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
022,O,C,"T M(2)"
048,O,C,"T H(2) DF 1-2"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
