[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Borgeau 6 & 7 Ridge"
.
98-12-08
13:20
"TA BW"
6950
F
.
NE
30
99507
Test
a
40
20
2
8
2
.
0
0
-9.4
65
0
[TEMPERATURES:no]
8
[temp_hgt,temp]
0,-1.2
10,-1.7
20,-2.8
30,-3.4
40,-5.2
50,-7.6
55,-10.2
65,-13.0
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1 r
1f 
1-2
0,""
0
[LAYERS:no]
8
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
009,0,5 , ,9e, ,4      ,2,180, ,"rotting crust",1
021,0,4 , ,  , ,1.5    ,2,210, ,"",1
037,0,3 , ,  , ,.5-1   ,2,210, ,"some FC",1
044,0,3 , ,4 , ,1      ,1,120, ,"",1
045,0,7 , ,  , ,4      ,1,100,e,"",1
058,0,4c, ,  , ,1      ,1,120, ,"",1
063,0,4 , ,  , ,1-2    ,0,055, ,"",1
065,0,1 , ,  , ,1.5    ,0,055, ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
009,O,C,"T H2  see note"
045,R,4,""
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"    Crust at base decomposing into DH. Rutschblock broke at both 45 and 9 simultaneously."
