[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Bow Summit"
.
98-12-15
10:30
"MH"
2030
M
.
.
0
99203
Full
a
30
20
1
0
8
.
1
1
-9.3
87
0
[TEMPERATURES:no]
10
[temp_hgt,temp]
0,-0.8
10,-1.2
20,-1.6
30,-1.9
40,-2.5
50,-3.2
60,-3.7
70,-6.9
77,-8.2
87,-9.7
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
.
1
0,""
0
[LAYERS:no]
9
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
002,0,9e, ,  , ,       ,4,   , ,"",1
005,0,4 , ,  , ,2      ,1,200, ,"STRIATIONS ",1
007,0,3 , ,4 , ,1      ,3,340, ,"",1
031,0,4 , ,  , ,1      ,3,310, ,"",1
038,0,4 , ,  , ,.5-1   ,2,270, ,"",1
057,0,4 , ,  , ,1      ,2,210, ,"",1
067,0,3 , ,  , ,.5     ,2,130, ,"",1
074,0,2 , ,3 , ,.5-1   ,1,110, ,"",1
087,0,2 , ,  , ,.5-1   ,0,110, ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
005,S,H,"ST & comp H comp 2 "
067,S,M,"comp M 2 on V"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
F
[COMMENTS]
"Snowpack in study plot plot very tight. Moderate Comp test gets uneven break on November 30 surface hoar. (broken arms visible but breaking down). Hard on both Comp and Shear in facets above melt freeze. Striations are forming, but not quite depth hoar y"
""
"Lots of wind transport in apline, 1 class 2 nat south aspect from steep rocky terrain, alp, on old windslab .( Observation Peak ) "
