[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Bow Summit"
.
98-12-03
11:53
"MH IP"
2030
M
.
.
0
99202
Full
a
40
.
1
0
3
.
1
1
-6.5
86
0
[TEMPERATURES:no]
10
[temp_hgt,temp]
0,-0.1
10,-1.3
20,-1.8
30,-2.6
40,-3.3
50,-4.1
60,-6.0
70,-8.2
76,-7.9
86,-7.7
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
2  
1
0,""
0
[LAYERS:no]
8
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
006,0,9e, ,  , ,       ,4,360, ,"possible DH conglomerate",1
007,0,4 , ,  , ,2      ,1,270,e,"",1
009,0,3 , ,  , ,1      ,2,270,e,"",1
022,0,3 , ,  , ,.5     ,3,290, ,"",1
038,0,3 , ,  , ,.5     ,3,240, ,"",1
049,0,3 , ,  , ,.5     ,2,190, ,"",1
066,0,3 , ,4 , ,.5     ,1,160, ,"",1
086,0,2 , ,4 , ,.5-1   ,0,100, ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
006,S,M," on FC @ 2"
059,S,M,"comp M 4"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
F
[COMMENTS]
"The mid is very strong with rounded pencil layers. There was no new evidence of natural activity along the 93 N and little wind transport recently. The facet layer above the crust is still the reacting layer of concern.  "
