[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Bow Summit"
.
98-11-24
12:30
"MH GHI"
2030
M
.
.
0
99201
Full
a
30
.
3
6
4
.
1
1
-3.5
60
0
[TEMPERATURES:no]
7
[temp_hgt,temp]
0,-0.7
10,-1.2
20,-2.3
30,-3.1
40,-4.0
50,-3.1
60,-3.1
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
.
2-2.5
0,""
0
[LAYERS:no]
5
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
007,0,5 , ,  , ,3      ,1,260, ,"",1
014,0,3 , ,  , ,.5-1   ,2,270, ,"",1
027,0,3 , ,  , ,1      ,2,200, ,"",1
046,0,2 , ,3 , ,1.5    ,1,140, ,"",1
060,0,2 , ,  , ,1-1.5  ,0,050, ,"",1
[SHEARS:no]
3
[shr_hgt,shr_test,shr_rslt,comment]
000,S,E,"SE @ GRND"
037,S,E,"SC E 9 @ 37"
049,S,E,"SC E 5 @ 49"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
F
[COMMENTS]
"Crust observed on Bow Summit slopes not found at study plot. Depth hoar has formed above ground and is the main reactive layer. Mid pack is strong for this time of year. Gusty winds hitting strong are transporting snow and helping in slab formation.  "
