[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Bow Summit Ski Hill"
.
98-11-22
09:45
"GHI"
.
M
.
NE
0
99501
Test
a
45
45
2
5
3
.
0
0
-4.2
58
0
[TEMPERATURES:no]
0
[temp_hgt,temp]
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
.
.
.
 ,""
0
[LAYERS:no]
3
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
007, ,4 , ,4 , ,       , ,   , ,"st-e @ 7",1
041, ,2 , ,  , ,       , ,   , ,"st - e @ 41",1
058, ,1 , ,2 , ,       , ,   , ,"",1
[SHEARS:no]
0
[shr_hgt,shr_test,shr_rslt,comment]
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"Major settlements while breaking trail and for first skiers down slope.  Ski cut steep section with NR.  No observed natural activity.   2nd day for area to be open for the season."
