[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Bow Summit"
.
99-01-14
12:18
"PW BW RW"
2030
M
.
.
0
99205
Full
a
.
.
2
6
4
.
1
4
-4.5
125
0
[TEMPERATURES:no]
14
[temp_hgt,temp]
0,-0.1
10,-0.3
20,-1.0
30,-0.9
40,-1.5
50,-2.0
60,-2.4
70,-3.0
80,-3.7
90,-4.0
100,-4.0
110,-4.0
115,-4.0
125,-2.0
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1 r
.
1-1.5
0,""
0
[LAYERS:no]
7
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
012,0,4 , ,5 , ,2-3    ,2,300, ,"",1
033,0,4c, ,  , ,1-2    ,3,350, ,"",1
064,0,4c, ,  , ,.5-1   ,2,290, ,"",1
074,0,4c, ,  , ,.5     ,3,270, ,"",1
091,0,3 , ,  , ,.5     ,2,200, ,"",1
113,0,1 ,r,2 , ,1      ,1,080, ,"",1
125,0,1 ,r,  , ,1.5-2  ,0,040, ,"",1
[SHEARS:no]
3
[shr_hgt,shr_test,shr_rslt,comment]
064,S,H," Comp test H x7 @ 64"
074,S,H," Comp test H x5 @ 74"
091,S,M,""
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"Snowing @ 4cm/hr over profile time, heard avalanches running, visibility obscured."
