[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Bow Summit"
.
99-01-28
12:20
"MH"
2030
M
.
.
0
99206
Full
b
30
.
2
7
4
.
1
1
-9.6
110
0
[TEMPERATURES:no]
12
[temp_hgt,temp]
0,-0.9
10,-1.4
20,-1.9
30,-2.4
40,-3.1
50,-3.7
60,-4.3
70,-5.8
80,-7.5
90,-8.5
100,-9.5
110,-8.9
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
.
1-1.5
0,"rimed"
0
[LAYERS:no]
9
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
003, ,9 , ,  , ,       ,4,   , ,"discontinous",1
028,0,4 , ,  , ,2      ,3,390, ,"",1
060,0,4 , ,  , ,1-2    ,2,310, ,"",1
063,0,4 , ,  , ,1      ,3,350, ,"P +",1
078,0,4 , ,  , ,1      ,3,290, ,"",1
083,0,4 , ,  , ,.5-1   ,3,260, ,"",1
094,0,4 , ,  , ,1-1.5  ,2,200, ,"",1
100,0,4 , ,  , ,1      ,1,180, ,"",1
110,0,2 , ,  , ,1.5    ,0,105, ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
060,S,M,"Shear on facets 1mm"
100,S,E,"burp DF & SH 1-3mm"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"Surface Hoar is variable in location even within the study plot. Shear will become a concern with more HN.  The weak temperature gradient is present promoting stronger bonding, which is evident in the mid pack. "
""
"No new natural avalnches seen today. Limited new snow and  Light to moderate winds."
