[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Bow Summit ski hill"
.
98-11-26
15:30
"MH PW"
7200
F
.
NE
24
99503
Test
a
97
.
3
6
4
.
1
3
-4
97
0
[TEMPERATURES:no]
0
[temp_hgt,temp]
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
.
1
 ,""
0
[LAYERS:no]
7
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
012, ,4 , ,  , ,2      ,1,   , ,"",1
016, ,4 , ,  , ,2      ,3,   , ,"",1
046, ,  , ,  , ,       ,2,   , ,"",1
050, ,  , ,  , ,       ,2,   , ,"",1
072, ,  , ,  , ,       ,1,   , ,"",1
095, ,  , ,  , ,       ,0,   , ,"",1
097, ,  , ,  , ,       ,1,   , ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
000,R,2,""
016,R,2,"top of Oct MF crust"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"RB 2 on size 1 facets on top of old MF crust & @ ground on size 2 facets.  Simultaneous releases."
