[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Bow Summit ski hill"
.
98-12-26
11:11
"PW"
2300
M
.
E
28
99512
Test
a
.
.
3
7
4
.
1
2
-8
94
0
[TEMPERATURES:no]
11
[temp_hgt,temp]
0,-2.0
10,-3.0
20,-5.0
30,-6.0
40,-8.0
50,-9.0
60,-10.0
70,-11.0
80,-12.0
84,-12.0
94,-10.0
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
2  
1
 ,""
0
[LAYERS:no]
10
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
010,0,4 , ,5 , ,1-3    ,2,   , ,"",1
013,0,4 , ,  , ,.5-1   ,2,   , ,"old MF crust",1
023,0,4 , ,  , ,1.5    ,2,   , ,"1F easy",1
037,0,4 , ,  , ,1-1.5  ,2,   , ,"",1
050,0,4 , ,  , ,1      ,2,   , ,"",1
054,0,4 , ,  , ,1      ,2,   , ,"",1
064,0,4 , ,  , ,.5     ,3,   , ,"",1
076,0,4 , ,  , ,.5-1   ,2,   , ,"",1
090,0,4 , ,  , ,1      ,0,   , ,"",1
094,0,2 , ,  , ,.5-1   ,1,   , ,"",1
[SHEARS:no]
1
[shr_hgt,shr_test,shr_rslt,comment]
080,S,M,""
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"Mod comp X1 @ 80  next number is 99513"
