[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Bow Summit ski hill"
.
98-12-17
12:30
"MH TM"
7200
F
.
NE
28
99507
Test
a
60
.
3
7
3
.
1
1
-9.1
146
0
[TEMPERATURES:no]
15
[temp_hgt,temp]
0,-0.6
10,-1.3
20,-1.5
30,-2.0
40,-2.4
50,-2.8
60,-3.4
70,-3.8
80,-4.0
90,-4.6
100,-5.3
120,-5.4
130,-6.1
136,-8.1
146,-10.5
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
.
2
0,""
0
[LAYERS:no]
11
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
004,0,5 , ,  , ,2-3    ,1,   , ,"",1
010,0,9e, ,  , ,       ,4,   , ,"discontinous crust",1
012,0,4 , ,  , ,2      ,1,   , ,"striations forming",1
016,0,4 , ,  , ,1      ,3,   , ,"",1
050,0,3 , ,4 , ,1      ,3,   , ,"",1
075,0,3 , ,  , ,1      ,3,   , ,"",1
088,0,3 , ,  , ,.5     ,3,   , ,"",1
098,0,3 , ,  , ,       ,2,   , ,"",1
105,0,3 , ,  , ,.5     ,2,   , ,"",1
123,0,3 , ,  , ,.5     ,1,   , ,"",1
146,0,2 , ,  , ,1.5-2  ,0,   , ,"",1
[SHEARS:no]
3
[shr_hgt,shr_test,shr_rslt,comment]
004,S,H,"comp H 1 "
105,S,M,"comp M 4"
123,S,E,"comp E 5"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
F
[COMMENTS]
"Mod shear @ 105 looks like it occurred on Nov. 29 surface hoar. RB 5 shears @ 105 and 123 simultanneously. Lots of wind and snow transport with the coming of the Arctic front. Soft slab developing on lee slopes. Boot out 4 snow boarders who built a big kicker under wind loaded slope. Soft slab developing as they huck air! "Hey man my friend said it was safe !" "
