[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Bow Summit ski hill"
.
98-11-24
11:30
"GHI MH GP SM"
7200
F
.
NE
24
99502
Test
a
.
30
3
6
4
.
1
2
-4.5
56
0
[TEMPERATURES:no]
7
[temp_hgt,temp]
0,-0.7
10,-1.4
20,-1.9
30,-2.8
40,-3.7
46,-4.5
56,-3.7
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
.
2
0,""
0
[LAYERS:no]
5
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
008,0,4 , ,5 , ,3-4    ,0,   , ,"",1
009,0,9e, ,  , ,       ,4,   , ,"",1
028,0,2 , ,3 , ,.5-1   ,2,   , ,"",1
049,0,2 , ,  , ,1.5    ,0,   , ,"",1
056,0,1 , ,2 , ,1-1.5  ,0,   , ,"",1
[SHEARS:no]
1
[shr_hgt,shr_test,shr_rslt,comment]
009,S,E,"CR INTERFACE"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
F
[COMMENTS]
"Moderate swirling winds, reaching high in alpine. Snow transport is apparent. Settlement around trees as mid-pack settles with skier weight. Mid pack is strenghtening over last 48 hrs, as ski pen. is reducing. Melt freeze crust is discontinous depending "
