[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Bow Summit ski hill"
.
99-01-29
12:10
"PW, MH "
7200
F
.
NE
32
99519
Test
a
60
.
3
6
4
.
1
3
-4.6
255
0
[TEMPERATURES:no]
0
[temp_hgt,temp]
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
.
2
0,""
0
[LAYERS:no]
6
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
201, ,  , ,  , ,       ,3,   , ,"",1
209, ,  , ,  , ,       ,2,   , ,"",1
225, ,  , ,  , ,       ,1,   , ,"1F -",1
229, ,1 , ,2 , ,       ,2,   , ,"4 F +",1
247, ,1 , ,2 , ,       ,1,   , ,"",1
255, ,1 , ,  , ,       ,1,   , ,"",1
[SHEARS:no]
3
[shr_hgt,shr_test,shr_rslt,comment]
201,R,2,"DF size 1 - 1.5mm"
225,S,M,"CTM 6"
242,S,M,"CTM 2 "
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
P
[COMMENTS]
"RB 2, SSL developing on lee features. Numerous class 2 nat. aval. observed on 93 N SW aspect. Winds Mod. to Strong. "
