[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Bow Summit"
.
99-02-25
14:15
"MH"
2030
M
.
.
0
99207
Full
a
35
.
1
0
2
.
0
0
-2.0
152
0
[TEMPERATURES:no]
16
[temp_hgt,temp]
0,-0.7
10,-1.2
20,-1.5
30,-2.0
40,-2.5
50,-2.9
60,-3.3
70,-3.7
80,-3.9
90,-4.6
100,-4.9
110,-5.1
120,-4.6
130,-3.9
140,-3.7
152,-5.9
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
.
2
0,"rimed"
0
[LAYERS:no]
9
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
014,0,5 , ,4 , ,2-3    ,3,300, ,"conglomerate",1
022,0,4 , ,  , ,2-3    ,3,320, ,"rnding",1
052,0,4 , ,  , ,2      ,3,350, ,"transition to rnds",1
079,0,3 , ,  , ,1.5    ,3,310, ,"",1
110,0,4 , ,3 , ,1-1.5  ,3,290, ,"",1
126,0,4 , ,  , ,1      ,2,220, ,"",1
130,0,3 , ,4 , ,.5     ,1,150, ,"",1
140,0,1c, ,1d, ,2      ,0,080, ,"",1
152,0,1 , ,2 , ,1      ,0,090, ,"",1
[SHEARS:no]
1
[shr_hgt,shr_test,shr_rslt,comment]
130,S,M,"CTM on + and DF 1.5-2 "
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"New snow reacting to Mod comp tests and burp tests.Shearing above wind layer. Avalanche activity: pt. releases from steep terrain gaining enough volume to reach 2/3 runnout. Slab activity around Bow Summit in cross loaded East aspect features. Crown heights between 20 and 40 cm, 10 and 35m wide.  "
