[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Bow Summit"
.
99-03-11
09:30
"PW"
2030
M
.
.
0
99209
Full
a
.
.
1
0
2
.
.
0
-17
136
0
[TEMPERATURES:no]
15
[temp_hgt,temp]
0,-0.2
10,-1.3
20,-1.8
30,-2.1
40,-2.6
50,-3.2
60,-4.0
70,-4.6
80,-5.5
90,-6.3
100,-7.1
110,-8.6
120,-12.9
126,-15.8
136,-17.7
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
7  
.
2
 ,""
0
[LAYERS:no]
11
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
008, ,3 , ,4 , ,1-2    ,2,300, ,"",1
017, ,3 , ,4 , ,1-3    ,3,350, ,"",1
028, ,3 , ,4 , ,1-2    ,2,360, ,"",1
060, ,3 , ,4 , ,2      ,2,300, ,"",1
076, ,3 , ,3 , ,1.5    ,2,360, ,"",1
088, ,3 , ,4 , ,1-2    ,2,320, ,"",1
090, ,3 , ,4 , ,2      ,2,   , ,"",1
104, ,3 , ,4 , ,.5-1   ,2,350, ,"",1
118, ,4 , ,  , ,1      ,2,240, ,"",1
132, ,4 , ,  , ,1-2    ,0,130, ,"",1
136, ,4 , ,  , ,.5-1   ,0,   , ,"",1
[SHEARS:no]
0
[shr_hgt,shr_test,shr_rslt,comment]
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
