[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Corral Cr 1"
.
98-11-27
12:00
"MH ML PW"
2200
M
.
SE
30
99504
Test
a
.
.
1
0
3
.
0
0
-1.2
69
0
[TEMPERATURES:no]
0
[temp_hgt,temp]
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
2  
1.5-2
 ,""
0
[LAYERS:no]
4
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
016, ,3 , ,4 , ,.5     ,2,   , ,"",1
029, ,3 , ,  , ,.5     ,2,   , ,"",1
045, ,2 , ,3 , ,.5     ,2,   , ,"",1
069, ,2 , ,  , ,1.5    ,0,   , ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
000,R,4,""
029,S,E,"Burp test"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"R4 @ ground on heather, no Oct MF crust @ this location"
