[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Crowfoot glades"
.
98-12-27
11:32
"PW"
2200
M
.
S
30
99513
Test
b
.
.
3
6
4
.
1
2
-10
112
0
[TEMPERATURES:no]
13
[temp_hgt,temp]
0,-1.0
10,-3.0
20,-4.0
30,-5.0
40,-6.0
50,-7.0
60,-8.0
70,-9.0
80,-10.0
90,-11.0
100,-10.0
102,-10.0
112,-10.0
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
.
.5
 ,""
0
[LAYERS:no]
8
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
020, ,4 , ,  , ,1-1.5  ,2,   , ,"",1
040, ,4 , ,  , ,1      ,3,   , ,"",1
056, ,4 , ,  , ,.5-1   ,2,   , ,"",1
070, ,4 , ,  , ,.5     ,3,   , ,"",1
093, ,4 , ,  , ,1      ,1,   , ,"",1
107, ,4 , ,  , ,       ,2,   , ,"",1
108, ,4 , ,  , ,       ,2,   , ,"",1
112,0,2 , ,  , ,.5     ,3,   , ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
093,S,M,"  SM @ 93"
108,S,E," SE @ 108"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"Comp H X1 @93  next pit 99514"
