[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Chikadee Valley"
.
98-12-28
13:00
"BW TA RW"
6200
F
.
S
20
.
Test
a
65
20
2
7
4
.
1
2
-12.0
109
0
[TEMPERATURES:no]
0
[temp_hgt,temp]
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
.
2
 ,""
0
[LAYERS:no]
7
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
043, ,  , ,  , ,       ,3,   , ,"",1
056, ,  , ,  , ,       ,2,   , ,"",1
074, ,  , ,  , ,       ,2,   , ,"",1
082,0,4 , ,  , ,1.5    ,1,210, ,"",1
094,0,2 , ,  , ,1.0    ,1,120, ,"",1
103,0,1 , ,  , ,2.0    ,0,090, ,"",1
109,0,1 , ,  , ,1.5    ,0,060, ,"",1
[SHEARS:no]
0
[shr_hgt,shr_test,shr_rslt,comment]
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
