[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Cathedral Mtn."
.
99-01-26
14:14
"BW, MH"
6500
F
.
NW
22
99518
Test
b
15
10
1
0
2
.
0
0
-9.0
121
0
[TEMPERATURES:no]
10
[temp_hgt,temp]
0,-1.1
20,-1.9
40,-2.8
50,-3.3
60,-4.0
70,-4.8
80,-6.5
90,-7.9
100,-9.7
110,-10.8
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
2  
4  
.
0,""
0
[LAYERS:no]
11
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
009,0,9 , ,  , ,       ,3,   , ,"",1
023,0,  , ,  , ,       ,3,   , ,"",1
034,0,  , ,  , ,       ,3,   , ,"P +",1
053,0,  , ,  , ,       ,3,   , ,"",1
061, ,  , ,  , ,       ,3,   , ,"P +",1
085, ,  , ,  , ,       ,3,   , ,"",1
088, ,4 , ,  , ,       ,3,   , ,"",1
096, ,  , ,  , ,       ,3,   , ,"P -",1
103, ,  , ,  , ,       ,3,   , ,"",1
109, ,  , ,  , ,       ,3,   , ,"",1
117,0,4 , ,  , ,.5-1   ,1,   , ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
088,S,H,"CTH ON FC"
117,S,M,"FC AND V"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"Variable wind crusts sometimes supported by facets. 1 natural sz 1 in top of gully. Alpine and treeline blasted by wind at this Divide site."
