[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Vermilion"
.
99-01-13
13:00
"BW,GHI,KS"
.
M
.
NA
0
99302
Full
a
57
28
2
6
4
.
0
0
-6.7
183
0
[TEMPERATURES:no]
19
[temp_hgt,temp]
0,-0.1
20,-0.9
30,-1.3
40,-1.5
50,-1.9
60,-2.3
70,-2.6
80,-3.0
90,-3.3
100,-3.5
110,-3.8
120,-4.0
130,-3.9
140,-4.3
150,-5.3
160,-7.0
170,-9.9
173,-10.1
183,-8.8
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
2  
.
1.0
 ,""
0
[LAYERS:no]
9
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
015, ,5 , ,  , ,3.0    ,3,270, ,"CTHx10 @ 14, STH @ 10 ",1
035, ,4 , ,4c, ,1.5    ,3,370, ,"",1
060, ,4 , ,4c, ,1.0    ,3,340, ,"",1
092, ,3 , ,  , ,1.0    ,3,270, ,"",1
120, ,3 , ,  , ,.5     ,3,220, ,"",1
150, ,2 , ,3 , ,.5 - 1 ,2,180, ,"STH @ 149, CTMx6 @ 149",1
159, ,2 , ,  , ,1.5    ,2,160, ,"",1
170, ,2 , ,  , ,1.0    ,1,140, ,"CTEx10 @ 171",1
183, ,2 , ,  , ,1.0    ,0,120, ,"",1
[SHEARS:no]
0
[shr_hgt,shr_test,shr_rslt,comment]
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"DH from 0 -15 is rounded and fused, with a remnant of old crust at 15"
"STH at 149 is on stellars and dentrites 1.5 - 2.0"
"Some old FC @ 60"
