[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Chickadee Valley"
.
98-12-28
13:00
"BW TA RW"
6200
F
.
S
20
99512
Test
a
65
20
2
7
4
.
1
2
-12.0
109
0
[TEMPERATURES:no]
12
[temp_hgt,temp]
0,-0.5
10,-1.3
20,-1.9
30,-2.6
40,-3.5
50,-3.7
60,-5.2
70,-5.9
80,-7.3
90,-9.9
99,-12.1
109,-12.9
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
.
2
 ,""
0
[LAYERS:no]
7
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
043,0,4 , ,5 , ,2.5    ,3,310, ,"",1
056,0,4 , ,  , ,2      ,2,280, ,"",1
074,0,4 , ,  , ,1.5-2  ,2,240, ,"",1
082,0,4 , ,  , ,1.5    ,1,210, ,"",1
094,0,2 , ,  , ,1.0    ,1,120, ,"",1
103,0,1 , ,  , ,2.0    ,0,090, ,"",1
109,0,1 , ,  , ,1.5    ,0,060, ,"",1
[SHEARS:no]
3
[shr_hgt,shr_test,shr_rslt,comment]
076,S,C,"TM STM irreg in FC"
080,R,4,"FC from 981223"
094,O,T,"E 4 on stellars"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"HN still loose and unconsolidated at pit location.  Natural avalanches approx 40cm thick X 200m wide running across valley on lee fans below cliffs triggered by sluffing. 981223 FC major layer of concern and suspected bed surface for avalanches. Lower pack FC but strong. No SH or Oct CR."
