[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Goat's Eye Plot"
.
98-12-22
12:50
"RW/MH"
2300
M
.
.
0
19103
Full
a
.
.
2
7
4
.
1
2
-16.9
92
0
[TEMPERATURES:no]
11
[temp_hgt,temp]
0,-0.5
10,-3.0
20,-3.2
30,-5.5
40,-7.0
50,-10.5
60,-12.5
70,-15.5
80,-18.6
82,-17.5
92,-15.7
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1b 
1c 
1
0,""
0
[LAYERS:no]
10
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
008,0,5 , ,  , ,2-4    ,2,230, ,"",1
010, ,9e, ,  , ,       ,3,   , ,"mfc decomposing",1
021,0,4 , ,  , ,1-1.5  ,3,330, ,"",1
034,0,4 , ,  , ,1      ,3,330, ,"",1
047,0,4 , ,  , ,1      ,2,320, ,"",1
057,0,4 , ,  , ,1      ,2,290, ,"",1
070,0,4 , ,  , ,1      ,1,230, ,"",1
082,0,4 , ,  , ,1      ,0,190, ,"",1
090,0,4 , ,  , ,0.5-1  ,0,160, ,"",1
092,0,1 , ,  , ,1      ,0,   , ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
000,S,H,""
082,O,C,"T M(8)"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"Strong thermal gradient throughout the pack.  Cold temps faceting the snowpack.   No new avalanche observations.                                                                                                                                              "
""
""
""
