[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Goat's Eye Plot"
.
98-12-12
13:00
"ML/RW"
2300
M
.
.
0
99102
Full
a
47
.
2
1
4
.
1
1
-4.5
84
0
[TEMPERATURES:no]
10
[temp_hgt,temp]
0,-0.5
10,-1.2
20,-1.7
30,-2.3
40,-3.0
50,-3.7
60,-4.6
70,-5.8
74,-5.4
84,-5.5
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
2  
1
0,""
0
[LAYERS:no]
7
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
010,0,5 , ,4 , ,2-3    ,2,   , ,"",1
018,0,4 , ,  , ,2      ,3,   , ,"P+ MF crust Oct 30th",1
024,0,3 , ,  , ,1      ,3,   , ,"",1
037,0,3 , ,  , ,1      ,3,   , ,"",1
056,0,3 , ,  , ,1      ,2,   , ,"1F+",1
082,0,3 , ,  , ,0.5    ,0,   , ,"",1
084,0,1 , ,2 , ,1      ,0,   , ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
074,O,M," Burp test"
079,O,M," Burp test"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"No observed new avalanches on the way to the profile site. At this location snow temps and temp gradients are both good. The upper snow pack is settling  and consolidating into a rounded mid pack above a faceted and depth hoar base. Snow is still available for wind transportation."
""
" "
""
""
