[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Goat's Eye Plot"
.
99-02-04
11:20
"BW ML"
2300
M
.
W
0
99105
Full
a
50
20
2
7
4
.
1
1
-8.3
178
0
[TEMPERATURES:no]
12
[temp_hgt,temp]
0,-0.4
20,-1.6
40,-2.3
60,-3.3
80,-4.0
100,-5.1
120,-6.3
140,-7.3
150,-7.9
160,-8.3
168,-7.8
178,-7.6
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
1f 
1-2
0,""
0
[LAYERS:no]
9
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
016,0,5 , ,  , ,3      ,3,280, ,"rounded /melted",1
022,0,4 , ,  , ,2-3    ,3,300, ,"",1
070,0,4c, ,  , ,1-1.5  ,3,330, ,"",1
099,0,4c, ,  , ,.5-1   ,3,290, ,"",1
119,0,3 , ,  , ,.5     ,3,240, ,"",1
127,0,3 , ,  , ,.3     ,3,210, ,"",1
146,0,2 , ,  , ,.5-1.5 ,2,170, ,"",1
162,0,2 , ,  , ,1      ,1,090, ,"",1
178,0,1 , ,  , ,1-2    ,0,075, ,"",1
[SHEARS:no]
4
[shr_hgt,shr_test,shr_rslt,comment]
057,O,C,"TH (8)"
119,O,C,"TH (4) "
146,O,C,"TM X 2 DF / BTM"
162,O,B,"TE PP (Stellars)"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
" VERY STRONG SNOWPACK.  NO SIGNIFICANT WEAKNESSES OTHER THAN PRECIPITATION RELATED SHEARS IN NEW SNOW. THE CONCERN IS THAT SHALLOWER AREAS DO NOT HAVE THE SAME STRENGTH AS IS FOUND IN THIS PROFILE."
""
""
