[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Goat's Eye Plot"
.
99-02-18
13:40
"MH"
2300
M
.
.
0
99106
Full
a
25
.
2
2
4
.
0
0
-6.4
160
0
[TEMPERATURES:no]
17
[temp_hgt,temp]
0,-1.0
10,-1.5
20,-1.8
30,-2.3
40,-2.6
50,-3.1
60,-3.5
70,-4.0
80,-4.1
90,-4.8
100,-5.5
110,-6.3
120,-7.1
130,-7.8
140,-9.0
150,-8.8
160,-5.4
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1d 
.
3
0,""
0
[LAYERS:no]
9
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
007,0,9e, ,  , ,       ,3,290, ,"",1
010,0,5 , ,  , ,2-3    ,2,   , ,"",1
020,0,  , ,  , ,       ,2,350, ,"1F -",1
038,0,3 , ,4 , ,1.5    ,3,360, ,"",1
068,0,3 , ,4 , ,2      ,2,300, ,"1F+",1
119,0,3 , ,4 , ,.5     ,3,310, ,"",1
139,0,4 , ,2 , ,.5 -1  ,2,240, ,"",1
150,0,2 , ,4 , ,.5/ 1.5,1,200, ,"",1
160,0,2 , ,  , ,1.5-2  ,0,120, ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
119,S,H,"CTH on FC & DF .5-1.5"
139,S,M,"BTM on DF 1-1.5mm"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
