[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Goat's Eye Plot"
.
99-01-21
14:30
"TA/BL"
2300
M
.
NA
0
99105
Full
a
.
.
1
0
3
.
1
1
-6.7
138
0
[TEMPERATURES:no]
10
[temp_hgt,temp]
0,-0.6
20,-1.5
40,-2.0
60,-2.7
80,-3.7
100,-4.5
110,-5.7
120,-7.0
128,-7.5
138,-6.7
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
.
2.0-3.0
0,""
0
[LAYERS:no]
11
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
013,0,5 , ,  , ,3.5    ,3,   , ,"",1
029,0,4 , ,  , ,3.0    ,3,   , ,"",1
042,0,4 , ,  , ,1.5    ,3,   , ,"",1
059,0,4 , ,  , ,2.0    ,2,   , ,"",1
075,0,4 , ,  , ,1.5    ,2,   , ,"CT H2  ",2
079,0,4 , ,  , ,1.0    ,3,   , ,"CT H2",2
090,0,3 , ,4 , ,1.0    ,3,   , ,"CT H10  SS H @82",2
099,0,3 , ,  , ,1.5    ,2,   , ,"CT H3 twice",2
110,0,3 , ,  , ,1.0    ,1,   , ,"",1
126,0,3 , ,  , ,1.0    ,1,   , ,"",1
138,0,2 , ,  , ,1.0-2.0,0,   , ,"",1
[SHEARS:no]
0
[shr_hgt,shr_test,shr_rslt,comment]
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"99/01/21 -  1.  Size 2.5 in U2 (likely skier triggered but unreported, fresh today), from cornice at top of scalloped shaped slope, fractured in old layer, crown up to 1.0m.  2.  Skier triggered size 2 in U2 (nearby, next to D2) at time of profile.  Est. 35-40cm pack fractured on ground.  Took 2px for 90m ride over rock band.   3.  Also size 2.5 natural release at 0900 today in west side of B9 - toe @ almost to top of waterfall - reported by R Harper.   All triggers in shallow or new snow.  U2 has slid several times earlier this season."
