[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Goat's Eye Plot"
.
99-01-07
12:15
"RW/AF"
2300
M
.
NA
0
19104
Full
a
70
.
1
0
4
.
1
1
-4.1
117
0
[TEMPERATURES:no]
13
[temp_hgt,temp]
0,-0.2
10,-1.0
20,-1.5
30,-1.9
40,-2.5
50,-3.0
60,-3.4
70,-3.9
80,-4.0
90,-4.7
100,-5.1
107,-4.5
117,-4.5
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1f 
1 r
3/2.5
0,""
0
[LAYERS:no]
11
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
008,0,5 , ,4 , ,4/2    ,3,320, ,"",1
010,0,9e, ,  , ,       ,4,   , ,"Oct crust",1
012,0,5 , ,  , ,3      ,2,   , ,"",1
031,0,4 , ,  , ,1-1.5  ,3,340, ,"",1
039,0,4 , ,  , ,1-1.5  ,3,340, ,"",1
040,0,4 , ,  , ,1.5    ,2,330, ,"1F+",1
073,0,4 , ,  , ,1      ,1,270, ,"",1
079,0,3 , ,  , ,0.5    ,2,240, ,"",1
099,0,1 , ,3 , ,1/0.5  ,1,180, ,"",1
107,0,1 , ,2 , ,2.5/2  ,0,065, ,"",1
117,0,1 , ,  , ,3      ,0,050, ,"",1
[SHEARS:no]
3
[shr_hgt,shr_test,shr_rslt,comment]
012,O,C,"T M6"
073,O,C,"T H2"
099,O,C,"T E9 (fist snow)"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"Skier triggered class 1.5 in "U2" yesturday. Snow pack strengthening with increased sintering and rounding in the upper pack. The mid pack is providing good bridging above the lower pack weakness. Where the midpack is thinner - around rocks and cross loading areas - it may be possible to trigger a failure from the lower pack, as was the case yesturday.                                                                                                                                                                                                                                                     "
