[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Little Wawa"
.
98-12-05
14:39
"ML, GHI"
2100
M
.
SE
28
99506
Test
a
.
.
2
6
3
.
1
1
-13.8
72
0
[TEMPERATURES:no]
0
[temp_hgt,temp]
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
.
.
.
 ,""
0
[LAYERS:no]
8
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
007, ,  , ,  , ,       , ,   , ,"",1
016, ,  , ,  , ,       , ,   , ,"",1
045, ,  , ,  , ,       , ,   , ,"",1
050, ,  , ,  , ,       , ,   , ,"",1
052, ,7 , ,  , ,3      , ,   , ,"SH buried at 52, ste",1
060, ,  , ,  , ,       , ,   , ,"",1
068, ,  , ,  , ,       , ,   , ,"",1
072, ,  , ,  , ,       , ,   , ,"",1
[SHEARS:no]
0
[shr_hgt,shr_test,shr_rslt,comment]
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"RB 4 at surface hoar layer and at ground - simultaneously.  No settlement felt or heard on approach."
