[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Little Wawa"
.
98-12-26
11:40
"RW, ML"
2100
M
.
SE
28
99511
Test
a
.
.
2
1
4
.
1
1
-12.0
151
0
[TEMPERATURES:no]
6
[temp_hgt,temp]
100,-9.5
110,-10.8
120,-12.0
130,-12.4
141,-12.1
151,-11.2
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
.
.
.
 ,""
0
[LAYERS:no]
10
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
010, ,9e, ,  , ,       ,3,   , ,"Oct mfc",1
021, ,  , ,  , ,       ,3,   , ,"",1
077, ,  , ,  , ,       ,3,   , ,"",1
090, ,  , ,  , ,       ,3,   , ,"",1
100, ,  , ,  , ,       ,2,   , ,"Nov SH at interface 2mm",1
106, ,  , ,  , ,       ,3,   , ,"",1
115, ,  , ,  , ,       ,2,   , ,"",1
132, ,  , ,  , ,       ,2,   , ,"",1
145, ,  , ,  , ,       ,0,   , ,"",1
151, ,  , ,  , ,       ,0,   , ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
100,R,4,""
115,R,3,"Windslab"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
