[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Little Wawa"
.
99-02-24
11:55
"ML, AH"
2100
M
.
SE
36
99524
Test
.
.
.
3
5
4
.
1
1
-6.0
150
1
[TEMPERATURES:no]
5
[temp_hgt,temp]
0,-4.0
10,-7.8
20,-9.3
30,-9.5
40,-9.4
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
.
.
.
 ,""
0
[LAYERS:no]
5
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
008, ,  , ,  , ,       ,2,   , ,"",1
018, ,  , ,  , ,       ,1,   , ,"4F ",1
034, ,  , ,  , ,       ,1,   , ,"4F +",1
075, ,  , ,  , ,       ,2,   , ,"1F+",1
150, ,  , ,  , ,       ,3,   , ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
018,R,2,"Only one leg on"
034,R,2,"Only one leg on"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"Dug down about 150 cm. HS aproximately 400cm."
""
""
