[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"OBSERVATION PEAK"
.
98-12-22
12:30
"MIKE H. GP AH AM KS"
2400
M
.
S
28
99510
Test
b
30
20
1
0
1
.
0
0
-15.9
69
0
[TEMPERATURES:no]
7
[temp_hgt,temp]
0,-1.2
10,-2.3
20,-3.3
30,-5.1
40,-7.3
50,-10.2
59,-15.5
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
4  
7  
1
0,""
0
[LAYERS:no]
7
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
008,0,4 , ,  , ,2      ,2,   , ,"going to DH",1
017,0,4 , ,  , ,1.5    ,3,   , ,"",1
024,0,4 , ,  , ,1-1.5  ,3,   , ,"",1
041,0,4 , ,  , ,1      ,2,   , ,"",1
051,0,4 , ,  , ,1      ,2,   , ,"",1
068,0,4 , ,  , ,.5     ,0,   , ,"",1
069,0,9d, ,  , ,       , ,   , ,"",1
[SHEARS:no]
3
[shr_hgt,shr_test,shr_rslt,comment]
000,S,M,""
041,S,M,"comp M 5"
048,S,M,"uneven on FC 1-2"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
G
[COMMENTS]
"No new Aval. activity, winds calm, no new snow. Cold is starting to FC snowpack. The shallow snowpack  here will be very suseptible to this prolonged cold spell. "
