[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Odaray Plateau"
.
98-11-30
13:35
"GHI, SM"
2300
M
.
E
0
99505
Test
a
.
.
1
0
3
.
1
1
-6
86
0
[TEMPERATURES:no]
9
[temp_hgt,temp]
0,-0.2
20,-1.0
30,-1.6
40,-2.6
50,-3.2
60,-4.2
70,-5.9
76,-7.2
86,-6.0
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
.
.
.
0,""
0
[LAYERS:no]
7
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
019, ,  , ,  , ,       ,1,   , ,"ctm - 3",1
022, ,9e, ,  , ,       ,3,   , ,"ste.  cte w/ column cut",1
027, ,4 , ,  , ,       ,0,   , ,"",1
056, ,3 , ,  , ,       ,2,   , ,"",1
072, ,  , ,  , ,       ,1,   , ,"ste @ 72",1
081, ,  , ,  , ,       ,1,   , ,"",1
086, ,  , ,  , ,       ,0,   , ,"",1
[SHEARS:no]
0
[shr_hgt,shr_test,shr_rslt,comment]
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
F
[COMMENTS]
"Widespread settlements up to 30m as indicated by movement in small trees on way to site."
