[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Pika Flats"
.
99-04-14
14:30
"GP MH"
2300
M
.
S
0
99525
Test
a
20
.
0
0
1
.
.
0
-0.6
191
0
[TEMPERATURES:no]
10
[temp_hgt,temp]
110,-2.9
120,-3.0
130,-3.3
140,-3.4
150,-3.9
160,-4.0
170,-4.9
180,-4.0
190,-1.0
191,-1.6
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
.
.
.
 ,""
0
[LAYERS:no]
9
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
107, ,  , ,  , ,       ,3,   , ,"",1
108, ,  , ,  , ,       ,4,   , ,"",1
143, ,  , ,  , ,       ,3,   , ,"",1
157, ,  , ,  , ,       ,3,   , ,"",1
161, ,  , ,  , ,       ,4,   , ,"",1
177, ,  , ,  , ,       ,2,   , ,"",1
180, ,  , ,  , ,       ,2,   , ,"",1
186, ,  , ,  , ,       ,1,   , ,"",1
191, ,  , ,  , ,       ,0,   , ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
161,O, ,"  CTMX4 @161"
177,S,M,"  STM @161"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
