[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Pipestone Bowl"
.
98-12-30
12:52
"BW/DW"
7400
F
.
NE
30
99413
Test
a
40
.
3
7
2
.
0
0
-6.7
121
0
[TEMPERATURES:no]
13
[temp_hgt,temp]
0,-3.9
10,-4.6
20,-5.5
30,-5.9
40,-6.5
50,-7.5
60,-7.6
70,-7.9
80,-8.1
90,-8.2
100,-7.9
111,-7.1
121,-7.1
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
.
2
0,""
0
[LAYERS:no]
7
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
016,0,5 , ,  , ,6      ,2,022, ,"Old rain crust laminates",1
043,0,4 , ,  , ,1.5    ,3,280, ,"",1
069,0,4c, ,  , ,1      ,3,290, ,"",1
070,0,7 , ,  , ,2      ,3,   , ,"981129",1
094,0,4c, ,  , ,1      ,2,230, ,"",1
095,0,7 , ,4 , ,2/1.5  ,2,   , ,"thin wind crust",1
121,0,2 , ,  , ,1.5    ,1,110, ,"",1
[SHEARS:no]
4
[shr_hgt,shr_test,shr_rslt,comment]
016,M, ,"10 below crust"
070,M, ,"8 RB 4 FC and SH"
094,R, ,"3 Under thin crust"
095,M, ,"6"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
" 25cm HST largely unconsolidated as yet. 981223 layer has thin WC over SH and FC at this location: RB3.  Shortly after pit was dug three leading edge forecasters cut across the whole of Pipestone Bowl through the ideal ski cut points. No results."
""
"  "
