[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Pipestone Bowl"
.
99-01-19
11:30
"MH,AM,JM"
7500
F
.
NE
30
99517
Test
a
40
20
1
0
8
.
1
1
-6.4
197
0
[TEMPERATURES:no]
16
[temp_hgt,temp]
0,-1.9
20,-2.2
40,-2.6
60,-3.2
80,-3.7
100,-4.1
110,-4.3
120,-4.8
130,-5.5
140,-6.5
150,-7.2
160,-7.9
170,-8.5
180,-8.8
187,-8.5
197,-8.4
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
.
1-1.5
0,""
0
[LAYERS:no]
13
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
013,0,5 , ,  , ,3-4    ,1,   , ,"",1
024,0,4 , ,  , ,2      ,2,   , ,"",1
051,0,3 , ,  , ,.5-1   ,3,   , ,"",1
075, ,3 , ,  , ,1      ,3,   , ,"1F +",1
086,0,3 , ,  , ,1      ,2,   , ,"",1
111,0,3 , ,  , ,1      ,3,   , ,"",1
119,0,3 , ,  , ,.5     ,3,   , ,"",1
132,0,3 , ,  , ,.5     ,3,   , ,"",1
147,0,3 , ,  , ,.5     ,2,   , ,"",1
163,0,2 , ,3 , ,.5-1   ,2,   , ,"1F -",1
175,0,2 , ,3 , ,.5-1   ,2,   , ,"4F +",1
191,0,2 , ,3 , ,.5-1   ,1,   , ,"",1
197,0,1 , ,2 , ,1-1.5  ,0,   , ,"",1
[SHEARS:no]
1
[shr_hgt,shr_test,shr_rslt,comment]
147,R,4,"clean on DF stellars"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
F
[COMMENTS]
"1 Natural 1.5 on windloaded feature on National Geos. Extensive skier and rider testing on all slopes out of lease area at LL producing no results. ( there must have been 30 people out there! ) "
"Slab tighteneing up and stil reacting on DF stellars and plates. "
