[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"PUMPKIN PEAK"
.
99-04-15
12:50
"MH"
7440
F
.
NW
10
99527
Test
a
15
10
1
0
1
.
0
0
-1.5
123
0
[TEMPERATURES:no]
5
[temp_hgt,temp]
90,-3.9
100,-6.0
110,-7.1
120,-3.7
123,-4.0
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
4  
.
.
0,""
0
[LAYERS:no]
7
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
016,0,5 , ,  , ,3      ,1,   , ,"",1
060, ,  , ,  , ,       ,2,   , ,"",1
062, ,  , ,  , ,       ,2,   , ,"",1
086, ,  , ,  , ,       ,2,   , ,"",1
093, ,  , ,  , ,       ,2,   , ,"",1
115, ,  , ,  , ,       ,2,   , ,"",1
123,0,  , ,  , ,       ,0,   , ,"",1
[SHEARS:no]
0
[shr_hgt,shr_test,shr_rslt,comment]
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"Winter snow pack complete with DH. Strong TG in top 30cm, creating FCs. No results with Burp or Comp. Class 1 - 1.5 on south Asp. with HN over melt freeze crust. Excellent travelling."
