[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Purple Bowl - N Face"
.
99-02-03
12:45
"BW, DI, ML"
2625
M
.
N
24
99520
Test
.
.
.
3
7
3
.
0
0
-9.5
223
1
[TEMPERATURES:no]
0
[temp_hgt,temp]
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
.
.
.
0,""
0
[LAYERS:no]
4
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
006, ,  , ,  , ,       ,1,   , ,"",1
034, ,  , ,  , ,       ,3,   , ,"",1
058, ,  , ,  , ,       ,2,   , ,"1F +",1
077, ,  , ,  , ,       ,3,   , ,"Pencil +",1
[SHEARS:no]
4
[shr_hgt,shr_test,shr_rslt,comment]
006,O,C,"TM"
034,S,H,""
058,S,H,""
077,S,H,""
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
