[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Shaeffer Bowl"
.
98-12-31
14:50
"BW/MH/RW"
7300
F
.
N
28
99514
Test
a
40
.
3
7
4
.
1
1
-3.0
117
0
[TEMPERATURES:no]
0
[temp_hgt,temp]
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
.
.
 ,""
0
[LAYERS:no]
4
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
040, ,4 , ,5 , ,       ,2,   , ,"",1
074, ,4 , ,  , ,       ,1,   , ,"",1
096, ,2 , ,  , ,       ,1,   , ,"",1
117, ,2 , ,  , ,       ,0,   , ,"",1
[SHEARS:no]
1
[shr_hgt,shr_test,shr_rslt,comment]
074,R,6,"on fc and old stellars"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"2 natural size 1.5/2 in HST on NW aspect of shaeffer bowl during last 24 hrs Crown depth 20-40 cm, ran only a short way down the path. Likely wind stiffening HST into slab.                                                                                                                                                                                                                                                                                                                                                                                                                   "
