[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Schaffer Bowl"
.
99-01-15
11:05
"GI JN"
2200
M
.
NW
30
99516
Test
a
.
.
2
4
4
.
1
1
-8
186
0
[TEMPERATURES:no]
8
[temp_hgt,temp]
40,-1.0
60,-2.0
80,-3.0
100,-3.0
120,-5.0
140,-5.0
160,-6.0
180,-8.0
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
2  
1 r
.5
0,""
0
[LAYERS:no]
9
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
028,0,4 , ,5 , ,2-3    ,2,   , ,"",1
057,0,4 , ,  , ,1.5    ,3,   , ,"",1
091,0,4 , ,  , ,1      ,2,   , ,"1F+",1
115,0,3 , ,  , ,.5     ,3,   , ,"P+",1
142,0,3 , ,  , ,.5     ,3,   , ,"",1
159,0,2 , ,  , ,1      ,1,   , ,"",1
167,0,2 , ,3 , ,.5     ,2,   , ,"",1
180,0,1 , ,2 , ,1      ,0,   , ,"",1
186,0,1 , ,2 , ,1      ,0,   , ,"",1
[SHEARS:no]
3
[shr_hgt,shr_test,shr_rslt,comment]
130,R,3,"  RB 3 @ 130 on 2mm "
159,O, ,"comp easy 159"
173,O,c,"omp easy 173"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
P
[COMMENTS]
"RB 3 @ 130 on 2mm plates and stellars"
