[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Stanley Glacier"
.
99-01-03
12:00
"GHI/RW"
.
M
.
NE
20
99515
Test
a
42
23
2
8
3
.
0
0
-10.7
77
0
[TEMPERATURES:no]
8
[temp_hgt,temp]
0,-3.1
10,-3.5
20,-4.0
30,-4.6
40,-6.0
50,-7.8
60,-9.1
70,-10.8
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
.
2
 ,""
0
[LAYERS:no]
9
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
013, ,4 , ,5 , ,2 - 3  ,2,   , ,"",1
018, ,4 , ,  , ,1      ,3,   , ,"",1
031, ,4 , ,  , ,1 - 1.5,2,   , ,"",1
032, ,4 , ,  , ,1      ,1,   , ,"",1
048, ,4 , ,  , ,1      ,1,   , ,"",1
050, ,4 , ,3 , ,.5     ,3,   , ,"",1
054, ,4 , ,3 , ,.5 -.25,2,   , ,"",1
057, ,3 , ,  , ,.5     ,1,   , ,"",1
077, ,2 , ,  , ,1      ,0,   , ,"",1
[SHEARS:no]
0
[shr_hgt,shr_test,shr_rslt,comment]
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"cte 3 at 69, cth 5 at 32 (df 2.5)  no results from st, burp hard at 32"
