[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Takakkaw"
.
98-02-19
11:00
"PW ALH"
1560
M
.
NA
0
98405
Full
a
.
.
2
6
3
.
0
0
-0
105
0
[TEMPERATURES:no]
12
[temp_hgt,temp]
0,0.0
10,-1.0
20,-1.0
30,-1.0
40,-1.0
50,-2.0
60,-2.0
70,-2.0
80,-3.0
90,-3.0
95,-2.0
105,0.0
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
7  
2  
3    1
1,""
0
[LAYERS:no]
7
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
029,0,5 , ,4 , ,310    ,2,310, ,"",1
052,0,4 , ,  , ,.5-1   ,3,340, ,"",1
085,0,3 , ,4 , ,.5     ,3,360, ,"",1
094,0,3 , ,4 , ,1      ,3,280, ,"easy P",1
095,0,3 , ,  , ,1      , ,   , ,"conglomerates",1
100,1,3 , ,  , ,.5-1   ,1,220, ,"",1
105,1,2 , ,  , ,1      ,0,100, ,"",1
[SHEARS:no]
1
[shr_hgt,shr_test,shr_rslt,comment]
029,O, ,"    CTM X6 @29"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
