[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Takakkaw"
.
98-12-09
10:20
"PW MH"
1560
M
.
NA
0
99402
Full
a
.
.
1
0
4
.
0
0
-7.5
80
0
[TEMPERATURES:no]
9
[temp_hgt,temp]
0,0.0
10,-1.0
20,-2.0
30,-3.0
40,-3.0
50,-4.0
60,-5.0
70,-6.5
80,-5.0
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
1f 
4   2
 ,""
0
[LAYERS:no]
11
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
006,0,4 , ,  , ,.5-1   ,3,340, ,"",1
008,0,4 , ,  , ,1-2    ,3,   , ,"conglomerate",1
013,0,4 , ,  , ,.5     ,3,320, ,"",1
014,0,4 , ,  , ,1-1.5  ,4,   , ,"conglomerate",1
025,0,4 , ,3 , ,1      ,3,300, ,"",1
041,0,4 , ,3 , ,.5     ,3,250, ,"",1
048,0,8 , ,  , ,2      ,3,330, ,"",1
050,0,4 , ,  , ,1      , ,   , ,"",1
059,0,4 , ,  , ,.5     ,2,200, ,"",1
078,0,2 , ,  , ,.5-1   ,1,140, ,"",1
080, ,1 , ,2 , ,2-4    ,0,   , ,"",1
[SHEARS:no]
1
[shr_hgt,shr_test,shr_rslt,comment]
048,S,H," STH  @ 48 on size 1 FC"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"STH @ 48,  hard pull but smooth shear, repeatable.   "
