[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Takakkaw"
.
98-11-28
13:40
"PW AH"
1560
M
.
NA
0
99401
Full
a
.
.
1
0
2
.
0
0
-3
83
0
[TEMPERATURES:no]
10
[temp_hgt,temp]
0,0.0
10,-0.5
20,-1.7
30,-2.8
40,-3.7
50,-4.6
60,-4.6
70,-5.0
73,-6.1
83,-4.0
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1f 
1  
1   3
 ,""
0
[LAYERS:no]
10
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
010, ,4 , ,  , ,1      ,2,   , ,"",1
012, ,9e, ,  , ,1.0    ,3,   , ,"",1
018, ,4 , ,3 , ,.5     ,2,   , ,"",1
020, ,9e, ,  , ,.5     ,4,   , ,"",1
040, ,3 , ,4 , ,.5     ,3,   , ,"",1
062, ,3 , ,  , ,.5     ,2,   , ,"",1
067, ,9e, ,  , ,1      ,3,   , ,"",1
070, ,9e, ,2 , ,.5     ,2,   , ,"",1
080, ,1 , ,2 , ,1      ,1,   , ,"",1
083, ,1 , ,2 , ,1   2  ,0,   , ,"",1
[SHEARS:no]
1
[shr_hgt,shr_test,shr_rslt,comment]
062,S,H,"  STH X2 @62"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
