[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Takakkaw"
.
99-03-03
12:20
"GI JM SR"
1560
M
.
NA
0
99406
Full
a
.
.
1
0
4
.
1
1
-1
189
0
[TEMPERATURES:no]
16
[temp_hgt,temp]
0,-0.2
10,-0.4
30,-0.9
50,-1.3
70,-1.8
90,-2.2
100,-2.3
110,-2.6
120,-2.8
130,-3.0
140,-3.2
150,-3.5
160,-4.0
170,-4.2
179,-3.1
189,-0.5
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
.
3
 ,""
0
[LAYERS:no]
10
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
049, ,3 , ,  , ,2      ,3,430, ,"",1
053, ,9 , ,  , ,       ,2,   , ,"",1
134, ,3 , ,  , ,.5     ,3,350, ,"",1
161, ,3 , ,  , ,1      ,2,290, ,"",1
163, ,7 , ,  , ,       ,0,   , ,"",1
170, ,3 , ,  , ,.5     ,1,160, ,"",1
172, ,3 , ,  , ,.5     ,2,   , ,"",1
176, ,2 , ,  , ,1-1.5  ,0,140, ,"",1
183, ,1 , ,2 , ,2      ,0,130, ,"",1
189, ,1 , ,2 , ,2      ,0,090, ,"",1
[SHEARS:no]
4
[shr_hgt,shr_test,shr_rslt,comment]
049,O, ,"   1 cm ice crust"
163,O, ,"   CTE @163 on V"
176,O, ,"   CTE @ 176 on V"
183,O, ,"  CTE @183"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
