[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Takakkaw"
.
99-01-06
13:00
"GHI, MH"
1560
M
.
NA
0
99404
Full
a
40
.
1
0
4
.
1
2
-9.9
137
0
[TEMPERATURES:no]
14
[temp_hgt,temp]
0,-0.1
10,-0.7
20,-1.2
30,-1.7
40,-2.2
50,-2.6
60,-3.1
70,-3.7
80,-4.2
90,-4.8
100,-5.8
110,-6.7
120,-7.8
130,-7.8
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
.
2.5
0,"rimed"
0
[LAYERS:no]
12
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
010,0,4 , ,  , ,1.5    ,3,350, ,"",1
012, ,9e, ,  , ,       ,4,   , ,"",1
033,0,4 , ,3 , ,1      ,3,360, ,"",1
042,0,4 , ,  , ,1.5    ,3,400, ,"conglomerate",1
058,0,4 , ,  , ,1      ,2,300, ,"facets are rounding",1
061,0,4 , ,  , ,1      ,1,300, ,"",1
069,0,4 , ,  , ,1      ,1,220, ,"",1
071,0,9e, ,  , ,       ,4,   , ,"",1
096,0,2 , ,3 , ,1      ,2,180, ,"",1
118,0,2 , ,  , ,1-1.5  ,1,135, ,"4F hard",1
132,0,2 , ,  , ,1.5    ,0,090, ,"",1
137,0,1 , ,  , ,2.5    ,0,060, ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
071,S,M,"ST M"
121,S,E,"COMP   E  2 "
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
F
[COMMENTS]
"The main layer  of concern around Tak and lower elevation slopes in Yoho is the raincrust below the Christmas storm cycle snow. Breaking the crust results in easy shears. No nat. aval. activity seen today. "
