[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Takakkaw"
.
99-03-24
10:00
"PW"
1560
M
.
NA
0
99407
Full
a
.
.
0
0
2
.
.
0
-0.4
158
0
[TEMPERATURES:no]
17
[temp_hgt,temp]
0,-0.2
10,-0.5
20,-0.5
30,-0.5
40,-0.7
50,-0.7
60,-0.8
70,-0.8
80,-0.8
90,-0.7
100,-0.7
110,-0.5
120,-0.4
130,-0.3
140,-0.3
148,-0.4
158,-0.8
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
8a 
.
1-2
0,""
0
[LAYERS:no]
10
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
017,1,3 , ,  , ,3      ,3,   , ,"",1
027,1,3 , ,  , ,2-3    ,2,   , ,"",1
045,1,3 , ,  , ,1.5    ,3,   , ,"",1
049,1,3 , ,  , ,1      ,2,   , ,"",1
065,1,3 , ,  , ,1.5    ,4,   , ,"",1
112,1,3 , ,  , ,.5-1.5 ,3,   , ,"",1
127,1,3 , ,  , ,.5     ,3,   , ,"",1
139,1,3 , ,  , ,.5     ,2,   , ,"",1
143,1,3 , ,  , ,1      ,3,   , ,"",1
158,0,8 , ,  , ,1      ,4,   , ,"sandwich of crusts",1
[SHEARS:no]
0
[shr_hgt,shr_test,shr_rslt,comment]
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
