[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Takakkaw"
.
99-02-03
12:00
"MH"
1560
M
.
NA
0
99405
Full
a
.
.
1
0
3
.
0
0
-3.0
204
0
[TEMPERATURES:no]
15
[temp_hgt,temp]
0,-0.7
20,-1.1
40,-1.6
60,-2.5
80,-3.2
100,-3.7
120,-4.0
140,-4.5
150,-4.7
160,-4.8
170,-4.9
180,-5.5
190,-6.5
194,-6.3
204,-3.7
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
.
1
0,"RIMED"
0
[LAYERS:no]
14
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
030,0,4 , ,  , ,1.5    ,3,400, ,"P +",1
034,0,8 , ,  , ,       ,3,   , ,"DISCONTINOUS CRUST",1
040,0,5 , ,  , ,3      ,2,280, ,"",1
059,0,4 , ,  , ,1.5    ,3,310, ,"",1
076,0,3 , ,  , ,1      ,3,390, ,"",1
111,0,4c, ,  , ,1      ,3,250, ,"P +",1
129,0,3 , ,  , ,.5     ,3,260, ,"",1
148,0,3 , ,  , ,.5     ,3,220, ,"",1
164,0,3 , ,  , ,.5     ,3,200, ,"",1
170,0,2 , ,  , ,.5     ,1,140, ,"1F E",1
176,0,2 , ,3 , ,.5     ,2,150, ,"",1
186,0,2 , ,  , ,1      ,1,110, ,"",1
196,0,1 , ,2 , ,1.5    ,1,100, ,"",1
204,0,1d, ,  , ,1.5    ,0,070, ,"",1
[SHEARS:no]
3
[shr_hgt,shr_test,shr_rslt,comment]
034,S,H,"CTH 1 DH 3mm"
164,S,M,"CTM 6  / .5mm - 1mm"
183,S,E,"Burp + / 1.5mm - 2 mm"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"A weak temp gradient is promoting rnding in this 2 m snow pack. Dicontinous crust at 34 cm is causing DH above, however this is strongly bridged.  New snow instabilites are found in the first 30 cm but unreactive in steep ski tests. Despite high winds in the alp. only 1 class 2 was seen from Mt. Ogden reaching TR. Giant cornices are formed on Wapta and Michael Peaks.    "
