[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Takakkaw"
.
99-02-17
11:00
"MH, GHI"
1560
M
.
NA
0
99406
Full
a
10
.
1
0
4
.
1
3
-5.0
178
0
[TEMPERATURES:no]
19
[temp_hgt,temp]
0,-0.5
10,-0.6
20,-0.9
30,-1.1
40,-1.4
50,-1.8
60,-2.1
70,-2.3
80,-2.7
90,-3.1
100,-3.6
110,-4.0
120,-4.3
130,-5.1
140,-5.7
150,-6.5
160,-7.1
168,-5.9
178,-3.0
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
.
1.5
0,""
0
[LAYERS:no]
9
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
023,1,3 , ,  , ,1.5    ,3,410, ,"FC to RDs",1
032,0,4c, ,  , ,2      ,3,310, ,"FC to RDs (P -)",1
053,0,3 , ,  , ,2      ,3,390, ,"FC to RDs",1
058,0,9e, ,  , ,       ,4,   , ,"variable thickness",1
135,0,3 , ,  , ,.5     ,3,380, ,"",1
149,0,3 , ,  , ,1.0    ,3,290, ,"",1
163,0,4 , ,3 , ,1.0    ,2,180, ,"",1
171,0,2 , ,4 , ,.5-1   ,1,160, ,"",1
178,0,2 , ,  , ,1-1.5  ,0,110, ,"",1
[SHEARS:no]
4
[shr_hgt,shr_test,shr_rslt,comment]
023,S,M,"STH uneven"
053,S,H,"CTH below crust "
138,S,H,"CTH clean, on old V & DF"
163,S,M,"Burp M & CTM DF & FC"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"Large settlement in past 2 weeks. ( prev. HS 204, 2 week int.  21cm, new HS 178) Boot penetration is now 10 cm. Weak temp gradient is rounding out old facets under crust. The new snow is sluffing in steep unskiable terrain and there was some evidence of nat. avals on Silk Tassel from solar heating.    "
