[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"The Crow's Missing Toe"
.
99-03-12
10:24
"RW  PW"
2030
M
.
SE
32
99524
Test
a
24
.
0
0
4
.
1
1
-7.4
370
1
[TEMPERATURES:no]
11
[temp_hgt,temp]
0,-7.0
10,0.3
20,-9.7
30,-9.3
40,-8.4
50,-7.9
60,-7.7
70,-7.5
80,-7.2
90,-7.0
100,-6.9
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
4  
.
.25
 ,""
0
[LAYERS:no]
6
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
011, ,2 , ,  , ,1.5    ,0,   , ,"",1
025, ,2 , ,  , ,1.5    ,0,   , ,"",1
044, ,4 , ,2 , ,.25/ 1 ,1,   , ,"",1
089, ,3 , ,  , ,.25-.5 ,2,   , ,"",1
103, ,3 , ,  , ,.5     ,3,   , ,"",1
141, ,3 , ,  , ,.5     ,3,   , ,"",1
[SHEARS:no]
3
[shr_hgt,shr_test,shr_rslt,comment]
011,O, ,"   CTM @ 11"
025,O, ,"   CTM @ @25"
044,O, ,"   CTM @ 44"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
