[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Teepee Town"
.
99-03-05
10:30
"RW"
2275
M
.
NA
0
99107
.
a
41
.
1
0
2
.
0
0
-6.9
171
0
[TEMPERATURES:no]
18
[temp_hgt,temp]
0,-0.2
10,-0.6
20,-0.9
30,-1.2
40,-1.5
50,-1.9
60,-2.3
70,-2.6
80,-2.9
90,-3.3
100,-3.6
110,-3.7
120,-3.7
130,-4.2
140,-5.1
150,-7.0
160,-10.0
171,-10.1
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1d 
1a 
3/1
 ,""
0
[LAYERS:no]
11
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
019,0,5 , ,4 , ,3/2    ,3,310, ,"Weeker in the upper 1/3 (1F+)",1
062,0,4 , ,  , ,1.5    ,3,330, ,"",1
067,0,4c, ,  , ,0.5-1  ,3,360, ,"",1
103,0,4c, ,  , ,0.5-1  ,3,340, ,"",1
112,0,3 , ,  , ,0.5-1  ,3,350, ,"",1
125,0,3 , ,  , ,0.5    ,3,300, ,"",1
136,0,3 , ,4 , ,1      ,2,250, ,"",1
148,0,4 , ,3 , ,1/0.5  ,2,210, ,"",1
155,0,2 , ,4 , ,1/0.25 ,1,170, ,"",1
162,0,2 , ,  , ,1-2    ,0,140, ,"",1
171,0,1 , ,2 , ,2/1    ,0,090, ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
148,O,C,"T M7"
162,O,C,"T E2"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
""
