[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Teepee Town Plot"
.
98-11-23
13:15
"BW / ML"
.
M
.
NA
0
99101
Full
a
30
.
1
0
4
.
1
1
-6.0
74
0
[TEMPERATURES:no]
9
[temp_hgt,temp]
0,-0.1
10,-0.5
20,-1.1
30,-1.9
40,-3.3
50,-4.0
60,-5.5
64,-6.2
74,-5.5
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1dr
.
3
0,""
0
[LAYERS:no]
6
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
016,0,9e, ,  , ,       ,4,280, ,"Laminated/percolated CR",1
019,0,4 , ,  , ,2-4    ,1,150,e,"Striated",1
042,0,3 , ,  , ,.5     ,2,220, ,"",1
057,0,2 , ,  , ,1      ,1,130, ,"",1
068,0,2 , ,  , ,1      ,1,120, ,"",1
074,0,2 ,r,1d, ,1.5    ,0,080, ,"",1
[SHEARS:no]
3
[shr_hgt,shr_test,shr_rslt,comment]
016,S,S,"ee Note 1"
057,S,M,"SC Mod 9"
068,S,M,"SC Mod 6"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"     Most of the snow has come in the last 10 days. Moderate snowfall intensities and warm temperatures have created a strong mid-pack. The main layer of concern is the layer of facets sitting on top of a melt-freeze crust at the base of the snowpack. Nearby EX and SA avalanches are running on this crust. Stability test results are in the Mod-Hard range with a clean bed."
""
""
""
