[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Vermilion plot"
.
99-02-09
10:00
"GHI, DI"
.
M
.
NA
0
99306
Full
a
45
28
1
0
2
.
0
0
-13.7
234
0
[TEMPERATURES:no]
24
[temp_hgt,temp]
0,-0.5
10,0.0
20,-1.6
30,0.0
40,-2.1
50,0.0
60,-2.6
70,0.0
80,-3.3
90,0.0
100,-3.8
110,-3.7
120,-4.3
130,-4.6
140,-4.4
150,-5.3
160,-5.7
170,-6.0
180,-6.5
190,-7.0
200,-8.4
210,-10.8
220,-14.0
224,-16.5
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
2  
2
0,""
0
[LAYERS:no]
14
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
015, ,5 , ,  , ,2-3    ,2,390, ,"",1
041, ,4 , ,  , ,2      ,3,380, ,"",1
047, ,4 , ,  , ,1.5-2  ,3,390, ,"",1
081, ,4 , ,  , ,1.5    ,3,370, ,"",1
124, ,3 , ,  , ,.5 - 1 ,3,350, ,"",1
130, ,3 , ,  , ,1      ,3,310, ,"",1
153, ,3 , ,  , ,.5 - 1 ,3,320, ,"",1
158, ,3 , ,  , ,.5     ,2,270, ,"",1
168, ,3 , ,  , ,.5     ,3,240, ,"",1
173, ,3 , ,  , ,.5     ,2,220, ,"cth8 @ 173",1
179, ,3 , ,  , ,.25    ,3,240, ,"",1
203, ,3 , ,  , ,.5     ,2,140, ,"cth sth @ 189 some V",1
225, ,2 , ,  , ,.5 - 1 ,1,110, ,"ctm3 @ 225",1
234, ,2 , ,  , ,1      ,0,060, ,"",1
[SHEARS:no]
0
[shr_hgt,shr_test,shr_rslt,comment]
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"Profile and telemetry check done with SLL staff,  Dave Ilse and Rocket Miller."
