[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Wawa"
.
99-02-22
12:00
"RW"
2720
M
.
NE
25
99523
Test
a
36
.
3
1
3
.
1
1
-6.5
130
1
[TEMPERATURES:no]
8
[temp_hgt,temp]
0,-5.2
10,-10.1
20,-10.9
30,-10.8
40,-11.2
50,-11.2
60,-10.9
70,-11.1
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
2  
.
1
 ,""
0
[LAYERS:no]
6
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
020,0,1 , ,2 , ,1      ,1,   , ,"",1
036,0,1 , ,2 , ,1      ,2,   , ,"",1
046,0,3 , ,2 , ,1      ,3,   , ,"",1
064,0,3 , ,2 , ,0.3/1  ,3,   , ,"",1
077,0,3 , ,2 , ,0.5/1  ,3,   , ,"",1
105,0,3 , ,  , ,0.5    ,3,   , ,"",1
[SHEARS:no]
2
[shr_hgt,shr_test,shr_rslt,comment]
020,S,M," 1"
064,S,H,"2"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"The total depth of the snow pack at this location was in excess of 370 cm. The area was at the very upper end of tree line a little below ridge top.                                                                                                                                                                                                                                                                                            "
