[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Wawa Ridge"
.
99-02-06
10:40
"GHI/ML"
7800
F
.
SE
26
99522
Test
a
.
.
2
6
4
.
1
1
-8.4
200
1
[TEMPERATURES:no]
3
[temp_hgt,temp]
10,-10.8
20,-10.6
30,-9.7
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
.
.
.
 ,""
0
[LAYERS:no]
4
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
024, ,  , ,  , ,       ,1,   ,e,"rb 2 down 24",1
052, ,  , ,  , ,       ,3,   , ,"rb 4 down 52,  ste down 40",1
072, ,  , ,  , ,       ,1,   , ,"rb 4 down 72",1
150, ,  , ,  , ,       ,3,   , ,"150 for graph only",1
[SHEARS:no]
0
[shr_hgt,shr_test,shr_rslt,comment]
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"*******Total snow depth 390********  Profile done from top down."
