[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"WOLVERINE RIDGE"
.
99-01-05
15:20
"MH, GP"
2250
M
.
N
30
99515
Test
a
30
20
2
8
4
.
1
2
-4.2
95
0
[TEMPERATURES:no]
0
[temp_hgt,temp]
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1  
.
.
 ,""
0
[LAYERS:no]
8
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
009, ,  , ,  , ,       ,1,   , ,"",1
013, ,9e, ,  , ,       ,2,   , ,"VARIABLE",1
030, ,  , ,  , ,       ,2,   , ,"1F EASY",1
061, ,  , ,  , ,       ,2,   , ,"",1
068, ,  , ,  , ,       ,2,   , ,"",1
078, ,  , ,  , ,       ,1,   , ,"4F HARD",1
089, ,  , ,  , ,       ,1,   , ,"",1
095, ,  , ,  , ,       ,0,   , ,"",1
[SHEARS:no]
4
[shr_hgt,shr_test,shr_rslt,comment]
000,S,M,"COMP T M 6"
039,R,4,"FACETS"
068,S,M,"BURP"
078,R,4,"STELLARS"
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
U
[COMMENTS]
"No new aval. activity seen. Winds Mod to strong in Alp. from NW, snow transport and loading occurring. Snow pack at site is facetted from previous cold wx. Infromation gathered BTL, slab concern at TL and ALP.   "
