[SNOWPROFILE: version]
2.1
[prf_desc,area_cd,prf_dt,prf_tm,tech_id,elevation,units,loc_lat,loc_lon,aspect,incline,prf_no,prf_typ,surf_rgh,foot_pen,ski_pen,wind_spd,wind_dir,sky_cond,ram_ttl,prcp_typ,prcp_rt,air_temp,height,lvl_ind]
"Wawa Ridge"
.
98-12-15
10:30
"TA/DH"
7800
F
571845,5651604
SE
25
98509
Test
a
40
.
2
6
4
.
1
2
-9.7
109
0
[TEMPERATURES:no]
8
[temp_hgt,temp]
0,-1.2
20,-2.0
40,-3.0
60,-3.7
70,-5.4
80,-7.3
90,-9.9
99,-11.3
[SURFACE:grain_sf1,grain_sf2,grain_sfs,surf_water,surf_com,bottom_pit]
1 r
.
1
0,""
0
[LAYERS:no]
9
[layer_hgt,water_cnt,grain_fm1,grain_rm1,grain_fm2,grain_rm2,size,hand_hrd,density,dens_est,comments,position]
012,0,4 , ,  , ,2.5    ,3,   , ,"Some DH size 3 at grnd",1
031,0,3 , ,  , ,0.25   ,2,   , ," ",0
053,0,4 , ,  , ,1.5    ,3,   , ," ",0
068,0,4 , ,  , ,2.0    ,3,   , ," R5 (clean shear)@53",2
074,0,4 , ,  , ,1.5    ,2,   , ,"R5 (clean shear)@68 cth-2",2
084,0,4 , ,  , ,1.5    ,2,   , ,"R4 (clean shear) ctm-2 @84",0
103,0,3 , ,  , ,1.5    ,2,   , ," ",0
106,0,3 , ,  , ,0.5    ,0,   , ," ste@99",2
109,0,1 ,r,  , ,1.5    ,0,   , ,"",1
[SHEARS:no]
0
[shr_hgt,shr_test,shr_rslt,comment]
[RAM:no]
0
[delta_p,ram_hard]
[STABILITY]
F
[COMMENTS]
""
